### ISSUE TITLE
Add OSM POI Layer

### ISSUE THREAD

**Issue by SwiftFast** [IsraelHikingMap/Site#363] opened 2017-06-24 10:12 UTC
Currently, searching for a POI displays a popup, but the popup is pretty barren. Ideally the popup should include the tags (or a selection of important tags, like opening hours, track type, etc.), and perhaps even an image (obtained from `image` / `wikidata` / `wikimedia_commons` / `wikipedia`) 

The data does not have to be hosted on IHM and can simply be queried upstream by the client.

Secondly, clicking a POI does not do anything, and I think it should display the same search popup.

**Comment by HarelM** [comment] 2017-06-24 10:23
Can you please elaborate a bit?
Please note that we are working to improve the whole concept of POIs in the site (currently it only Wikipedia), so this might be a barge into an open door.
Having said that I don't think I fully understand your requirements.
Current search is using data stored only in OSM and takes some data like name, address, type (for the icon).
We hope to improve this by getting data from other places by cooperate with other projects.
Currently we are not planning on building a mechanism to store and present POI from users for obvious reasons.
> Secondly, clicking a POI does not do anything, and I think it should display the same search popup.

Is this a bug? I don't understand what's not working...

**Comment by SwiftFast** [comment] 2017-06-24 10:41
It seems there's some misunderstanding so let me try to rephrase. Let's ignore the wiki / image bit for now, that's not essential.

by POI I mean any OSM primitive node or way, e.g. amenities, fuel shops, etc.I am looking at a supermarket right now, on the main site. 

![1](https://user-images.githubusercontent.com/28669244/27507888-4b98d784-58e2-11e7-83f2-7940be20a3a7.png)

If I click that supermarket, nothing happens. (I've always assumed this is a missing feature, not a bug). On the other hand, if I search for it by name, its outline is marked and a pop up shows:

![2](https://user-images.githubusercontent.com/28669244/27507895-692d2bb0-58e2-11e7-81d0-240f5e61ae46.png)

I'd want that pop up to show up on left-click, not just on textual search. It's a very basic feature (which osm.org also lacks for some reason!).

Also, I'd want that pop up to be more descriptive, at the very least telling me what I'm looking at (shop=supermarket) or maybe showing all tags.

As an optional bonus, that pop up would show a picture, obtained via one of the tags mentioned in the first post.

**Comment by SwiftFast** [comment] 2017-06-24 10:43
Regarding osm.org: That feature is available via right click -> query features, but that's needlessly fiddly imo.

**Comment by HarelM** [comment] 2017-06-24 11:06
I see.
I'll try to do my best answering, I assume you'll find my answer unsatisfying though.
1. POIs is a very complex problem - first and foremost because there are too many sources, each one has its own quirks and it won't be easy to combine them to a decent single place.
2. Search is processing data from OSM and stores it locally on the server, what it basically does is save everything that has a name - in order to do what you want - present relevant info according to node type requires a lot of code writing, which in most cases will not be used, so this automatically lowers the priority of developing it (low ROI).
3. While we can add data to OSM and add this capability there's a lot of data missing in OSM and so we'll probably won't be able to relay solely on it for a while.
In any case, I agree that data from OSM should be interactive and not just part of the map itself, I hope to be able to implement something to improve this, but there are other things to consider beside the code itself which I can't elaborate on.

**Comment by SwiftFast** [comment] 2017-06-24 11:32
In my humble opinion, that's overcomplicating it. IHM tiles use OSM, so anything that even shows at all on the tiles has OSM data. Therefore OSM should be sufficient as the only source. It makes everything that is visible clickable.

>Search is processing data from OSM and stores it locally on the server, what it basically does is save everything that has a name

I see. While I'm not aware of the technical details, I can only suggest that perhaps one can rely directly on the API call that the osm "query-feature" button uses uses rather than using the local database, making this a simpler task. A left click would fetch the proper nodes and their tags from the main osm server.

Regardless, whether this is a priority or not is up to you. I really appreciate the work you guys do.

**Comment by HarelM** [comment] 2017-06-24 11:58
> Regardless, whether this is a priority or not is up to you. I really appreciate the work you guys do.

Thanks for the vote of confidence!
Not everything in OSM is relevant to the user. I know form your posts in the OSM forum that you are editing the map extensively but a lot of the users doesn't have an OSM account and are not really familiar with all the technology involved.
Therefore, and much like other sites, POI need to be shown in a way that a user will know he can interact with it, not by simply clicking the map, IMHO.

As for the data itself. In theory and for open-source agenda I agree all the data should be in OSM or "in the open" (like Wikipedia).
Having said that, there is already a lot of data collected by users and the government and it would be a waste to add it to OSM too, instead we'll try and cooperate with other entities to get this data to the user - I also think there's little data in OSM beside basic stuff (images are missing, detailed description, etc.) which makes the OSM data less appealing.

Also, the OSM API is slow and so the data has to be stored locally, this is not really an issue as it works well now.

**Comment by SwiftFast** [comment] 2017-06-24 12:29
>Therefore, and much like other sites, POI need to be shown in a way that a user will know he can interact with it, not by simply clicking the map, IMHO.

Could you elaborate on that? On just about all maps I know, I interact with objects either by searching or by clicking them. The click shows additional info. As a user (and not a mapper), I consider a map that doesn't respond to clicks crippled in a way.

**Comment by SwiftFast** [comment] 2017-06-24 12:31
Oh, I think I get it. You're implying that there should be a layer of clickable icons on top of the tiles, just like the Wiki layer?

**Comment by HarelM** [comment] 2017-06-24 12:35
Exactly.

**Comment by SwiftFast** [comment] 2017-06-24 12:36
I removed my previous comments because I misunderstood your intentions.

I get it now. You're saying that there should be a layer of clickable icons on top of the tiles, just like the Wiki layer, which is not solely OSM data. (And whatever shows on those layers shouldn't render at all on the tiles, to avoid duplicates.)

**Comment by SwiftFast** [comment] 2017-06-24 12:38
Ok then, that makes sense.

Feel free to close this issue if you think it's irrelevant

**Comment by HarelM** [comment] 2017-06-24 12:47
I'm gonna keep this open in order to finally get to add this necessary feature going, This is probably the number 1 cause for users to go to other site - the fact that there's not enough data to plan routes as data on interesting POIs is very limited.
I hope I'll be able to close it in one of these days...

**Comment by SwiftFast** [comment] 2017-06-24 12:50
>This is probably the number 1 cause for users to go to other site - the fact that there's not enough data to plan routes as data on interesting POIs is very limited.

I completely agree. Number 2 possibly being trip routing.

**Comment by HarelM** [comment] 2017-08-10 22:56
Initial look and feel - advanced mode (non-advance mode is just the ability to toggle the entire layer on or off):
the following image is with the tooltip (currently still without translation)
![image](https://user-images.githubusercontent.com/3269297/29194932-93fb1b78-7e34-11e7-8993-95d539ad0445.png)
The following probably needs some icons (I used the legend texts to convey the message better)
![image](https://user-images.githubusercontent.com/3269297/29194920-86a8b69c-7e34-11e7-85f4-5dddfb3ede68.png)
@valleyofdawn, @zstadler I would appreciate your input here.
I have selected the following categories, I'm not sure if other are needed:
1. Spring (probably everything that is related to water including wells cistern etc.)
2. Campsite
3. Viewpoint
4. Ruins and probably archaeological site
5. Nature reserve?
6. Other? not sure what to put here, maybe tourists attraction?
In any case it should be between 3 and 7, preferably even number to place in two columns. 

I'm planning the following for this feature:
1. Show POIs only from OSM (for this feature).
2. Allow OSM users to edit description (hopefully to be able to facilitate for English and Hebrew - only if it's simple).
3. Grouping etc much like other layers.

This should provide a way to talk about how users would like to see/interact with the POI layer and we can get valuable input from users.

What I'm not planning on implementing as part of this feature:
1. Any thing related to images for POIs - I'm planning on presenting the same image for all POIs something similar to this:
![image](https://user-images.githubusercontent.com/3269297/29195558-ce324aac-7e37-11e7-8795-4a869e5b7678.png)
2. Not planning to update the search for now.
3. No external sources except OSM

**Comment by valleyofdawn** [comment] 2017-08-11 09:21
Could you explain the rationale behind the whole concept?
The POI's are already on the map. Would you like them to be available on top of sat images? 
There is no place for lengthy descriptions under OSM notes. 
Would you like it to be a gateway to serious OSM editors?

**Comment by HarelM** [comment] 2017-08-11 09:44
This is an initial step towards a full blown feature of POIs that we might spin of to a new project (probably will only gather data from OSM but not put all of it back in).
I want to use this step to get some users input on what is required and can help - more of an UX experiment of what a good POI layer is.
I want to use the following tag to allow users to add a description to a POI:
https://wiki.openstreetmap.org/wiki/Key:description
I want to setup the UX of the POI layer main functionality and infrastructure so that when I'll change the underlining POIs provider the UX will remain almost the same but there will be a lot more data.

**Comment by HarelM** [comment] 2017-08-14 20:35
Here's how a single POI will look in edit mode:
![image](https://user-images.githubusercontent.com/3269297/29290372-7f9a32ba-8148-11e7-8937-835915b99ba9.png)
I'm thinking about a text to put below the description areatext, I can make it change in case there is a description and in case there isn't, I'm just not sure what to write there.
Here it is not in edit mode:
![image](https://user-images.githubusercontent.com/3269297/29290418-ae5e9bc2-8148-11e7-8c98-ecbec9e402bb.png)
"Coming soon" image is still missing in both cases, it will be above the link title.

**Comment by HarelM** [comment] 2017-08-14 22:36
@valleyofdawn @zstadler I have created categories for OSM features which can be seen in the following file:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GeoJsonFeatureHelper.cs#L48
The last parameter of each line there is the category I created, it is based on OSM tags (hard to see since it is outside the visible scope - scroll right to see it).
The categories match the above I wrote: other, viewpoint, campsite, spring, ruins.
Can you please go over the list in this file and let me know if I forgot something, or if the categories should be changed?
It would be much appreciated.
In theory, I can also add the bike relations as part of the POIs, much like the nakeb POIs. Let me know if this is something you think is relevant.

**Comment by zstadler** [comment] 2017-08-15 06:49
Can you explain again what is the category for a POI like
[`new PropertiesData("boundary", "protected_area", 1),`](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GeoJsonFeatureHelper.cs#L50)

Wouldn't it be clearer to have the list of categories separated from the list of POIs?
Alternatively, use a list of categories, each containing a list of POI definitions.

**Comment by HarelM** [comment] 2017-08-15 07:06
In the above case the default is none - meaning it won't get picked up as a POI.
This class, as the name suggests, is just a helper class to add properties to OSM elements after converted to GeoJSON. Since the search and POI mechanism are somewhat related I think this is good enough, the mechanism can change to add OSM tags to a dictionary of categories, but it's just a matter of who holds who, which, IMHO, is not so important.
Any other comments though?

**Comment by zstadler** [comment] 2017-08-15 11:35
Correctly tagged nature reserves are [`new PropertiesData("boundary", "protected_area", 1),`](https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/GeoJsonFeatureHelper.cs#L50)

You may want to include them in some category.

**Comment by HarelM** [comment] 2017-08-16 21:48
I didn't want to break any copy right laws so I used SJJB icons and font awesome.
Most of the functionality is working (at least the map area, categories and grouping), here's how the map looks:
![image](https://user-images.githubusercontent.com/3269297/29386470-a1c3d0c4-82e4-11e7-8a24-f745677ad177.png)
I'm still working to improve the performance of large areas but other than that I think I'll be able to finish most of it by the end of the week, the change is both in the client side and server side so I can't create a test site like I usually do. I'll try and open a local server from my machine for you to try it out.
P.S. Elastic search is amazing, lighting fast and super rich!

**Comment by HarelM** [comment] 2017-08-21 20:34
A reference for UX:
http://www.germany.travel/en/map-of-germany.html#!/map/c/t/77001/b/http%3A%2F%2Fwww.germany.travel%2Fen%2Findex.html

**Comment by valleyofdawn** [comment] 2017-08-24 14:34
I've added a link to KKL to "סינגל איילון". Would like to see what is looks like.
[http://www.eyarok.org.il/bike/trip.aspx?id=2005]
[(https://www.openstreetmap.org/relation/4240755)]

**Comment by valleyofdawn** [comment] 2017-08-24 14:50
I can envisage a category and subcategory system:
Water source = Spring/pool/cistern/well
Historic = historic site/ruin/archeological site/museum/memorial
Natural attraction = flora/fauna (=season) /geology/cave
Camping = RTG day camp/RTG night camp/picnic area/payed camp site/good coffee stop
Viewpoint + direction

**Comment by HarelM** [comment] 2017-08-24 21:43
The categories sound good.
I don't want a subcategory system, categories will be for advanced users.
Here's is the split with the relevant OSM tags, let me know if I missed something.
1. Points of interest:
   * Water - natural:spring, natural:waterhole, water:pond, waterway:waterfall, man_made: cistern (? haven't found the last one on [OSM](https://wiki.openstreetmap.org/wiki/Key:man_made))
   * Historic - historic:ruins, archaeological_site, memorial, monument, man_made:water_well (because it's usually empty),
   * Natural - natural:cave_entrance, geological:*, how does one tag flowers?
   * Camping - tourism:camp_site, picnic_site, leisure:picnic_table, picnic
   * Viewpoint - tourism:viewpoint
   * Other - leisure: nature_reserve, boundary: national_park, protected_area, tourism:attraction
   * Wikipedia - I hope I'll be able to do it incorporate it into all this mechanism to include search.
2. Routes:
   * Hiking - route:hiking, nakeb (not OSM, I don't think it needs an extra icon.
   * Bicycle - route:bicycle, mtb
   * 4WD(?) - ?

Are the above OSM tags correct? did I miss some thing (except for those I didn't know what do with)? please review them and let me know.
The above Main categories will be visible for simple users, advanced user will have an expand option to see the categories.

**Comment by HarelM** [comment] 2017-08-26 21:41
Here's an a example of current status:
There are two groups - POIs and Routes, each have its own categories.
The below is the advanced view where categories are reachable and visible.
![image](https://user-images.githubusercontent.com/3269297/29745219-9dfede8a-8abd-11e7-97ba-428f5a8fef40.png)

@valleyofdawn do you have a though about which icon to put as natural? maybe the cave icon?
Better names are welcome.

Regarding images, I was thinking about using [imgur](http://imgur.com/), they have an anonymous API which allows uploading images without being a user. I heard reddit users are fond of it and I think it might be ok for now, I can probably store it on our server but there are better places that do the same, worst case, I'll implement it.
But we can start without images and add them later on.

Nakeb layer is now part of the hiking routes.

Every source of data for the POIs layer is also a source for the search so this is a big benefit.

Still open (by priority):
1. Add POI to OSM - I want to open a dialog when clicking on a editable route point to allow all the required data to be edited and presented to the user so he can upload it to OSM (without all the tagging and complexity of OSM, using some of the data the user already entered).
2. Need to implement rating - Get, Add + No more than once by user only to logged in users..
3. Nakeb layer will not be an extra layer but part of the hiking routes - only need to remove client side implementation.
4. I was thinking of doing the same thing I did to Nakeb with wikipedia and add it as a category under POIs (which will also make it searchable), the API doesn't support it so well, I'll probably need to iterate all over Israel to get all the values with geo location. @zstadler any change you'll contact someone from wikimedia and ask them if we can have an API call that returns all geolocation points in a county or at least more than 10Km?
5. images as described above.

**Comment by HarelM** [comment] 2017-08-27 21:10
Here is the initial dialog for uploading a point when clicking on a route point's upload to cloud icon:
I'm still not sure if this suppose to be part of the marker popup or not, I tent to go with the dialog as it requires more space than I think the marker can hold.
This however will mean that the edit POI will look very similar.
Still missing in this design: link to external site, and upload image.
![image](https://user-images.githubusercontent.com/3269297/29753971-e5590040-8b84-11e7-9cca-f48fd4681f4b.png)

**Comment by MatanBenMoshe** [comment] 2017-08-28 09:25
> Nakeb layer will not be an extra layer but part of the hiking routes - only need to remove client side implementation.
Can you please explain this change? Why are you doing it? What are the other routes that will be there under hiking routes?
Please update me next time when you're planning to make a change related to Nakeb and get my approval for the change. Thanks!

**Comment by HarelM** [comment] 2017-08-28 09:44
Routes from OSM. This change is still new, I thought about it a few days ago, sorry for not informing you...
Do I have you blessing?

**Comment by MatanBenMoshe** [comment] 2017-08-28 09:57
Can you explain what do you mean "Routes from OSM"?
Where can I see it? Why not to give the user the ability to distinguish between the routes source?

**Comment by HarelM** [comment] 2017-08-28 10:03
Some relations in OSM has tags that describe them as hiking routes or biking routes.
Currently the only place these routes can be found is using the search, for example if you search for:
ים אל ים you'll receive the sea-to-sea hiking route.
There is a possibility to separate it by source instead of by type, but I think in terms of UX the separation by source is not something the users really needs...

**Comment by HarelM** [comment] 2017-08-29 21:48
Categories will look like so:
![image](https://user-images.githubusercontent.com/3269297/29844831-5585e456-8d19-11e7-8735-4d97264bb7ec.png)
Almost empty POI will look like so:
![image](https://user-images.githubusercontent.com/3269297/29844891-7c6dd128-8d19-11e7-8b40-577fe154ed92.png)
When Clicking the pencil or the title it will transform to a simple editing mode:
![image](https://user-images.githubusercontent.com/3269297/29845302-f328d5b4-8d1a-11e7-947a-5d5a26a57973.png)
User can edit description and upload image in this dialog, he can also click the "More..." in order to open advanced editing - this is the same editing dialog that will appear when clicking on the upload to cloud icon on a route marker (when planning a route).
![image](https://user-images.githubusercontent.com/3269297/29845380-42929b58-8d1b-11e7-9d66-7ecd382d2312.png)
Once clicking the upload the dialog will close and data will be saved.
Clicking on vote-up/down will change the rating of a point and will make the buttons grey:
![image](https://user-images.githubusercontent.com/3269297/29845552-f0eec348-8d1b-11e7-8e20-e85e6e6883ff.png)

Thoughts and comments are welcome.

**Comment by zstadler** [comment] 2017-08-30 04:04
Please add 4WD trails. 

What about 2WD trails?

**Comment by valleyofdawn** [comment] 2017-08-31 07:41
Looking good.

"לחצו על כפתור העריכה למטה" . No button below, only text above.
The rating buttons would be more prominent if they are green and red
What does the camera icon signify?
מעניין should be מעיין
זה הזמן להחזיר חזרה should be זה הזמן להחזיר לקהילה

**Comment by valleyofdawn** [comment] 2017-08-31 07:43
The link should go directly to the website tag  in OSM, if one exists.
e.g. here:
https://www.openstreetmap.org/relation/4240755

**Comment by HarelM** [comment] 2017-08-31 07:53
Thanks for the feed back, it's greatly appreciated!
>"לחצו על כפתור העריכה למטה" . No button below, only text above.
The rating buttons would be more prominent if they are green and red

You are not logged in as OSM user probably, but you are right, it should say - log-in to OSM in that case.

>What does the camera icon signify?

That there's no image and you should upload one, better text or tooltip should be added probably.

>מעניין should be מעיין
זה הזמן להחזיר חזרה should be זה הזמן להחזיר לקהילה

Sure, I'll update the translation.

> The link should go directly to the website tag in OSM, if one exists.
e.g. here:
https://www.openstreetmap.org/relation/4240755

This should work, but I think I'm using more than a week old file on my PC, so this is probably the root cause, I'll download a new file tonight.

**Comment by valleyofdawn** [comment] 2017-08-31 07:58
Will we be storing the images locally?
Wouldn't uploading them to Mapillary make more sense?
When you are not logged in, the edit button is not there, but clicking the text above would still get you into (flase? edit mode)

**Comment by valleyofdawn** [comment] 2017-08-31 08:03
If we plan to remove the wiki layer from the POIs (and I think we should not). Then they should be accessible through the top POI window based on the Wikipedia tag in OSM. In that case we should try to auto-link wiki entries to OSM nodes, and include places in the POI layer as well. Most of the wiki entries are settlements.

**Comment by HarelM** [comment] 2017-08-31 08:04
No, Images are stored at [imgur](http://www.imgur.com), I don't see a good reason right now to store them locally, if you have another site to upload images anonymously let me know, I'll take a look at Mapillary, my main concern about imgur is the allowed capacity they offer for free which might not be enough.

>When you are not logged in, the edit button is not there, but clicking the text above would still get you into (flase? edit mode)

This is a bug...

**Comment by valleyofdawn** [comment] 2017-08-31 08:06
Maybe include a Show all/show none button for POI categories?

**Comment by HarelM** [comment] 2017-08-31 08:07
Since Wikipedia layer is a lot of work and further thoughts are needed, I don't think it should be part of this release, I'll split it into a separate issue, let's assume for this release that it will stay as it is now.

**Comment by HarelM** [comment] 2017-08-31 08:08
>Maybe include a Show all/show none button for POI categories?

I'll see what I can do, I agree this is a bit unfriendly.

**Comment by valleyofdawn** [comment] 2017-08-31 08:11
> It will stay as it is now.

As it is now in the beta or the main site?

**Comment by HarelM** [comment] 2017-08-31 08:14
I haven't changed the wiki layer, now = beta, and beta = production site.

**Comment by HarelM** [comment] 2017-08-31 17:05
Summary: All the above issue have been fixed, I think.
Still open:
 * Refresh after extended dialog is opened.
 * The state of the categories is not saved between sessions.
 * Search should be improved to look somewhat similar to POIs results.
 * What to do with description that does not match the user language?

**Comment by valleyofdawn** [comment] 2017-09-03 08:11
1) Uploading an image works fine (e.g. עין עוזי). However, clicking on the image must enlarge it. This feature is pretty useless with only thumbnail-size images.
2) OSM upload works well.
3) Maybe we should have an advanced edit button to take the user to the OSM editor, as a way of drawing people to be power OSM editors. Would be convenient for us too.
4) linking to website works nicely (סינגל איילון).
5) Graphic design could be improved:
a. The aggregate icons in low zoom have 5 elements: star, number, shape, thick transparent outline and color. They can have just 3 for simplification. 
b: The POI icons are rectangular. This is justrified when there is text, but when there is just an icon it wastes space and adds clutter (round shapes are easier on the eye. Let's rever to the classical drop.
c: Many of the OSM icons are badly designed - see for instance the archaeological site, At this resolution there is no way to know those are collapsed columns. 
d: The POI icons and aggregate icons speak a different design language and clash. They should both be either transparent or cast a shadow. Showing the two options in attached image.
![presentation1](https://user-images.githubusercontent.com/689201/30001487-8f572ea6-9098-11e7-843d-1383d139a871.jpg)

**Comment by HarelM** [comment] 2017-09-03 11:11
Thanks for the input!
>Maybe we should have an advanced edit button to take the user to the OSM editor, as a way of drawing people to be power OSM editors. Would be convenient for us too.

This button already exists - left pane - edit in OSM, I don't think there's a need for another button - OSM users will know how to continue working on the relevant element after the redirection.

> The aggregate icons in low zoom have 5 elements: star, number, shape, thick transparent outline and color. They can have just 3 for simplification. A colored, numbered, frameless star.
Expenation: 
 * Star (might not be needed if Wikipedia is also part of the points of interest layer) is needed to separate between different types - I agree it might not be needed any more.
 * I think Number and Color are good indications - we agree on that.
 * I found the round shape and outline to be fairly simple and easy on the eyes, the above start, IMO, looks bad.
>The POI icons are rectangular. This is justrified when there is text, but when there is just an icon it wastes space and adds clutter (round shapes are easier on the eye. Let's rever to the classical drop.

I started with the drop icon and it yielded even worse results than current design - some of the icons "touched" the outline of the drop, again, this can be fixed with better css design code but currently I'm not planning on changing it, same reason as below.
> Many of the OSM icons are badly designed - see for instance the archaeological site, At this resolution there is no way to know those are collapsed columns.

Can't argue about it, I have taken the SJJB icons and didn't want to waist a lot of time on designing icons - my skills are better used coding - but I think we should improve it project-wise, see issue https://github.com/IsraelHikingMap/Map/issues/160

>The POI icons and aggregate icons speak a different design language and clash. They should both be either transparent or cast a shadow. Showing the two options in attached image.

You're probably right, but I don't think I know how to fix it, I think we need a designer, but one that knows how to write some CSS, otherwise it won't help much as it's painfully slow for me to change the design and to achieve what's needed (Not sure I'm the only one, BTW - see the following image :-)).

![](https://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif)

**Comment by valleyofdawn** [comment] 2017-09-03 11:47
Hmm, not much traction. Please ask around about what POIs look better.
What about the thumbnails, will they be clickable?
Can I help by supplying SVGs complete with drop+icon?

**Comment by HarelM** [comment] 2017-09-03 13:48
I don't see much use to enlarging the image, I don't think you'll benefit from it much - what is the use case for this?
I don't think it's hard to implement, but might not be beneficial...
I don't think you can help with the SVG drop+Icon as I use a font to create all the icons and then place them one on top of the other to make it flexible for size and color.
every icon is considered a "letter" in the font and every "letter" has a single color - so Icon+Drop needs two colors which can't work with the current mechanism.
You can especially see it when editing a route and placing different icons on top of the marker with changing colors.
Might not be the case for POIs but I think this mechanism is very simple and flexible to achieve what I need, I would hate to loose it in favor of static images...

**Comment by valleyofdawn** [comment] 2017-09-03 14:04
I know that in other sites with images I always enlarge the images. Mostly to see the place and assess if it's worth visiting. 
Regarding the drops, how come it works well with the private POI feature?

**Comment by HarelM** [comment] 2017-09-03 14:10
I'll add it to my list then.
It doesn't work well, IMO, but I wanted to split the UX between private and public POI - to let the user know this is not his POI.:
Here's an example of what I said about - the inner icon almost touches the edges...
![image](https://user-images.githubusercontent.com/3269297/30003713-7c0bbf24-90ca-11e7-8798-f8046ee4a775.png)
![image](https://user-images.githubusercontent.com/3269297/30003716-8529a86e-90ca-11e7-8f36-20fc82536e92.png)
![image](https://user-images.githubusercontent.com/3269297/30003719-8e292142-90ca-11e7-9901-871e4b5edc2d.png)

**Comment by valleyofdawn** [comment] 2017-09-03 14:35
And there is no way to decrease the font size or increase the shape size?

**Comment by HarelM** [comment] 2017-09-03 14:53
There is, using CSS, see the relevant image above.
I tried to play with it for a few minutes and gave up when it wasn't doing what I wanted...
You can try it yourself if you want, when opening the browser and pressing F12 you can edit the CSS of the site for your local session, but I don't recommend it...

**Comment by HarelM** [comment] 2017-09-04 22:50
New look for advance editing of points - less options is probably better, especially for the water, but I wasn't sure how to present it to the user (for example monument and memorial are very confusing in this case).
![image](https://user-images.githubusercontent.com/3269297/30039356-4916d39c-91d8-11e7-99b2-3fcd590d3ce8.png)
I think this was the last open issue.

**Comment by HarelM** [comment] 2017-09-08 22:17
This is basically implemented now. Closing this in favor of leftover issues opened separately.

**Closed by HarelM** 2017-09-08 22:17 UTC
Labels: Critical, enhancement
