### ISSUE TITLE
Android App failed to initialize with Maximum IPC message size exceeded error 

### ISSUE THREAD

**Issue by EdoGeron** [IsraelHikingMap/Site#1130] opened 2020-01-22 14:12 UTC
## Bug
Android App issue ( but i couldn't find the appropriate repo - please relocate if needed )

## What I expect to happen
App loads succesfully 

## What really happened
App Crashed

## What I did that caused the issue - step by step
Tried top open the App 

## My environment
* Operating System and version:
* Web Browser and version:
Xiomi Mi 8 pro  

## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/52445845/72901153-e30a0d00-3d31-11ea-9305-dffe332a9cec.png)

**Comment by HarelM** [comment] 2020-01-22 14:41
Thanks for reporting, this is a duplicate of #1117.
If you can find an easy way to reproduce it, it can help a lot.
Let's continue the discussion on the other thread.

**Closed by HarelM** 2020-01-22 14:41 UTC
