### ISSUE TITLE
[iOS] App freezes during offline map download

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1206] opened 2020-04-04 21:43 UTC
## What I expect to happen
Successful download of offline map

## What really happened
App freezes while downloading offline map - white screen and no response

## What I did that caused the issue - step by step
 
- האפליקציה הרגילה הוסרה
- הותקנה אפליקציה מתוך TestFlight
- האפליקציה הופעלה מתוך TestFlight 
- התבצעה קניה של מפות אופליין (ללא חיוב)
- החלה הורדה של מפות האופליין
- מיד עם הגעת התהליך ל 12.5%, המסך הפך לבן והאפליקציה הפסיקה להגיב

## My environment
manufacture: Apple
model: iPad4,1
platform: iOS
OS version: 12.4.6

## Things I think the developers should know, images, links etc.

Log files were sent by mail
Subject: Issue reported by zstadler מסך לבן תוך הורדה של האופליין 
Date: Apr 4, 2020, 10:09 PM

There are no visible issues at the relevant time:
```
2020-04-04 21:53:10 | DEBUG | [Store] owned: offline_map  <- Last log line before the crash
2020-04-04 21:55:42 |  INFO | Starting IHM Application Initialization <- First log line after the restart 
```
בהנתן שהתקלה ארעה לאחר שמינית מתהליך ההורדה, אני משער שהבעיה החלה בשלב שבו החלק הראשון מ 4 החלקים של מפת האופליין סיים לרדת למכשיר והאפליקציה החלה בפתיחתו והתקנתו.

למכשיר יש יותר מ 3 ג’יגה בייט של מקום פנוי

**Comment by HarelM** [comment] 2020-04-05 05:00
I'm not experiencing this issue on my iPad.
Since test flight only supports crash reports from iOS 13 I advise to update to the latest OS and run this scenario again.
Let me know if something had changed, I know there are issues with indexDb and iOS 12.x so regardless I would advise to update the OS...

**Comment by zstadler** [comment] 2020-04-05 06:42
The OS is updated to the latest on this iPad. iOS 13.x is probably not available for this device.
Given the download time of the first offline item, it seems it is one of the tile files. AFAIK, the tiles are no longer stored in the indexDB.
I hope additional logging can help to clarify the problem.

**Comment by HarelM** [comment] 2020-04-05 06:52
IndexDB is used in the app in general, we can't ignore the fact the iOS 12.x has issues with it.
The following log line is what I would expect to see in the logs and it is missing:
https://github.com/IsraelHikingMap/Site/blob/a2629e7aebe96c7ffc4e27be1d6e4c72db1836cb/IsraelHiking.Web/sources/application/services/database.service.ts#L125
Coming from this line of code:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/dialogs/download-progress-dialog.component.ts#L67
Since this log line is missing I would suspect loading the file to memory crashed the app.
If this is the case I'd need a crash report which as far as I understand can only be sent from iOS 13 devices.
I'm not sure this device is a good candidate to test our app for those reasons...

**Comment by zstadler** [comment] 2020-04-05 08:56
> IndexDB is used in the app in general, we can't ignore the fact the iOS 12.x has issues with it.

Given this, I suggest the app would not be supported on iOS12.x and below on the app store.

**Comment by HarelM** [comment] 2020-04-05 09:05
I have no clue how to do it.
Feel free to investigate.

**Comment by zstadler** [comment] 2020-04-05 09:11
https://cordova.apache.org/docs/en/latest/config_ref/ says
`<preference name="deployment-target" value="13.0" />`

**Comment by HarelM** [comment] 2020-07-09 05:36
Seems like this happens not only on 12.x devices. reopening.
Some info can be found here which might help:
https://github.com/apache/cordova-plugin-file/issues/364

**Comment by HarelM** [comment] 2020-07-09 19:06
I have migrated to file-transfer-plugin for the mbtiles files and tested it on both platform with success (my iPad worked before before this change I just made sure it now work too, I'll see if I can find a way to reproduce/test it with one of the customers who reported this issue).
I'm not sure it will solve this issue but I do hope so as the failure seems to be in the Cordova code that translate the blob to base 64 and the blob is probably too big so the process crashes (the location in the code is just after the file finishes downloading and before or while storing it to the file system). file-transfer-plugin does this whole process in native code which should provide a work-around for this, again, I hope...

**Comment by HarelM** [comment] 2020-07-10 07:24
Seems like there's also a problem with the POIs json parse.
I'll be using this issue to deal with both problems.
I have uploaded to the server a secondary file called `offline-pois-chunked` to facilitate the testing and updated the code in this issue's branch.

**Comment by HarelM** [comment] 2020-07-10 20:01
Seems like migrating to `file-tranfer-plugin` had improved the situation. chuck database updates for indexdb also seems to help a bit but not fully solve all aspects of the POIs problem.
I'll be closing this issue, publish the version and monitor the situation. If need be I'll reopen this issue.

**Closed by HarelM** 2020-07-10 20:01 UTC
Labels: App, Critical, bug
