### ISSUE TITLE
POI update efficiency

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1454] opened 2021-03-07 09:05 UTC
## What I expect to happen
Minimize empty POI updare responses by the server

## What really happened
From time to time, the server log has sequences of POI update responses with no features, starting on 1.1.1970 and progressing 3 days at a time. For example:

```
2021-03-07 09:32:29.2610 |179 |INFO | Finished getting POIs updates for 01/01/1970 02:00:00 - 04/01/1970 02:00:00. Features: 0, Images: 0 
2021-03-07 09:32:29.4978 |179 |INFO | Finished getting POIs updates for 04/01/1970 02:00:00 - 07/01/1970 02:00:00. Features: 0, Images: 0 
2021-03-07 09:32:30.0963 | 11 |INFO | Finished getting POIs updates for 07/01/1970 02:00:00 - 10/01/1970 02:00:00. Features: 0, Images: 0 
2021-03-07 09:32:30.3088 |  4 |INFO | Finished getting POIs updates for 10/01/1970 02:00:00 - 13/01/1970 02:00:00. Features: 0, Images: 0 
```

It would take more than 18000 requests to complete the POI update.

**Comment by HarelM** [comment] 2021-03-07 11:09
Duplicate of #1441

**Closed by HarelM** 2021-03-07 11:09 UTC
