### ISSUE TITLE
Error uploading a POI to OSM

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#659] opened 2018-03-11 06:56 UTC
## What I expect to happen
Be able to upload a POI created using coordinates.

## What really happened
![image](https://user-images.githubusercontent.com/1304610/37250591-1584496e-2509-11e8-8da1-23e11d1ddf2a.png)

## What I did that caused the issue - step by step
1. Search for location by coordinates. For example [170000/500000](https://israelhiking.osm.org.il/#!/?q=170000/500000)
2. Click on the "+" button
3. Click on the new POI
4. Click on the "Upload Point" button
5. Click on the "Update Point" button

## My environment
* Operating System and version: any
* Web Browser and version: any

## Thing I think the developers should know, images, links etc.
```
2018-03-11 08:41:30.2768 |259 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HLC6A3VCUNS3": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at IsraelHiking.API.Converters.OsmGeoJsonConverter.ToGeoJson(ICompleteOsmGeo completeOsmGeo) in C:\projects\site\IsraelHiking.API\Converters\OsmGeoJsonConverter.cs:line 23
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IsraelHiking.API.Executors.OsmGeoJsonPreprocessorExecutor.Preprocess(Dictionary`2 osmNamesDictionary) in C:\projects\site\IsraelHiking.API\Executors\OsmGeoJsonPreprocessorExecutor.cs:line 57
   at IsraelHiking.API.Services.Poi.OsmPointsOfInterestAdapter.<ConvertOsmToFeature>d__16.MoveNext() in C:\projects\site\IsraelHiking.API\Services\Poi\OsmPointsOfInterestAdapter.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IsraelHiking.API.Services.Poi.OsmPointsOfInterestAdapter.<UpdatePointOfInterest>d__12.MoveNext() in C:\projects\site\IsraelHiking.API\Services\Poi\OsmPointsOfInterestAdapter.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IsraelHiking.API.Controllers.PointsOfInterestController.<UploadPointOfInterest>d__9.MoveNext() in C:\projects\site\IsraelHiking.API\Controllers\PointsOfInterestController.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by HarelM** [comment] 2018-03-11 13:56
I'll take a look at this after resolving #614 or take this into account when implementing #614 since I'm revising the entire POI UI.

**Comment by HarelM** [comment] 2018-03-30 21:16
@zstadler can you please check if the scenario above is still valid?
I can't reproduce using the latest code locally.
I also think the scenario is no longer possible as you have to set either title, image or description in order for the update button to be enabled.
Please close this issue if this is no longer relevant. if this is still relevant, please update steps to reproduce  or write new ones.

**Comment by zstadler** [comment] 2018-04-04 08:54
The scenario is working fine and the server log does not have an error.

>I also think the scenario is no longer possible as you have to set either title, image or description in order for the update button to be enabled.

I believe this is because of a recent change where results of the coordinate search do not have a name any more. I think they should continue to have a name - the search text as the user typed it.

**Comment by HarelM** [comment] 2018-04-04 10:38
> I believe this is because of a recent change where results of the coordinate search do not have a name any more. I think they should continue to have a name - the search text as the user typed it.

I see. I changed how the search results works locally as part of #660 and search results will return poi data instead of geojson which should simplify things and fix that as well.
I hope to upload a new version in the next few days.
I'll keep this issue open to make sure I don't forget to fix it.

**Comment by zstadler** [comment] 2018-04-09 05:31
In the above example, "170000/500000" turns into "170000 500000". Strangely enough, when using a different separator, such as "170000, 500000", the user-typed text is not modified.

I agree that the coordinates are not a great title, but having no title, or an automatically-generated title is worse.

**Comment by HarelM** [comment] 2018-04-09 05:33
"/" is a problematic character when it comes to urls. This is not a new behavior BTW and I think we discussed it when implementing coordinate search...

**Comment by HarelM** [comment] 2018-04-09 06:00
See https://github.com/IsraelHikingMap/Site/issues/499#issuecomment-334595371
Please close this issue.

**Closed** 2018-04-09 07:33 UTC
Labels: Low, bug
