### ISSUE TITLE
Present GPXs from external sites on the map

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#51] opened 2015-08-12 07:19 UTC
Like they do in [Amud Anan] (http://amudanan.co.il/?url=http://groopy.co.il/files/maslul/1725gps.gpx)

**Comment by HarelM** [comment] 2015-08-21 11:26
The url is {IHM}/#/?url={address}.
This will work only with site that supports cross origin resource sharing (CORS).

**Comment by zstadler** [comment] 2015-08-21 12:33
Was it published on the pre-production site?

I've tried
http://osm.org.il/IsraelHiking/PreProduction/#/url=http://waymarkedtrails.org/en/routebrowser/282071/gpx
with no success

**Comment by HarelM** [comment] 2015-08-21 13:17
Just now, please close it if it works. If you open F12 in the browser and set a url and it doesn't work you should see a message about CORS in the console area.

**Comment by zstadler** [comment] 2015-08-22 06:02
I'm not familiar with CORS, but it seems that 
http://osm.org.il/IsraelHiking/PreProduction/#/?url=http://groopy.co.il/files/maslul/1725gps.gpx
gets an error:

18:23:37.827 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://groopy.co.il/files/maslul/1725gps.gpx. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

while AmudAnan is perfectly OK opening the same GPX URL.

It there anything I should do with the browser's settings?

**Comment by HarelM** [comment] 2015-08-22 08:41
CORS stands for cross origin resource sharing. This can be addressed if you use a server to fetch the file instead of asking the browser to do it. Since I'm not planning on writing a server side right now this is a limitation... There's nothing you can do about it as far as I know with the browser settings...

**Comment by HarelM** [comment] 2015-08-22 09:44
Do you want to keep this issue open until we have a proper server side?
BTW, you can ask groopy to support CORS. I know this won't fix the general problem.

**Closed** 2015-08-22 18:45 UTC
Labels: enhancement
