### ISSUE TITLE
When recording a track, the height profile was truncated

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1036] opened 2019-05-19 09:47 UTC
## What I expect to happen
When recording a track I expect the height profile to represent all the elevation changes up to my current position

## What really happened
It showed just the first portion of the height profile, although X,Y position recording continued.
## What I did that caused the issue - step by step
Started recording a track, switching the screen on and off.
At 6 Km opened the height track to watch it.
Noticed that only the 1st kilometer appears (see image)

## My environment
IHM app version 8.0.309 on android

## Thing I think the developers should know, images, links etc.
1)	This happened before on a separate trip.
2)	I shared this track, and when opened on the website the entire height profile is shown, with a dip to 0m at the position the bug occurred.
3)	At the same position (0.81 KM) an elevation value is missing from the GPX file (line #1084). File attached.

![image](https://user-images.githubusercontent.com/689201/57980274-dfe7b000-7a31-11e9-94b9-e0787f81e4b3.png)
[מסלול 2019-05-17.gpx.txt](https://github.com/IsraelHikingMap/Site/files/3194940/2019-05-17.gpx.txt)

**Comment by HarelM** [comment] 2019-05-19 09:59
Do you have the log file generated by the debug-app I sent? Can you please attach it here?

**Comment by valleyofdawn** [comment] 2019-05-19 14:18
It wasn't installed yet then. Will get you one for the next time.

**Comment by HarelM** [comment] 2019-05-19 14:41
Have you tried anything to make it work? close and open the graph? switch to statistics? I'm guessing there's probably a division by zero or something...

**Comment by valleyofdawn** [comment] 2019-05-19 14:50
Closing and opening the graph and switch to statistics didn't work.

**Comment by HarelM** [comment] 2019-05-22 16:37
@valleyofdawn I have commited an attempt to fix this issue but when I tried reproducing it on my desktop - i.e take the file I was able to see the entire height chart with the 0 drops.
But it might be that the browser substitutes `null` with `0` and the statistics are available.
In any case, Please see if you can install the latest app an reproduce this issue.
If you can, I'll send you a debug version for further analysis.
Since this is not the first time it happens I get the feeling you'll be able to reproduce it easily? If this is not the case, I'll create a debug version with the latest code so that we'll have logs for when it happens.

**Comment by valleyofdawn** [comment] 2019-05-22 17:40
I'll first see if I can reproduce the problem by turning off the GPS in the current version and then try the new version. I think the drops to zero should also be eliminated by ignoring reads without elevation or through intrapulation.

**Comment by HarelM** [comment] 2019-06-02 18:08
@valleyofdawn Are you able to reproduce this issue with latest debug version?

**Comment by valleyofdawn** [comment] 2019-06-02 18:09
So far no. Will test again tomorrow morning.

**Comment by HarelM** [comment] 2019-07-01 17:45
@valleyofdawn any updates on this? Can I close it and in case it returns you
ll reopen?

**Closed** 2019-07-08 06:44 UTC
Labels: App, Medium, bug
