### ISSUE TITLE
Avoid merge warnings in daily update

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1713] opened 2022-04-23 14:38 UTC
## Bug/Feature
The daily update log includes warning such as

```
warn: IsraelHiking.API.Executors.FeaturesMergeExecutor[0]
      There was a problem merging the following feature into a multipolygon גינת נח, https://www.openstreetmap.org/way/828205672 Nested shells (34.8595278, 32.1688372)
```

The location in the above warning is the location of the first and last node of a closed OSM way - node 7731851797
```
  <way id="828205672" version="3" timestamp="2020-07-22T20:10:21Z" changeset="88367269" uid="1298075" user="Sokuya">
    <bounds minlat="32.1685606" minlon="34.8593946" maxlat="32.1688372" maxlon="34.8596871"/>
    <nd ref="7731851797" lat="32.1688372" lon="34.8595278"/>
    <nd ref="7731851798" lat="32.1687616" lon="34.8596871"/>
    <nd ref="7731851799" lat="32.1685606" lon="34.8595540"/>
    <nd ref="7731851800" lat="32.1686362" lon="34.8593946"/>
    <nd ref="7731851797" lat="32.1688372" lon="34.8595278"/>
    <tag k="leisure" v="playground"/>
    <tag k="name" v="גינת נח"/>
    <tag k="name:he" v="גינת נח"/>
    <tag k="playground:theme" v="playground"/>
  </way>
```

## What I expect to happen
This is a simple legal OSM closed way and it should be imported as a POI without any warnings.

## What really happened
There are 68 similar warnings in the daily log file.

**Comment by HarelM** [comment] 2022-04-24 08:11
There are two polygons one inside the other with the same name that the merge algorithm tries to merge in order to avoid duplicate answers in the search results.
https://www.openstreetmap.org/way/961999449
https://www.openstreetmap.org/way/828205672
I'm not sure if this is bad mapping or bad algorithm behavior in this particular case.

**Comment by zstadler** [comment] 2022-04-25 11:56
Strangely, this is the mapping recommended by the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:leisure=playground?uselang=en):

> Use [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=[park](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dpark) for the overall "Playground" and [leisure](https://wiki.openstreetmap.org/wiki/Key:leisure)=playground for the play area specifically.

I guess the [algorithm assumes the merged multi-/polygons are non-overlapping](https://github.com/IsraelHikingMap/Site/blob/f8fd1a88487132f6b211400599d28eccdafd2531/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L309), which is not the case here. I suggest considering a [Union operation](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Operation.Union.html) instead.

**Comment by HarelM** [comment] 2022-04-25 12:59
Union would be problematic for other cases I guess.
Should the name tag be on both? this is what's mostly strange to me.
I can probably add a specific handling for this case as I don't think I can "generalize" this...
IDK, any chance you can check how many are mapped this way as I do want to improve the build log so that there won't be any error in case there are no mapping issues.

**Comment by zstadler** [comment] 2022-04-25 13:56
In which cases Union would be problematic?
As far as I understand, if the merged multi-polygons are non-overlapping, Union would be the same as CreateMultiPolygon. If there is any sort of overlap, CreateMultiPolygon would fail.

**Comment by HarelM** [comment] 2022-04-25 14:10
I honestly don't know what will happen in the following line in all cases if we replace CreateMultiPolygon with Union:
https://github.com/IsraelHikingMap/Site/blob/97bd4c535f30462391bd9e063460f0d64357ad38/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L309
My main concern is with forests that has complicated multiplygon geometries and those will be merged with I don't know what and create weird geometries...
But it's worth a try and create some unit tests to make sure every case we can think of is covered.

**Comment by HarelM** [comment] 2022-04-27 06:45
After applying an attempt to fix the polygon inside polygon I'm getting the following warnings (Which I guess need different handling):

```
There was a problem merging 17 polygons from the following feature into a multipolygon El Nada Tower (OSM_node_503996785), https://www.openstreetmap.org/node/503996785 Self-intersection (34.5198268, 31.5480373)
There was a problem merging 2 polygons from the following feature into a multipolygon Nuseirat junior high school males (c) (OSM_node_505017030), https://www.openstreetmap.org/node/505017030 Self-intersection (34.3921073, 31.4606349)
The following merge created a weird geometry: אוניברסיטת חיפה https://he.wikipedia.org/wiki/%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA%20%D7%97%D7%99%D7%A4%D7%94 Point, Polygon, LineString, Polygon
The following merge created a weird geometry: הקניון הלבן https://www.openstreetmap.org/node/6413905085 Point, LineString, Polygon
The following merge created a weird geometry: נחל מערות https://he.wikipedia.org/wiki/%D7%A0%D7%97%D7%9C%20%D7%9E%D7%A2%D7%A8%D7%95%D7%AA LineString, LineString, LineString, LineString, LineString, Polygon
The following merge created a weird geometry: ואדי א-סלקא https://www.openstreetmap.org/way/759979226 LineString, LineString, LineString, Polygon
The following merge created a weird geometry: שמורת טבע נחל דלתון https://inature.info/wiki/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA%20%D7%A0%D7%97%D7%9C%20%D7%93%D7%9C%D7%AA%D7%95%D7%9F LineString, LineString, Polygon
The following merge created a weird geometry: הר הרצל https://www.openstreetmap.org/relation/2730115 LineString, LineString, Polygon
The following merge created a weird geometry: אזור מסחרי כורזין https://www.openstreetmap.org/relation/11568850 LineString, LineString, LineString, LineString, LineString, Polygon
The following merge created a weird geometry: קריית מטלון https://www.openstreetmap.org/way/891059858 LineString, MultiPolygon
The following merge created a weird geometry: שכונה דרום https://www.openstreetmap.org/way/893988575 LineString, MultiPolygon
The following merge created a weird geometry: רמת ורבר https://www.openstreetmap.org/way/209751641 LineString, MultiPolygon
The following merge created a weird geometry: מרכז העיר https://www.openstreetmap.org/way/253573831 LineString, MultiPolygon
There was a problem merging 14 polygons from the following feature into a multipolygon מפעל פולירון (OSM_way_690002387), https://www.openstreetmap.org/way/690002387 Self-intersection (34.5212114, 31.6067681)
There was a problem merging 3 polygons from the following feature into a multipolygon מעבר טאבה (OSM_way_765377076), https://www.openstreetmap.org/way/765377076 Self-intersection (34.9028496, 29.4908886)
There was a problem merging 2 polygons from the following feature into a multipolygon בריכה אקולוגית (OSM_way_98859880), https://www.openstreetmap.org/way/98859880 Self-intersection (34.8086555, 32.0960478)
There was a problem merging 3 polygons from the following feature into a multipolygon תעשייה (OSM_way_550643600), https://www.openstreetmap.org/way/550643600 Self-intersection (35.1052785, 31.8176514)
There was a problem merging 2 polygons from the following feature into a multipolygon גן ילדים (OSM_way_229712334), https://www.openstreetmap.org/way/229712334 Self-intersection (35.0950771, 32.8481455)
There was a problem merging 4 polygons from the following feature into a multipolygon בית ספר נוף ים (OSM_way_699543795), https://www.openstreetmap.org/way/699543795 Self-intersection (34.8129946, 32.1859395)
There was a problem merging 4 polygons from the following feature into a multipolygon מצפה הימים (OSM_way_1033448815), https://he.wikipedia.org/wiki/%D7%9E%D7%A6%D7%A4%D7%94%20%D7%94%D7%99%D7%9E%D7%99%D7%9D Self-intersection (35.5328644, 32.9583274)
There was a problem merging 2 polygons from the following feature into a multipolygon El Zeitun School (OSM_way_297323423), https://www.openstreetmap.org/way/297323423 Self-intersection (34.4574539, 31.4999457)
There was a problem merging 2 polygons from the following feature into a multipolygon 7 (OSM_way_442064737), https://www.openstreetmap.org/way/442064737 Self-intersection (35.2248364, 31.7795512)
There was a problem merging 3 polygons from the following feature into a multipolygon מגדלי אביב (OSM_way_364532455), https://www.openstreetmap.org/way/364532455 Self-intersection (34.7803925, 32.0629972)
There was a problem merging 2 polygons from the following feature into a multipolygon החרושת 2 (OSM_way_746318369), https://www.openstreetmap.org/way/746318369 Self-intersection (34.8908273, 32.1106453)
There was a problem merging 2 polygons from the following feature into a multipolygon מרכז פוזין (OSM_way_115952805), https://www.openstreetmap.org/way/115952805 Self-intersection (34.8738342, 32.181112)
There was a problem merging 4 polygons from the following feature into a multipolygon Nuseirat junior high school males (c) (OSM_way_71147015), https://www.openstreetmap.org/way/71147015 Self-intersection (34.3887683, 31.4599456)
There was a problem merging 2 polygons from the following feature into a multipolygon Abasan primary male school (OSM_way_41317795), https://www.openstreetmap.org/way/41317795 Self-intersection (34.3658111, 31.3028591)
There was a problem merging 2 polygons from the following feature into a multipolygon מגרש כדורגל עירוני (OSM_way_68735802), https://www.openstreetmap.org/way/68735802 Self-intersection (34.9636382, 32.4809318)
There was a problem merging 2 polygons from the following feature into a multipolygon مدرسة آمنة بنت وهب (OSM_way_41314981), https://www.openstreetmap.org/way/41314981 Self-intersection (34.2534417, 31.2822169)
There was a problem merging 2 polygons from the following feature into a multipolygon קניון ערים (OSM_way_129490168), https://www.openstreetmap.org/way/129490168 Self-intersection (34.9038889, 32.1779439)
There was a problem merging 2 polygons from the following feature into a multipolygon Deir Al Balah School for Boys (OSM_way_303385344), https://www.openstreetmap.org/way/303385344 Self-intersection (34.3374269, 31.424315)
There was a problem merging 2 polygons from the following feature into a multipolygon Rafah C Prep Male School (OSM_way_41314765), https://www.openstreetmap.org/way/41314765 Self-intersection (34.2570885, 31.2883686)
There was a problem merging 11 polygons from the following feature into a multipolygon שמורת טבע הר סאסא (OSM_way_1049147858), https://inature.info/wiki/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA_%D7%94%D7%A8_%D7%A1%D7%90%D7%A1%D7%90 Self-intersection (35.3909805, 33.0170717)
There was a problem merging 2 polygons from the following feature into a multipolygon הבאסה (OSM_way_970220153), https://www.openstreetmap.org/way/970220153 Self-intersection (34.8223532, 32.1716129)
There was a problem merging 2 polygons from the following feature into a multipolygon מחנה ג'אלמה (OSM_way_264306641), https://www.openstreetmap.org/way/264306641 Self-intersection (35.3094912, 32.5116599)
There was a problem merging 2 polygons from the following feature into a multipolygon בית עלמין עפולה (OSM_way_125130816), https://www.openstreetmap.org/way/125130816 Self-intersection (35.281715, 32.598659)
There was a problem merging 2 polygons from the following feature into a multipolygon وادي ابو خميسة (OSM_way_501589470), https://www.openstreetmap.org/way/501589470 Self-intersection (35.0601372, 32.0102298)
There was a problem merging 2 polygons from the following feature into a multipolygon אזור המנהרות (OSM_way_41319101), https://www.openstreetmap.org/way/41319101 Self-intersection (34.2473591, 31.276305)
There was a problem merging 2 polygons from the following feature into a multipolygon واد بربارة (OSM_way_495215734), https://www.openstreetmap.org/way/495215734 Self-intersection (35.0620767, 32.0205441)
There was a problem merging 2 polygons from the following feature into a multipolygon מרכז עינב (OSM_way_553274070), https://www.openstreetmap.org/way/553274070 Self-intersection (34.9603279, 31.8881171)
There was a problem merging 3 polygons from the following feature into a multipolygon שמורת טבע הר תבור (OSM_way_391514976), https://inature.info/wiki/%D7%92%D7%9F%20%D7%9C%D7%90%D7%95%D7%9E%D7%99%20%D7%94%D7%A8%20%D7%AA%D7%91%D7%95%D7%A8 Self-intersection (35.3834243, 32.6888085)
```

**Comment by HarelM** [comment] 2022-04-27 09:23
I think most of the warning that still exist are the following - i.e. places where two polygons are touching each other, I'll need to see if this can be fixed with some sort of union.
![image](https://user-images.githubusercontent.com/3269297/165486595-171df745-6938-4409-9180-075524680f25.png)

**Comment by zstadler** [comment] 2022-04-27 09:37
I've explored some more errors. As you wrote, most cases involve adjacent non-overlapping polygons.

### El Zeitun School 
> ```
> There was a problem merging 2 polygons from the following feature into a multipolygon El Zeitun School (OSM_way_297323423), https://www.openstreetmap.org/way/297323423 Self-intersection (34.4574539, 31.4999457)
> ```
Adjacent non-overlapping polygons ([Overpass Turbo](https://overpass-turbo.eu/s/1hZT))

![image](https://user-images.githubusercontent.com/1304610/165471278-12d6b034-7245-41e3-a364-4d36b4e42d9e.png)

### Nuseirat junior high school males (c)

> ```
> There was a problem merging 2 polygons from the following feature into a multipolygon Nuseirat junior high school males (c) (OSM_node_505017030), https://www.openstreetmap.org/node/505017030 Self-intersection (34.3921073, 31.4606349)
> ```
Several groups of adjacent non-overlapping polygons ([Overpass Turbo](https://overpass-turbo.eu/s/1hZG))

![image](https://user-images.githubusercontent.com/1304610/165460736-c9fb598b-13e3-402d-a916-b0a98ea9a8f8.png)

### El Nada Tower 

> ```
> There was a problem merging 17 polygons from the following feature into a multipolygon El Nada Tower (OSM_node_503996785), https://www.openstreetmap.org/node/503996785 Self-intersection (34.5198268, 31.5480373)
> ```
Several groups of adjacent non-overlapping polygons ([Overpass Turbo](https://overpass-turbo.eu/s/1hZH)). A proper merge ni this case should probably create inner "holes"

![image](https://user-images.githubusercontent.com/1304610/165459829-c7dd1f5e-9493-421f-aadf-54a9d7592d41.png)

### אוניברסיטת חיפה

> ```
> The following merge created a weird geometry: אוניברסיטת חיפה https://he.wikipedia.org/wiki/%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA%20%D7%97%D7%99%D7%A4%D7%94 Point, Polygon, LineString, Polygon
> ```

Two overlapping polygons and a linestring ([Overpass Turbo](https://overpass-turbo.eu/s/1hZI))

![image](https://user-images.githubusercontent.com/1304610/165461780-20521eac-0767-473b-a8ce-684e649e5dba.png)

**Comment by HarelM** [comment] 2022-04-27 09:57
Latest code shows the following warnings, which might be caused by bad mapping as they are all a combination of polygons and lines, it might also be a bad conversion from OSM entity into a geojson object.
```
The following merge created a weird geometry: אוניברסיטת חיפה https://he.wikipedia.org/wiki/%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA%20%D7%97%D7%99%D7%A4%D7%94 Point, Polygon, LineString, Polygon
The following merge created a weird geometry: הקניון הלבן https://www.openstreetmap.org/node/6413905085 Point, LineString, Polygon
The following merge created a weird geometry: נחל מערות https://he.wikipedia.org/wiki/%D7%A0%D7%97%D7%9C%20%D7%9E%D7%A2%D7%A8%D7%95%D7%AA LineString, LineString, LineString, LineString, LineString, Polygon
The following merge created a weird geometry: ואדי א-סלקא https://www.openstreetmap.org/way/759979226 LineString, LineString, LineString, Polygon
The following merge created a weird geometry: שמורת טבע נחל דלתון https://inature.info/wiki/%D7%A9%D7%9E%D7%95%D7%A8%D7%AA%20%D7%A0%D7%97%D7%9C%20%D7%93%D7%9C%D7%AA%D7%95%D7%9F LineString, LineString, Polygon
The following merge created a weird geometry: הר הרצל https://www.openstreetmap.org/relation/2730115 LineString, LineString, Polygon
The following merge created a weird geometry: אזור מסחרי כורזין https://www.openstreetmap.org/relation/11568850 LineString, LineString, LineString, LineString, LineString, Polygon
The following merge created a weird geometry: קריית מטלון https://www.openstreetmap.org/way/891059858 LineString, MultiPolygon
The following merge created a weird geometry: שכונה דרום https://www.openstreetmap.org/way/893988575 LineString, MultiPolygon
The following merge created a weird geometry: רמת ורבר https://www.openstreetmap.org/way/209751641 LineString, MultiPolygon
The following merge created a weird geometry: מרכז העיר https://www.openstreetmap.org/way/253573831 LineString, MultiPolygon
```

**Comment by HarelM** [comment] 2022-04-27 10:30
For example the following is bad mapping as there's one line that is not part of the relation (and probably needs to be removed):
The following merge created a weird geometry: קריית מטלון https://www.openstreetmap.org/way/891059858 LineString, MultiPolygon
Relevant relation:
https://www.openstreetmap.org/relation/12121570
Not sure how to fix this though, it seems that this line need to be deleted as it is covered by another line:
https://www.openstreetmap.org/way/891059857

**Comment by zstadler** [comment] 2022-04-27 10:42
I looked at some of the remaining failures. It looks like several of these failed merges are between incompatible OSM objects.

- Merge of a neighborhood polygon, a university, a bus platform line and an aerialway station at [אוניברסיטת חיפה](https://overpass-turbo.eu/s/1hZI)
- Merge of a tourist attraction area, a trail relation, a cliff and a tourist attraction node at [הקניון הלבן](https://overpass-turbo.eu/s/1i0e)
- Merge of a office building and several stream segments at [נחל מערות](https://overpass-turbo.eu/s/1i0f)
- Merge of a neighborhood polygon and a stream that crosses it at [ואדי א-סלקא](https://overpass-turbo.eu/s/1i0a)

BTW, I fixed an OSM error at שמורת טבע נחל דלתון (duplicate + incorrect mapping of area)

**Comment by zstadler** [comment] 2022-04-27 10:53
> For example the following is bad mapping as there's one line that is not part of the relation (and probably needs to be removed): The following merge created a weird geometry: קריית מטלון https://www.openstreetmap.org/way/891059858 LineString, MultiPolygon Relevant relation: https://www.openstreetmap.org/relation/12121570 Not sure how to fix this though, it seems that this line need to be deleted as it is covered by another line: https://www.openstreetmap.org/way/891059857

I removed that line

**Comment by HarelM** [comment] 2022-04-27 10:54
Thanks!

**Comment by HarelM** [comment] 2022-04-27 11:00
Yea, I'm not sure how to properly solve these unwanted merges.
The logic in the following function does most of the heavy lifting:
https://github.com/IsraelHikingMap/Site/blob/97bd4c535f30462391bd9e063460f0d64357ad38/IsraelHiking.API/Executors/FeaturesMergeExecutor.cs#L407
It looks at icons and categories (a simplified projections of the OSM tags) to better know which entities to merge.
I'm not sure what other rules should be introduced there though I as would like to avoid as much as possible adding specific tags there (although there are some already).

**Comment by HarelM** [comment] 2022-04-27 11:36
I've added waterway and building to the exclusive tags list in order to solve some unwanted merges.
Here are the last few left:

### See comments above:
The following merge created a weird geometry: אוניברסיטת חיפה https://he.wikipedia.org/wiki/%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA%20%D7%97%D7%99%D7%A4%D7%94 Point, Polygon, LineString, Polygon
The following merge created a weird geometry: הקניון הלבן https://www.openstreetmap.org/node/6413905085 Point, LineString, Polygon

### bad conversion?
The following merge created a weird geometry: אזור מסחרי כורזין https://www.openstreetmap.org/relation/11568850 LineString, LineString, LineString, LineString, LineString, Polygon - I've looked at the OSM entity and it looks fairly good but for some reason it is converted to LineString and not a Polygon so this looks like a bad conversion and not bad merge.

### Needs further investigation:
The following merge created a weird geometry: הר הרצל https://www.openstreetmap.org/relation/2730115 LineString, LineString, Polygon 
The following merge created a weird geometry: שכונה דרום https://www.openstreetmap.org/way/893988575 LineString, MultiPolygon
The following merge created a weird geometry: רמת ורבר https://www.openstreetmap.org/way/209751641 LineString, MultiPolygon
The following merge created a weird geometry: מרכז העיר https://www.openstreetmap.org/way/253573831 LineString, MultiPolygon
```

**Comment by zstadler** [comment] 2022-04-27 11:36
Perhaps the default should be non-merge.
Printing the categories in the log file could also help us understand what's being merged.

**Comment by HarelM** [comment] 2022-04-27 11:46
>Perhaps the default should be non-merge.

"CanMerge" can be easily negated, it's not about default, it's about writing what we want and don't want to merge.
I don't think the default should be non-merge since will get too many search results without a proper way to distinguish between them. 
My mistake, Category is not checked but icon is. In all the above cases the icon is equal, printing it won't add any valuable information.

**Comment by zstadler** [comment] 2022-04-27 11:46
Also:
- Avoid merge of [`public_transport`](https://wiki.openstreetmap.org/wiki/Key:public%20transport?uselang=en) elements. I'd even consider avoiding their extraction for the OSM data

There is also a big mess for way members of administrative boundary relations. They should not have names, but often they do. In addition, unrelated to the problem at hand, they should have `boundary` and `admin_level` tags, but often they don't.

**Comment by zstadler** [comment] 2022-04-27 11:48
> I don't think the default should be non-merge since will get too many search results without a proper way to distinguish between them. 

In a n^2 space of possible combinations of categories, I believe it will be simpler to identify what should be merged than otherwise. It is your call anyway.

**Comment by HarelM** [comment] 2022-04-27 11:54
I can't think of a list that I feel good about that I can write down in order know what's being merged and what's not, and since everything that is not merged will appear twice or more in the search results (which is limited to 10 items) I prefer to "over-merge" than "under-merge".

**Comment by zstadler** [comment] 2022-04-27 13:41
Sounds good!

**Closed** 2022-04-27 13:47 UTC
Labels: bug, Low
