### ISSUE TITLE
DB update process memory leak?

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#613] opened 2018-01-18 16:57 UTC
## What really happened
* Manual run of a DB update from the task scheduler
  ```
  2018-01-18 16:02:28.6302 |804 |INFO | No specific filters were applied, updating all databases.
  ```
* The update progressed nicely, but the progress messages stopped at 16:23
  ```
  2018-01-18 16:18:21.0124 |769 |INFO | Preprocessing OSM data to GeoJson, total distict names: 75791 
  2018-01-18 16:19:44.6687 |769 |INFO | Finished processing 5000 names of 75791 
  2018-01-18 16:20:20.1530 |769 |INFO | Finished processing 10000 names of 75791 
  2018-01-18 16:20:45.3874 |769 |INFO | Finished processing 15000 names of 75791 
  2018-01-18 16:21:01.9812 |769 |INFO | Finished processing 20000 names of 75791 
  2018-01-18 16:21:15.5124 |769 |INFO | Finished processing 25000 names of 75791 
  2018-01-18 16:21:35.4968 |769 |INFO | Finished processing 30000 names of 75791 
  2018-01-18 16:21:56.0124 |769 |INFO | Finished processing 35000 names of 75791 
  2018-01-18 16:22:10.9968 |769 |INFO | Finished processing 40000 names of 75791 
  2018-01-18 16:22:26.6530 |769 |INFO | Finished processing 45000 names of 75791 
  2018-01-18 16:22:46.6687 |769 |INFO | Finished processing 50000 names of 75791 
  2018-01-18 16:23:25.7937 |769 |INFO | Finished processing 55000 names of 75791 
  ```
* The error messages after 16:23 seems to be irrelevant. The first of the is approx. 18 minutes later:
  ```
  2018-01-18 16:41:17.2370 |123 |ERROR| Microsoft.AspNetCore.Server.Kestrel | Connection id "0HLAUFRGBBC6K": An unhandled exception was thrown by the application. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
  ```
* In order to check if the DB update process is still active, at 18:35 I've run  
  `curl -k -X POST https://israelhiking.osm.org.il/api/update -d ""` from a command prompt.   
  The result was the normal HTML response and not a `Can't run two full updates in parallel` message. 

My conclusion is that the DB update process aborted without an error message.

**Comment by HarelM** [comment] 2018-01-18 18:52
Update contoller has a finally block to release the semaphore, so the only explanation to this is if the method got stuck on a dead-lock or something, which is not likely but could happen, but I can't think of a reason why...
You'll probably need to restart the application pool in IIS in order to release this if this continues...

**Comment by zstadler** [comment] 2018-01-18 18:58
As you can see in the log file, there was no problem with a subsequent DB update at 18:35. No lock or block exists as far as I understand.

**Comment by HarelM** [comment] 2018-01-18 22:30
Were we looking at the same file?
I see the following lines, please let me know if I'm missing something.
```
2018-01-18 16:21:56.0124 |769 |INFO | Finished processing 35000 names of 75791 
2018-01-18 16:22:10.9968 |769 |INFO | Finished processing 40000 names of 75791 
2018-01-18 16:22:15.3562 |  1 |INFO | Initializing LRU cache. 
2018-01-18 16:22:15.7780 |  1 |INFO | Initializing singleton services 
```
The last two lines indicate the the server completely crashed (these are the first lines that are logged when the server starts).
A possible root cause for this is out of memory exception or something of that sort that would explain why the log stopped emitting the indexing lines.

I would appreciate it if you could place a monitoring tool on the memory of the machine/process and stress test the server using the rebuild database, or just try and see the state of the memory while the rebuild is running to see if it returns to normal after the rebuild is complete.
I'll try to do the same on my development environment to see if I can reproduce it locally.

**Comment by HarelM** [comment] 2018-02-21 22:37
Haven't seen this behavior again and local tests seems to indicate the memory is not leaking, at least not in C#, closing this for now, will reopen in case of new evidence.

**Closed by HarelM** 2018-02-21 22:37 UTC
