### ISSUE TITLE
Nothing happens when opening the IHM share URL from the app with the app

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#960] opened 2019-02-07 08:58 UTC
## Bug/Feature
(Delete the non-relevant)

## What I expect to happen
After creating or updating a share, and opening the resulting URL with the app, the app is expected to open the share URL or close the share dialog.

## What really happened
Nothing changes and the dialog remains open.
For reference, the desktop and mobile browsers switches to the resulting 

## What I did that caused the issue - step by step
- View a share from your share list
- Update the current share without changing anything.
- Click on the URL shown in the response
   
   ![screenshot feb 7 2019 10_42_46](https://user-images.githubusercontent.com/1304610/52399706-ab289c00-2ac5-11e9-8d61-e9d47ea58d0d.png)
- Choose to open the URL with the app

## My environment
* Operating System and version: Android

**Comment by HarelM** [comment] 2019-02-07 19:57
Here's the explanation of this issue:
After creating a share the state of the app is "editing current share" so that you'll be able to update the share - this state is cleared only when closing the app or refreshing the browser.
When you navigate to current share (clicking the link) the state is checked - if you are editing the current share then nothing should happen (since you are already viewing this share).
@zstadler I'm not sure what should be the right behavior here. A phone conversation might be in order here since I'm not sure how well I explained the root cause for this...

**Comment by HarelM** [comment] 2019-02-08 20:57
In continue to our phone conversation, it seems that removing the check that the current share is in edit mode didn't help. :-(
Parking this for now, as I don't see an easy fix to this.

**Comment by zstadler** [comment] 2019-02-09 05:15
The other option we've discussed was to use this check to close the dialog. Did you have a chance to try it?

**Comment by HarelM** [comment] 2019-02-09 08:05
I did, the dialog open and the route handling are in two different places and it will not be easy to handle them together, hence the parking.

**Comment by HarelM** [comment] 2020-02-07 07:35
More of a patch than anything else...

**Closed** 2020-02-07 07:35 UTC
Labels: Low, bug
