### ISSUE TITLE
typo on notification bar

### ISSUE THREAD

**Issue by eyal03** [IsraelHikingMap/Site#805] opened 2018-09-13 13:28 UTC
## What really happened
when i drag window down and see notification bar there is a typo for this app

## My environment
* Operating System and version:
* Web Browser and version:
Samsung 8+
Android

## Thing I think the developers should know, images, links etc.

![screenshot_20180913-161927_samsung experience home](https://user-images.githubusercontent.com/43241717/45491266-fe462f00-b771-11e8-8a63-8e6c0ff5326a.jpg)

**Comment by zstadler** [comment] 2018-09-13 14:54
Duplicate of #804 
The translation was fixed.
Thanks for the report!

**Closed by zstadler** 2018-09-13 14:54 UTC
