### ISSUE TITLE
Search for coordinates no longer creates a result POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#2078] opened 2024-11-24 14:13 UTC
### What happened?

Until recently, a search using coordinates created a result POI. That result POI could have been added to the route.

Currently, the map pans to the desired location, but no result POI is shown.

### What steps will reproduce the bug?

- Search for a coordinate, such as `200000 540000`
- Select the first and only result
- No POI is shown at the location

![image](https://github.com/user-attachments/assets/ba30db21-c1b3-442d-839b-303d98bb451a)

### What I expect to happen

The selected search result should have a result POI on the map

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

All

### Browser Name and Version

All

**Comment by HarelM** [comment] 2024-11-24 14:16
Duplicate of #2077

**Closed by HarelM** 2024-11-24 14:16 UTC
Labels: bug
