### ISSUE TITLE
One Wikipedia link for one POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#686] opened 2018-04-20 13:06 UTC
## What I expect to happen
Each POI or trail would have at most one Wikipedia link

## What really happened
Some have multiple links

## What I did that caused the issue - step by step
[Open this link](https://israelhiking.osm.org.il/#!/?q=עזוז)

## My environment
* Operating System and version: Any
* Web Browser and version: Any

## Thing I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/1304610/39052460-b040ded4-44b4-11e8-9e4f-566728b9a378.png)

**Comment by HarelM** [comment] 2018-04-20 21:41
This is related to merging different languages - the links are to different pages - one in Hebrew and the other in English.
I'll see if I can remove links that are not relevant to the selected user language.

**Comment by zstadler** [comment] 2018-05-15 16:14
[Shomrat](https://israelhiking.osm.org.il/#!/17/32.9508/35.0942) has 3 POI location. This is probably because of the two Hebrew spellings - "שמרת", "שומרת" - and the the two languages on Wikipedia:
[![image](https://user-images.githubusercontent.com/1304610/40069461-1493d77e-5874-11e8-91c5-69eb5690510a.png)](https://israelhiking.osm.org.il/#!/17/32.9508/35.0942)

**Comment by HarelM** [comment] 2018-05-15 21:09
This issue is describing a problem where two merged pois show two links instead of one.
I don't see how the last image is related to it.
Please open a different issue describing the expected behavior as I failed to understand it from the description and screenshot.

**Comment by zstadler** [comment] 2018-05-17 21:09
That's fine. I'll open a new issue after this issue is resolved if the Shomrat POIs will still be problematic.

**Comment by HarelM** [comment] 2018-05-29 20:41
There are two possible solutions here:
1. To only remove the links when a poi is not in the right language.
2. To return `null` from `WikipediaPointsOfInterestAdapter.GetPointOfInterestById(...)` when requested.

I tend to go with 2 since it makes more sense and feels less hacky. 
The only problem with that is when returning `null` this POI is not used for its images - so in the example above Azuz will have only one image in English and one in Hebrew and the images are different as opposed to now that it has both images in both languages...

**Comment by HarelM** [comment] 2018-05-29 20:44
I now see that the second solution makes more sense for the images as well - כפר סאלד example.
I will implement it then.

**Closed** 2018-05-29 20:46 UTC
Labels: Low, bug
