### ISSUE TITLE
Duplicate wikipedia tag as suffix and prefix

### ISSUE THREAD

**Issue by sannius** [IsraelHikingMap/Site#1082] opened 2019-11-14 09:37 UTC
Hi, looks like IsraelHiking.osm.org.il creates duplicate wikipedia tags (wikipedia=he:<data> and wikipedia:he=<data>) on edit.
The osmose jumps on it, like http://osmose.openstreetmap.fr/en/error/35511053879
Can only wikipedia=he:<data> be added on edit?

**Comment by HarelM** [comment] 2019-11-14 09:57
I'm not sure it's not a bug in osmose, here's how I see it:
Wikipedia tag can be in multiple languages, much like the name tag. Each language has its own tag, but I'd like to note in OSM which is the main language. I'm doing so by using the wikipedia tag without the language.
This is my interpretation though...

**Comment by HarelM** [comment] 2019-11-14 19:22
Some issues that involves around the above issue: #484 #616 #760

**Comment by zstadler** [comment] 2019-11-15 06:29
The [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_languages) is very clear:

> **In almost all cases, a single wikipedia tag as described above is sufficient.** Data users can access articles in other languages where available using Wikipedia's [interlanguage links](http://en.wikipedia.org/wiki/Help:Interlanguage_links). If interlanguage links are missing, this should usually be fixed within wikipedia.
> 
> One example where it is appropriate to provide additional explicit links to articles in secondary languages is where the subject is included in an article on a broader subject in the secondary language, for example to the English article which the particular museum in France while French wikipedia has only `wikipedia:fr=Monuments et sites de Paris`. In another example the structure of subjects in articles cannot be matched 1:1 with interlanguage links (or maybe there are several articles for the same object). In these circumstances use the format `wikipedia:lang=page title` for the secondary languages. 

Using a secondary language is acceptable where these are different articles in different languages and the articles have justifying scope or structure differences.

This is not the case here and duplicating the `wikipedia=he:` tag into the `wikipedia:he=`  tag does not comply with the wiki.

**Comment by HarelM** [comment] 2019-12-03 20:43
Wiki pages in Hebrew do not have good translation and vice versa which creates a lot of wikipedia pages in every language even for the same place. The above OSM wiki definition might be right, but naive.
While I do not agree with the above comment it is my opinion, and I'm entitled to it.
Regardless, this is not the place to discuss such a matter, The OSM forum is. If we can decide there what is the right course of action I'll implement the decision.
Closing for now...

**Closed by HarelM** 2019-12-03 20:43 UTC
