### ISSUE TITLE
Associate custom maps with username instead of cookies/cache

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#403] opened 2017-07-18 14:25 UTC
I recently replaced my PC and it the custom maps were a pain to reconstruct

**Comment by HarelM** [comment] 2017-07-18 14:51
Already implemented, I asked you to test if it works, you should read you e-mails :-)
Duplicate of #364

**Closed by HarelM** 2017-07-18 14:51 UTC
