### ISSUE TITLE
Add "zoom to route" capability

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#216] opened 2016-09-02 11:38 UTC
It would be nice to have a capability to re-zoom the map on a given route in order to see it in full.

For shared or opened routes, the workaround is to reload the map and the route. However, for routes edited on-site, I'm not aware of any workaround.

Ideally, a double-click on the route's entry in the layers pane would be assigned to this capability. I remember there were some reservations on the use of double-click in the UI, but I cannot recall why.

**Comment by HarelM** [comment] 2016-09-02 11:46
Double click is not intuitive for mobile devices.
Maybe upon selection and not upon double?

**Comment by zstadler** [comment] 2016-09-02 12:28
Selection does not necessarily mean that the user would like to change the map location or zoom.

What would be an intuitive gesture on a mobile device? As far as I can see, many similar mobile interactions are done through a drop-down menu.

**Comment by HarelM** [comment] 2016-09-06 13:13
I think a drop down menu would be an overkill in this case but I'm not sure if there's another option.
I would prefer a button somewhere but it seems that adding a button for this action is an overkill too...
I don't have a better idea though, if you can think of a decent UI for this let me know.

**Comment by zstadler** [comment] 2016-09-06 14:19
How about adding it to the "settings" window of the track?

In a way, the settings windows should do everything that can be done with respect to the route, similar to the 3 vertical points icon used by some UIs.

**Comment by HarelM** [comment] 2016-09-06 15:52
I thought about it, but doesn't this miss the point? move to route should be a simple usage as far as I can tell and not an advanced one like other stuff that are in the route properties window...?

**Comment by zstadler** [comment] 2016-09-06 20:55
The natural user action on a PC is a double click.
If we cannot find a natural way to do it on a touch device, then it cannot
be as natural as we want.
What else can be done?

It seems like touch devices have less options for interactions: press,
long-press, drag-and-drop, and sliding in different directions. As a
result, the interface is sometimes more complex.

**Comment by HarelM** [comment] 2016-09-18 05:56
Do we wand to add another button to the layers control near the route name to facilitate for this? with the crosshairs icon?
Another options is to zoom to route when a user select to edit it, it is a valid use case since a user that wants to edit a route probably wants to see it in his screen.
Would that solve this issue?
I prefer not to add more buttons to the route layer as it is a slippery slope...

**Comment by zstadler** [comment] 2016-09-18 10:29
When there are multiple routes, it is unexpected that the map will zoom when the user switches editing between the routes. I think we need a separate button.

To address the overcrowding of the layer control, some buttons can be visible only in advanced mode. 
I suggest that in non-advanced mode, the controller will only enable deleting the route and changing its name and color.

Also, the "toggle visibility" button is a duplicate of the functionality in the layers pane.

**Comment by HarelM** [comment] 2016-09-18 14:20
I think I can agree with what you are saying, can you create an image of regular and advanced mode?
The visibility is not really duplicated as you can access it in regular mode currently, but if we always place the open properties button, even in regular mode, we can define the appearance for each mode as we see fit, without duplication.

**Comment by zstadler** [comment] 2016-09-18 14:54
I didn't understand the comment about the visibility button. I was referring to the icon on the left of each route entry: <img width="95" alt="2016-09-18 17_37_52-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18616560/ad24273a-7dc6-11e6-80d6-254e0090bdf2.png">
It is readily accessible without opening the "settings" dialog. IMO, the visibility button in the settings dialog is therefore not needed.

The simple Route Properties dialog can look like:

<img width="165" alt="simplerouteproperties" src="https://cloud.githubusercontent.com/assets/1304610/18616664/99c4caa8-7dc8-11e6-8f50-569a8ee3651b.png">

The advanced mode can look like:

<img width="449" alt="2016-09-18 17_40_57-israel hiking map" src="https://cloud.githubusercontent.com/assets/1304610/18616688/f103fdac-7dc8-11e6-92f8-34feb415a75d.png">

**Comment by HarelM** [comment] 2016-10-04 21:20
Not sure if this should be a concern but the advanced options button is not on this dialog so the user can't switch to advanced mode without closing this first.
Implemented as requested for now.

**Comment by zstadler** [comment] 2016-10-05 05:59
The advanced version of this dialog is not available on Firefox. The simple version of dialog is shown when the layers pane is in either advanced or simple mode.

**Comment by zstadler** [comment] 2016-10-05 06:27
The center of the route is not in the center of the map pane after clicking the "center" button:

<img width="960" alt="2016-10-05 09_13_51-" src="https://cloud.githubusercontent.com/assets/1304610/19102884/1a57c222-8adc-11e6-9bdc-851ba891221d.png">


The center of the route is in the center of the map pane only if and when left pane is closed. Some users, especially those with a large screen, can prefer keeping the left pane open at all times.

IMO,

- The route should be centered within the map pane.
- Opening and closing of the left pane should keep the center of the map centered within the map pane.

**Comment by HarelM** [comment] 2016-10-05 07:50
I don't have the means to achieve it easily, the fact that the map center in not the center of the view is caused by the current implementation of the sidebar.
The firefox issue you described above is not happening to me.
I think it's good enough like that although not perfect...

**Comment by zstadler** [comment] 2016-10-05 08:58
I assume you mean that unlike when the browser window size is changed, the leaflet pane is "not informed" of the change in its size when the side bar is visible. As a result, the center of zoom-in and zoom-out is also shifted when the sidebar is open.

Which Firefox version are you using?
After this change, I cannot access the advanced version of the dialog on Firefox.

**Comment by HarelM** [comment] 2016-10-05 22:30
Latest on win 10 show proper behavior. please try and refresh the browser while "F12" is open.
I get good results on chrome and FF both on PC and mobile.
Please reopen if you are sure there's a problem (try it on another PC too).
off:
![image](https://cloud.githubusercontent.com/assets/3269297/19134061/5ab2b29a-8b64-11e6-8fd6-68d4da16ea4e.png)
on:
![image](https://cloud.githubusercontent.com/assets/3269297/19134072/6da43f36-8b64-11e6-8fd3-5eac2b8dc1fd.png)

**Closed by HarelM** 2016-10-05 22:30 UTC
Labels: enhancement, Low

**Comment by zstadler** [comment] 2016-10-06 12:09
I'm no longer able to reproduce the issue. Thanks!
