### ISSUE TITLE
Wikipedia image is not used by the POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1125] opened 2020-01-15 07:24 UTC
## Bug

[This POI](https://israelhiking.osm.org.il/poi/OSM/node_5605113504?language=en) has a link to the [English Wikipedia page](https://en.wikipedia.org/wiki/Faidherbia), but the [Wikipedia image](https://en.wikipedia.org/wiki/File:Faidherbia_albida.JPG) is not used in the POI.

**Comment by HarelM** [comment] 2020-01-15 09:26
OK, I think I understand the root cause for this issue, here goes:
The mirroring of Wikipedia is done only on entities that has a location.
The merge is between the entities that are mirrored and the OSM elements.
The reference from the OSM element is to a wikipedia entry without a location and so the merge is not really happening (which is what you see - no image and no description).
The link to the page is a simple conversion between the OSM wikipedia tag and the address so the link appears in the POI and it looks like the points are merged but actually they weren't.

Not sure what should be done in this case though... 
This is somewhat similar to what we talked about with the Tambur store...

**Comment by zstadler** [comment] 2020-01-15 14:07
I hope that we agree that from a UX perspective, a POI pane that shows a link to Wikipedia should also show the Wikipedia description or image if OSM does not have them.

This probably means that additional mirroring needs to be done for OSM elements in the POI layer with a Wikipedia link that are missing an image or description.

The Tambur store discussion was about which Wikipedia entries should be included in the POI layer. This issue is about showing proper information for a POI that is included in the POI layer.

**Comment by zstadler** [comment] 2020-05-24 06:41
This bug still exists

**Comment by HarelM** [comment] 2020-08-26 14:06
Phone conversation summary:
The preferred solution is to query overpass turbo for linked wikipedia tags and bring them as part of the mirroring process.
The following overpass turbo link can do it:
http://overpass-turbo.eu/s/XpL
Another possibility is to do it as part of the merge process, but I would like to keep the mirroring and merge process as separate as possible, so this solution is less preferred.

**Closed** 2020-08-27 09:48 UTC
Labels: Low, bug
