### ISSUE TITLE
En-Route edit not working

### ISSUE THREAD

**Issue by bmwmccil** [IsraelHikingMap/Site#1481] opened 2021-04-17 11:09 UTC
## Bug
(Delete the non-relevant)

## What I expect to happen
I try to edit a new point to point route (on-road) and expect to get a route

## What really happened
I get straight lines (even though I verified that "straight line" option is not selected)

## My environment
* Operating System and version: Windows 10 Pro 64bit
* Web Browser and version: Chrome Version 89.0.4389.128 (Official Build) (64-bit)

**Comment by HarelM** [comment] 2021-04-17 11:21
Duplicate of #1480.
Can you please comment there?
I can't seem to be able to reproduce the bug on my devices...
If you can open debug tools (f12) on chrome and capture the console tab there it would be great. Also if you see any warning or error pop up please add it there.
Thanks!

**Closed by HarelM** 2021-04-17 11:21 UTC

**Comment by bmwmccil** [comment] 2021-04-20 14:37
Solved by uninstalling and re-installing Chrome.
Thanks

**Comment by HarelM** [comment] 2021-04-20 19:26
We were experiencing some issues with our routing server as we posted in our facebook group.
In any case, no matter what the bug is in our site there no real justification to uninstall and install chrome :-)
