### ISSUE TITLE
Circulate through route colors

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1551] opened 2021-07-17 13:12 UTC
## What I expect to happen
When I add a new route to a map with an existing route I expect it to have a different color. The system can figure what colors are already there and choose a different one.

## What really happened
Some of the routes had the same color, making them hard to tell apart

## What I did that caused the issue - step by step
Opened or planned a red route.
Recorded a new route, or imported a route that was previously red to the map.

## My environment
Both web and app.

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/689201/126028536-44658a2b-b0dc-4aca-a145-b4f6830bb828.png)
![image](https://user-images.githubusercontent.com/689201/126028545-c106898b-920d-4683-94cf-c7aba40160fa.png)

**Comment by HarelM** [comment] 2021-07-17 13:18
I'm not sure about recording, but this is what happens in generalbi believe, except when there's data in the file telling the app to use a specific color. I tend to think that respecting what in the file is more important in terms of data consistency...
Please recheck this and specify what's exactly not working as intended assuming the above considerations as this is implemented in theory...

**Comment by HarelM** [comment] 2021-07-29 12:22
@valleyofdawn did you have a chance to check this?
Is there anything to do here or can I close the issue?

**Comment by HarelM** [comment] 2021-08-10 19:43
No response... Closing...

**Closed by HarelM** 2021-08-10 19:43 UTC
