### ISSUE TITLE
Unsuccessful recording keep asking for continuation.

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#985] opened 2019-03-02 09:18 UTC
## What really happened
Wherever I open the app it asks me again. 

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment] 2019-03-02 17:15
I'm unable to see a badly stopped recording at all in latest version. I'll investigate it, might be a timing issue...

**Comment by HarelM** [comment] 2019-03-03 21:22
@valleyofdawn I have tried to create an app in order to debug this but when installing it the problem goes away.
Can you please check if deleting the app cache solved this (don't uninstall and install again as it seems that it doesn't clean the database itself)? It might be related to the latest change I made in how the database works...

**Comment by valleyofdawn** [comment] 2019-03-04 07:15
Cleaning the cache didn't solve the problem.

בתאריך יום א׳, 3 במרץ 2019, 23:22, מאת Harel M ‏<notifications@github.com>:

**Comment by HarelM** [comment] 2019-03-04 08:31
Bummer, Please try uninstall and install. If this doesn't help please install the following debug version:
https://drive.google.com/file/d/1imz3Oxb4IfQy0B6tB4Hcdt7pSJYLue8u/view?usp=drivesdk
And test the relevant scenario. After you manage to reproduce the problem please send the log file under IHM folder in your device SD card.

**Comment by zstadler** [comment] 2019-05-31 16:42
A debug trace was sent by e-mail.

In this case, I was able to exit this loop by deleting all traces. However, the traces were restored after the app was re-lunched. Subsequent deletions were not successful. The deletions were successful only after a new recording was done.

**Comment by HarelM** [comment] 2019-06-01 07:41
The latest issue seems to be related to app closing before database update.

**Closed** 2019-06-01 07:59 UTC
Labels: App, bug
