### ISSUE TITLE
Show line breaks in the description of saved routes

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1423] opened 2021-01-13 11:57 UTC
## What I expect to happen
Show line-breaks in the descripion of a saved route

Applies to the following places:

#### 1. In the list of saved routes

Separate the saved route title from the description:
<img width="35%" src="https://user-images.githubusercontent.com/1304610/104443895-b16ffe80-559f-11eb-80c8-f7a2e9c31c2f.png"/>

#### 2. In the messsage following a successful save

Avoid duplicating the saved route title:
<img width="35%" src="https://user-images.githubusercontent.com/1304610/104462778-a75af980-55b9-11eb-9353-34b8ad337735.png"/>

#### 3. In the intermittent message shown just after the saved route was loaded

I was unable to create a mockup. See the last screenshot below

#### In the list of saved routes

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104449056-b08e9b00-55a6-11eb-8baa-752924a60e4a.png"/>

#### In the messsage following a successful save

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104441306-29d4c080-559c-11eb-8b4d-e04a3202deea.png"/>

#### In the intermittent message shown just after the saved route was loaded

<img width="35%" src="https://user-images.githubusercontent.com/1304610/104441882-f6466600-559c-11eb-9c5c-40dd4e2fac19.png"/>

## What I did that caused the issue - step by step
Use line breaks in the description of a cloud-saved route

## Things I think the developers should know, images, links etc.
1. The example is available at https://israelhiking.osm.org.il/share/uXPOfXpadq.
2. The mock-ups are using the `white-space: pre-line;` style directive.

**Comment by HarelM** [comment] 2021-01-15 12:47
This seem like a duplicate of #1422 
I'm closing this...
@zstadler please verify that I'm correct and that these issue are truly duplicate of one another...
If they are not, then please re-open this one and elaborate how it is different from the previous one...

**Closed by HarelM** 2021-01-15 12:47 UTC
