### ISSUE TITLE
Incorrectly rotated POI image

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#496] opened 2017-10-04 07:11 UTC
## Bug
The image for [המפל הנסתר](https://israelhiking.osm.org.il/#!/?q=המפל%20הנסתר) is shown rotated on the site.

## What I expect to happen
The site to maintain the orientation of the image, as [appears on Wikimadia](https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg)

## What really happened
The image is rotated:
![image](https://user-images.githubusercontent.com/1304610/31163378-cb1135f8-a8ea-11e7-8304-25a36431ca63.png)

## What I did that caused the issue - step by step
- Search for "המפל הנסתר"
- Click on the first result - "המפל הנסתר, מועצה אזורית תמר"

## My environment
* Operating System and version: Windows 10 home
* Web Browser and version: Firefox 55.0.3 (64-bit)

**Comment by HarelM** [comment] 2017-10-04 07:19
is this a duplicate of #455?

**Comment by zstadler** [comment] 2017-10-04 07:28
In #455 you wrote it's a Wikimedia issue. 

In this case it shows well when you do `Right click -> View Image` on the POI's thumbnail. Therefore, it is not a Wikimadia issue.

**Comment by HarelM** [comment] 2017-10-04 07:34
I see. Thanks for the clarification!
Maybe the following will fix this:
https://stackoverflow.com/questions/24658365/img-tag-displays-wrong-orientation
```
img {
    image-orientation: from-image;
}
```

**Comment by zstadler** [comment] 2017-10-04 07:42
Yes, that does the trick!

**Comment by zstadler** [comment] 2017-10-04 07:47
However, since both width and height of the picture is set in the HTML, the picture is distorted: 

![image](https://user-images.githubusercontent.com/1304610/31164744-15f5ff30-a8f1-11e7-84fd-bb08e7edf917.png)

rather than

![image](https://user-images.githubusercontent.com/1304610/31164810-55435b92-a8f1-11e7-8cd6-b5cd7c13d547.png)

**Comment by HarelM** [comment] 2017-10-04 08:08
The above is not supported in chrome apparently.
Wikimedia's image link is not the one they are using when presenting the image in their page.
Not sure how to address this, might need to use some flags on the image link to get the right size and orientation.
In any case I think this issue is covering #455 as well.

**Comment by zstadler** [comment] 2017-10-04 14:03
1. Somehow, Chrome shows the correct orientation when [viewed on Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg), and when opening the full-resolution image.

2. Wikimadia Commons shows a 450 pixel thumbnail using
https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg/450px-Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg
The use of thumbnails for the POI images is covered by #497

**Comment by HarelM** [comment] 2017-10-04 23:54
I've gone to the source :-) here is my analysis when using internet explorer:
Surfing to the original image address the using internet explorer shows a rotated image:
https://upload.wikimedia.org/wikipedia/commons/6/61/Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg

Surfing to the thumbnail URL using internet explorer shows an image with the right orientation.
https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg/450px-Israel_Hiking_Map_%D7%94%D7%9E%D7%A4%D7%9C_%D7%94%D7%A0%D7%A1%D7%AA%D7%A8.jpeg

This means that the wikimedia images server shrinks and rotates the thumbnail image before returning it to the client.
Maybe we can use #497 for both thumbnail and "bigger" image and this might solve this issue as well.
by "bigger" I mean using a 600px image link.

**Closed** 2017-10-08 10:41 UTC
Labels: bug, enhancement, Low
