### ISSUE TITLE
Simplify long imported tracks using Douglas–Peucker 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#351] opened 2017-05-26 17:58 UTC
Which file were you referring to?

**Comment by HarelM** [comment] 2017-05-26 18:01
Any large file that causes delay.

**Comment by valleyofdawn** [comment] 2017-05-26 18:25
[YamLeBatyam.gpx.txt](https://github.com/IsraelHikingMap/Site/files/1032686/YamLeBatyam.gpx.txt)

**Comment by HarelM** [comment] 2017-05-26 19:08
Thanks! I'll take care of it when I'm done with angular migration.

**Comment by HarelM** [comment] 2017-05-31 08:55
D-P algorithm is available in Net topology suite framework which the server is already using, should be a one liner code change.

**Comment by HarelM** [comment] 2017-06-24 09:20
This issue collides with #331 .
I think the current issue is more important than #331 as it creates a bad user experience.
@valleyofdawn @moshfeu Can you help me reconcile this collision?
I don't have a good idea how to support both issue, mainly UX-wise.
The only thing that comes to mind is that if the recording has more than say 300 points then we'll run the D-P algorithm when loading the file which will reduce the number of points, otherwise we won't.
What do you think?

**Comment by moshfeu** [comment] 2017-11-15 14:27
I think that we can let the user to decide if he wants to use advanced edit. We can warn him that it may slow down his computer (in mobile we can't allow it, I think) and he can decide if he wants this.
If the user choose to continue, we will send the server a flag so it will know if he needs to use the algorithm or not.

**Comment by HarelM** [comment] 2017-11-16 23:05
Simplification algorithm (D-P) exists in the client side as well (within leaflet), so no need for extra call to the server.
I tend to go with a popup after the user selects a file to open in case of too many points.
The pop will ask the user whether to simplify the route or not.
 @valleyofdawn, @moshfeu, what do you think?

**Comment by HarelM** [comment] 2017-11-17 17:32
I've retested the file and on chrome it seems to work reasonably well, on firefox a bit less good but still reasonable.
We can open an issue for either firefox or leaflet for performace, but I doubt it will be fixed.

**Comment by zstadler** [comment] 2017-11-17 22:49
I believe the simplification is also decreasing the performance of the site.

For example:
Opening the [GPX file of Israel Trail](http://hiking.waymarkedtrails.org/api/details/relation/282071/gpx) and simplifying it takes 14 seconds, including a few seconds of a "Not Responding" browser.
Opening the Israel Trail from the search results, which does not simplification it, takes 5 seconds.

**Comment by HarelM** [comment] 2017-11-17 23:27
In both cases simplification is not preformed right now.
The difference of a simplified route is that the site will be less "sluggish" once the loading is complete, in theory.
Having said that, simplifying means loosing user data which I think is worse than a sluggish route manipulation.
I'm leaning towards closing this issue.

**Comment by zstadler** [comment] 2017-11-18 18:52
> In both cases simplification is not preformed right now.

If so, what is the cause of this significant difference in performance?

**Comment by HarelM** [comment] 2017-11-18 19:12
Different flows, file upload etc...

**Comment by zstadler** [comment] 2017-11-18 20:34
I don't think so. The long operation has lots of GCs

**Comment by HarelM** [comment] 2017-11-18 22:07
I'm not sure what are you proposing or where this discussion is going to.
If you have insights about how the code is working and what bottle necks you've seen while debugging it please share them.
If you are not sure about something and would like some more insights I'll be happy to check and help.
Your last statement is neither as far as I could understand, I might have missunderstood it though.

**Comment by zstadler** [comment] 2017-11-19 10:11
![image](https://user-images.githubusercontent.com/1304610/32989630-a4087780-cd22-11e7-9829-014bf722214b.png)

**Comment by HarelM** [comment] 2017-12-16 18:13
Haven't found anything out of the ordinary.
Closing...

**Closed by HarelM** 2017-12-16 18:13 UTC
Labels: bug, enhancement, Medium
