### ISSUE TITLE
Incomplete scroll when adding a new POI

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#604] opened 2018-01-17 08:56 UTC
When POI is close to the top of the screen

<img width="273" alt="2018-01-17 10_53_48-israel hiking map" src="https://user-images.githubusercontent.com/1304610/35033932-174c8404-fb75-11e7-85a5-c5ca577895d0.png">

**Comment by HarelM** [comment] 2018-01-17 10:26
This is by design as centering the dialog causes other issues, especially on mobile devices.

**Comment by HarelM** [comment] 2018-01-17 10:33
Maybe I can do it only for private POIs read-only mode...

**Comment by zstadler** [comment] 2018-01-17 11:20
Please elaborate on the other problems caused by a scroll.

If complete scroll is not possible, then it is better not to scroll at all. Currently, there is a partial scroll which feels like a bug.

**Comment by HarelM** [comment] 2018-01-17 11:24
My bad, I misunderstood the issue. There is a partial scroll due to the fact that the DOM is updated using angular after leaflet scrolls to the popup. I'm not sure I'll be able to fix this due to framework responsibilities collision.
I can disable the scroll.

**Comment by zstadler** [comment] 2018-01-17 11:32
Disabling the scroll is a better, but still a bad option.

Can you update the DOM before the Leaflet scroll or induce another scroll after the DOM is updated?

P.S., I assume the "DOM update" is creating the dialog. Right?

**Comment by HarelM** [comment] 2018-01-17 11:36
The "DOM update" just insert the content of the popup to the popup - this is why you have a partial scroll.
I'll see what I can do in order to overcome this, I agree that no panning is not the best solution...

**Comment by HarelM** [comment] 2018-01-18 18:45
Closing this in favor of #614 - there are too many bugs in this area.

**Closed by HarelM** 2018-01-18 18:45 UTC
