### ISSUE TITLE
Hanita Singletrack is not found

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#676] opened 2018-04-11 20:23 UTC
## Bug

Although the Hanita Singletrack ("סינגל חניתה") has an [OSM relation](https://www.openstreetmap.org/relation/7560653) and an [e-yarok page](http://www.eyarok.org.il/bike/trip.aspx?id=2755), it does not show in bike routes layer or in the search results.

This issue may be related to #501 and the "Merge KKL e-yarok and OSM MTB routes" part of #675. If off-road fails to extract a KKL single, it will not show on the Israel Hiking site despite the fact that it is included in the OSM data.

**Comment by HarelM** [comment] 2018-04-11 21:03
Seems like a duplicate of item 3 in #675. and it is due to #501. 
I think it will be better to either remove item 3 and place it here or close this issue.
Your call...

**Comment by zstadler** [comment] 2018-04-12 07:17
### Item 3 of #675 moved here:

- [ ] **Merge KKL e-yarok and OSM MTB routes**
  A good principle of the POI merge algorithm is that the geographic information is taken from the OSM data. It avoids unnecessary misalignment between objects and the underlying map. 

  The merge algorithm and this principle should also be applied to KKL e-yarok and OSM MTB routes such that the route geometry will be taken from OSM. This will avoid mismatches such as

  ![image](https://user-images.githubusercontent.com/1304610/38625631-90771742-3db3-11e8-8461-ae93fc8bb7b0.png)

  The information in the side panel should continue to be taken from KKL's e-yarok site. 

  Matching of KKL e-yarok MTB routes with OSM MTB relations can be done when either:
  1. The OSM relation's tags include the URL of the e-yarok route
  2. Their names match and the center of the two geometries are within 1km

**Closed** 2018-04-13 19:16 UTC
Labels: Medium, bug, enhancement

**Comment by zstadler** [comment] 2018-04-14 08:30
The singletrack is found. However, there is no icon for KKL's e-Yarok site although there is a `website` tag with a link to it.

![image](https://user-images.githubusercontent.com/1304610/38765890-7183db2e-3fd2-11e8-94c4-9964c83c4a5e.png)

There is no description because off-raod did not extract this singltrack from e-yarok. Ideally, the description would be taken directly from the e-yarok site rather as an alternative to off-road's extraction.

**Comment by HarelM** [comment] 2018-04-14 09:03
Taking the description from e-yarok site requires crawling, which is a big effort.
Currently website field is not parsed in order to get the relevant icon.
In the example above, the link to off-road is not a link to a e-yarok page but a route from a user, I think.
I'm not sure how to proceed here, feel free to reopen and suggest what should be the next step to solve this issue.
