### ISSUE TITLE
specific route fails to load in iOS

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#573] opened 2017-12-09 17:27 UTC
## What I expect to happen
Route to load

## What really happened
IHM loads but instead of loading the route an error message appears: "לא ניתן לפתוח את הקישור"

## What I did that caused the issue - step by step
https://israelhiking.osm.org.il/#!/?s=wUWSCG7Nyk

## My environment
iPhone SE, iOS 11.1.2
Safari (but also fails in built-in browsers such as inside the the facebook app)

## Thing I think the developers should know, images, links etc.
Route loads fine on Windows.
I'm wild-guessing it has something to do with the route title / description.

**Comment by HarelM** [comment] 2017-12-09 18:20
I have limited capabilities to test iOS. Can you check what happens if the description and the route length are short?
Also safari is just horrible so I can image it won't support some of the things.
Had this link worked before the last update?

**Comment by oriori** [comment] 2017-12-09 18:26
It's a new link and it's not my route but I think older routes from this user also failed to load before the update.
I'll test the text and route length.

**Comment by oriori** [comment] 2017-12-09 19:28
After a lot of testing, I found out that the problem is actually with the layers. If any layer is turned on while sharing, the route will fail to load correctly. If no layer is turned on, there's no problem loading the route. Regardless of shared routes, there's no problem turning layers on and off under iOS.
Also, I realized that when it fails to load the route correctly, the route does actually load, it's simply that the site gives the error message and doesn't re center the map around the route.

**Comment by HarelM** [comment] 2017-12-09 19:35
I'm sure I understand your definition for layers.
Can you define a short scenario with simple steps to reproduce?

**Comment by oriori** [comment] 2017-12-09 19:42
![image](https://user-images.githubusercontent.com/8708384/33798899-cbc868fe-dd29-11e7-9f4c-ed62cad8d1dd.png)
Turn on "שבילים מסומנים" before sharing the route.

**Comment by HarelM** [comment] 2017-12-09 19:47
I'll see what I can do, but since I can't debug iOS devices I have little faith I'll be able to solve this...

**Comment by HarelM** [comment] 2017-12-16 17:55
@oriori I just tried this with an iPad and was able to see the route correctly.
So I'm not sure how to proceed.
If you have a way to connect to the device and perform a remote debug or something and send me the error message that is received in the browser I might be able to help out...

**Comment by oriori** [comment] 2017-12-16 18:27
I’ll see what I can do.

**Comment by MatanBenMoshe** [comment] 2017-12-20 21:10
Hi,

It's the same issue we talked about. I see the message "לא ניתן לפתוח את הקישור" also on **my PC** using **chrome**.
I tried it also in different devices and I can reproduce it consistently.
It happens just for new links!
You can take for example this link: https://israelhiking.osm.org.il/#!/?s=RmRzHY72h1

![image](https://user-images.githubusercontent.com/17752588/34228808-b4af8fee-e5da-11e7-8f26-9c4bbc39fc4e.png)

**Comment by MatanBenMoshe** [comment] 2017-12-20 21:14
Using F12 I can see this error (don't know if it helps...):
siteSettings.js:23 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google-analytics.com https://*.gingersoftware.com". Either the 'unsafe-inline' keyword, a hash ('sha256-3Nd4++ZPd6rEQBIhUR1KptydrN90shck9sL9RCpSb04='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by zstadler** [comment] 2017-12-20 21:16
Could it be an issue with the internet speed/bandwidth/timeout?
I also see that some tiles are missing in the screenshot.

**Comment by HarelM** [comment] 2017-12-20 21:26
I just tried with Win 10 FF and chrome, android with chrome and all have managed to present the route.
Also the error you wrote has to do with this, I think:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script
Which I have no clue how it is related to the site - might be some security settings you might have?

**Comment by MatanBenMoshe** [comment] 2017-12-20 21:29
It's a PC  from work and it has some extra security programs...
But I tried it also with my private PC and see the same problem...
I don't think it's related to internet speed, I saw it also on work using very high internet speed.

**Comment by HarelM** [comment] 2017-12-20 21:37
Can you check the network tab for http errors? it might shed some light depending on the error code...

**Comment by oriori** [comment] 2017-12-20 21:47
Matan's link fails to open correctly on my iPhone as well. No problem with
Chrome on Windows.

**Comment by MatanBenMoshe** [comment] 2017-12-20 22:01
It's the only thing I see and maybe interesting:
null | 404 | text/html | platform-browser.js:2949 | 1.9 KB | 1.06
-- | -- | -- | -- | -- | --

**Comment by HarelM** [comment] 2017-12-20 22:22
Unfortunately this null is due to image fetching for an image named null, I have fixed it but have yet to publish it... :-/

**Comment by MatanBenMoshe** [comment] 2017-12-21 07:59
Let me know if I can help somehow...

**Comment by HarelM** [comment] 2018-01-24 23:12
@MatanBenMoshe @oriori I have published a fix to #622 which seems similar to this issue.
Can you please check if this was resolved as well?

**Comment by oriori** [comment] 2018-01-25 07:53
Resolved on my iphone.

**Comment by MatanBenMoshe** [comment] 2018-01-25 15:42
Looks good now! You can close it.
Thanks!

**Comment by HarelM** [comment] 2018-01-25 15:53
Yay!

**Closed by HarelM** 2018-01-25 15:53 UTC
Labels: High, bug, help wanted
