### ISSUE TITLE
map rotates when trying to drag the focus into other part of it

### ISSUE THREAD

**Issue by tiulimg** [IsraelHikingMap/Site#1249] opened 2020-06-19 14:15 UTC
## Bug
(Delete the non-relevant)

## What I expect to happen
When I press and hold, somewhere in the map, then I move the mouse, I expect the map to drag, not to rotate.

## What really happened
Sometimes the map drags, sometimes it rotates. If it's not a bug it's a bad user experience for sure..

## What I did that caused the issue - step by step
I press and hold the mouse on some point on the map
Then I move the mouse without releasing the hold. 
Sometimes the map drags, sometimes it rotates.

## My environment
* Operating System and version: Windows 10
* Web Browser and version: Chrome 83

**Comment by HarelM** [comment] 2020-06-19 17:48
Thanks for taking the time to report this issue!
Are you sure you are not pressing the CTRL button when the map rotates?
I can't seem to be able to reproduce this behavior on my PC unfortunately... :-(
Is it reproducible easily?
Can you check if you can reproduce it on another machine as well?
If you can send a video of it it would help a lot...

**Comment by tiulimg** [comment] 2020-06-21 00:16
Yes, it happens also without holding Ctrl. reproducible easily..
I can't reproduce it on another machine that I have. (same chrome version, another windows build. both 10, mine is 1803 and the other machine 1903)

It happens also on incognito, Edge 42, Firefox 77.
video:
https://streamable.com/2wurjt

**Comment by HarelM** [comment] 2020-06-21 05:01
Thanks for the video! I guess the green circle indicates a long press?
Can you please check if you can reproduce this using the following example?
https://docs.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/
If so, can you make a video using this example as well?
This is the Mapbox map infrastructure we are using and I would like to know if the problem is with the code I wrote or exists in the library.
I haven't seen this happening on any machine I've used so I'm inclined to say that this is a bug is the version of windows you are using, but I honestly don't know what can cause this...

**Comment by zstadler** [comment] 2020-06-21 05:12
I had a similar experience with the app. Without ant special action on my part, suddenly a single-finger touch drag made the map rotate rather than pan. Cleaning the touch screen did not help. Exiting and re-entering the all solved the problem.

**Comment by HarelM** [comment] 2020-06-23 14:47
Closing this issue for now as I don't see a way to reproduce it or better understand the root cause.
I suggest to see if the above link to the example is showing the same behavior, if so I suggest to open an issue in mapbox-gl repository and continue to follow there.

**Closed** 2020-06-23 14:47 UTC
