### ISSUE TITLE
Incorrect calculation of altitude

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1413] opened 2020-12-28 08:19 UTC
## What I expect to happen
correct altitude calculation. 

## What really happened
I ran downhill 11 km and the altitude calculation shows a climb of 800 meters and a descent of a thousand meters.
I record the track in the app. 

## What I did that caused the issue - step by step
Open the link. 
See incorrect altitude calculation. 

## My environment
* Operating System and version:
* Web Browser and version:

## Things I think the developers should know, images, links etc.
https://israelhiking.osm.org.il/share/VfV365iSxl

**Comment by HarelM** [comment] 2020-12-28 08:38
Height calculation is problematic.
See the discussion here:
https://www.facebook.com/groups/israelhikingmap/permalink/3014479188607254

**Comment by amiad** [comment] 2020-12-28 19:37
I uploaded [my partner's record ](https://israelhiking.osm.org.il/share/RpuRKzisfx) and the calculation is correct.
He used Garmin with auto sync to MapMyRun.

Maybe the problem with recording of the app is that imported files are displayed correctly.

**Comment by HarelM** [comment] 2020-12-28 20:28
The app gets the height from the GPS. It's easy to see that your devices added a lot of unwanted artifacts to the height chart while the Gramin device has either better GPS that has more accurate height or the MapMyRun application removes the height from the GPS and uses some sort of DEM.
DEM is available only on the server so this is not a good options is most cases and in general we try not to change data that was recorded - hence the poor height graph.
In any case, height recording is not something the you should trust. And if you want to see a proper height graph just plan a route...

**Comment by amiad** [comment] 2020-12-29 17:19
I downloaded the file and I uploaded its to [trackreport](https://www.trackreport.net). I got correct data.
![Screenshot_2020-12-29 GPX report generator](https://user-images.githubusercontent.com/402108/103301555-56b89d80-4a0a-11eb-98a7-17124a4373b4.png)

I uploaded to [maplorer](https://maplorer.com/view_gpx.html) and I got correct data too.
![Screenshot_2020-12-29 MAPLORER GPX view Elevation Google Maps](https://user-images.githubusercontent.com/402108/103301755-b0b96300-4a0a-11eb-8e23-320eb3af7902.png)

Of course it is also possible to repair on IHM.

**Comment by HarelM** [comment] 2020-12-29 18:42
Every site calculates this differently.
Here's the code from this site:
https://github.com/IsraelHikingMap/Site/blob/4e479a5a92051ae5ec84136ca8c20547a4d11f26/IsraelHiking.Web/sources/application/services/route-statistics.service.ts#L87
I don't see a good reason to change it...
Feel free to submit a pull request if you do.

**Comment by zstadler** [comment] 2021-01-01 16:00
As @HarelM pointed-out, the height graph has a lot of artifact "spikes"

![image](https://user-images.githubusercontent.com/1304610/103441758-ab515800-4c58-11eb-850e-042eb747d587.png)

Prior to calculating the gain and loss, the code performs a simplification  to the curve

https://github.com/IsraelHikingMap/Site/blob/4e479a5a92051ae5ec84136ca8c20547a4d11f26/IsraelHiking.Web/sources/application/services/route-statistics.service.ts#L85

[That simplification](http://mourner.github.io/simplify-js/) uses a combination of [Douglas-Peucker](http://en.wikipedia.org/wiki/Ramer-Douglas-Peucker_algorithm) and Radial Distance algorithms. The Douglas-Peucker algorithm tends to preserve such spikes because of their relative distance from nearby points.

The [Visvalingam-Whyatt](https://en.wikipedia.org/wiki/Visvalingam-Whyatt_algorithm) algorithm uses area rather than distance for simplification, and it _**may**_ produce a smoother graph. Unfortunately, I will not be able to experiment with the [Javascript implementaion](http://bost.ocks.org/mike/simplify/simplify.js) of the algorithm.

Source: [StackOverflow](https://stackoverflow.com/a/12027097/368683)

**Comment by zstadler** [comment] 2021-01-02 06:09
@amiad,
You may also experiment with eliminating nodes with absolute vertical velocity higher than some constant, such as 2 m/s.

**Comment by HarelM** [comment] 2021-01-09 14:30
Feel free to submit a pull request, I see very little value in fixing the height calculation when the height profile is so noisy...
I couldn't find a npm package that implements the suggested "new" simplification and hence I believe it is not widely used. Beside this, I have no confirmation that it will actually solve this issue...
I'll be closing this issue now, In case a PR will arrive I'll re-open it.

**Comment by migolan** [comment] 2021-07-07 03:15
To understand where our problem lies, I took 3 gpx files of the route from Har Amasa to Tel Arad:

* [recorded by phone](https://israelhiking.osm.org.il/share/VfV365iSxl)
* [recorded using Garmin](https://israelhiking.osm.org.il/share/RpuRKzisfx)
* [planned on IHM](https://israelhiking.osm.org.il/share/3qG8ti4xIg)

I uploaded each one to 4 websites to compute the total climb/descent:

- [trackreport](https://www.trackreport.net)
- [maplorer](https://maplorer.com/view_gpx.html)
- [gps visulalizer](https://www.gpsvisualizer.com/profile_input) (without changing default parameters)
- [IHM](https://israelhiking.osm.org.il)

Here are the results:

<html>
<body>
<google-sheets-html-origin>

har amasa to tel arad | total climb/total descent in meters |   |   |  
-- | -- | -- | -- | --
  | trackreport | maplorer | gpsvisualizer | ihm
phone recording | 276/-574 | 1179/-1477 | 1179/-1477 | 784/-1080
garmin recording | 99/-412 | 120/-431 | 120/-431 | 86/-397
ihm planned | 103/-415 | 118/-428 | 118/-428 | 84/-394


</body>
</html>

Seems that the problem isn't in computing total climb/descent on planned routes, but when altitude has measurement errors.

**Comment by HarelM** [comment] 2021-07-07 10:24
@migolan thanks for the detailed research!!
@amiad please let me know if this is also your understanding of the issue, in that case we should focus on "noise reduction".
I'll reopen this issue to facilitate for a discussion and hopefully a fix at the end.

**Comment by amiad** [comment] 2021-07-07 15:24
Yes, the problem is probably with the sudden jumps. See the graph:
![Screenshot 2021-07-07 at 18-19-58 Israel Hiking Map](https://user-images.githubusercontent.com/402108/124786612-62e06300-df37-11eb-80e5-bff18443f626.png)

**Comment by migolan** [comment] 2021-07-19 18:22
I applied the [RDP](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) and [VW](https://en.wikipedia.org/wiki/Visvalingam%E2%80%93Whyatt_algorithm) polyline simplification algorithms on the 3 route files from Har Amasa to Tel Arad, with various horizontal stretch and algorithm parameter values.
(See the links for demonstration on how these algorithms work.)
The figures below show for every track file:
1. The original altitude profile
2. The altitude profile after RDP simplification, using the same parameters that are currently used on IHM for calculating total gain/loss (although, on IHM a radial distance algorithm is applied in addition, so the results aren't exactly the same as in IHM).
3. The altitude profile after VW simplification, using parameters that gave good results.

* One very important note is that calculating the total gain/elevation is affected by two factors - resolution of the data, and noise in the data. Obviously, on a planned route, or a route recorded using exact tools (e.g. Garmin), we'd have very little noise. We can see the noise added when recoding by phone in the figure below. The polyline simplification algorithms are designed for reducing polyline resolution, but from the figures we can see that the VW algorithm is pretty good in noise filtering too - a very refreshing approach for signal processing :)
* I used my own simplification for calculating the distance along route - my simplification results with ~12.4km vs around ~11.4km on track analysis websites, but this doesn't change the total gain/loss (not significantly anyway).

![bokeh_plot (3)](https://user-images.githubusercontent.com/41941445/126205304-26e10fef-91e4-454f-8fe7-e21b19b704e7.png)
![bokeh_plot (4)](https://user-images.githubusercontent.com/41941445/126205316-8fe9bc82-0f38-4acb-93a7-019fe14aa408.png)
![bokeh_plot (5)](https://user-images.githubusercontent.com/41941445/126205329-6350c140-1753-435e-8a83-78d09f8750e1.png)

Additional reading about track simplification & total gain/loss calculation:
https://www.gpsvisualizer.com/tutorials/elevation_gain.html
https://bost.ocks.org/mike/simplify/
https://www.gpsvisualizer.com/tutorials/track_filters.html

@HarelM @zstadler @amiad

**Comment by HarelM** [comment] 2021-07-19 18:42
These are very interesting results! Thanks for the research!!
Looking at the phone simplification it seems like VW has very good results, but in the IHM planning it seems (to me) a bit too simplified.

RDP doesn't seem like a good fit in general as its purpose is to keep the line as close to the original in term if how it looks which in case of spikes and noise is the opposite of what we want.

The question is, if there's another algorithm for eliminating noise (spikes) that's worth trying here?

**Comment by migolan** [comment] 2021-07-19 19:29
Here are two more figures that show the effect of the stretch and algorithm parameter values on the total gain: we can see here that using the RDP algorithm, the stretch has little effect on the result (because it's actually designed to preserve the spikes, and if we get a result which is close to the truth, it's just by coincidence); and in the VW algorithm, any result achieved by stretching can be achieved by changing the algorithm parameter.
I have a few more route examples which I want to test the VW on and maybe see if other parameter values get better results, and also try to think which values make sense.
![image](https://user-images.githubusercontent.com/41941445/126214834-36985029-5703-4479-b2a9-b328f32adc21.png)
![image](https://user-images.githubusercontent.com/41941445/126214879-ff870536-7f4b-40ed-b3a1-2fbd2a149d07.png)

Anyway, indeed we don't have a line simplification problem because in the garmin & planned route cases, the current RDP gave pretty good results. So if we're looking at noise reduction, I can try a few things and see how easy or hard this problem is. Maybe applying some median filter as a start.

**Comment by HarelM** [comment] 2021-07-19 19:39
Cool! Median filter would be interesting to see compared to VW... :-)

**Comment by zstadler** [comment] 2021-07-20 11:16
Hi @migolan,
It was a real pleasure to read your analysis!

When looking into the behavior of a median filter, please note that while GPS recordings usually have a fixed 1 point/second rate, the distance between points in a planned route can vary significantly depending on the original mapper's patience. Users may also upload and view the height graph for routes/recordings that had gone through some simplification which changed the point density along the path.

Perhaps the "window" of the median filter should be defined in terms of the total length of the "segment under investigation" rather than the usual "fixed number of sample points" approach.

**Comment by migolan** [comment] 2021-07-23 13:04
For the median filter, I first resampled the data to uniform resolution using linear interpolation.
I experimented with several resampling resolutions and median filter window sizes, and added two more tracks of the Havar crack hiking route to the analysis - one recorded, and one planned on IHM (so it doesn't have altitude measurement errors, but instead suffers from route displacement in a very steep terrain area).

Final conclusions will come later, but you're welcome to review the analysis & figures here: https://github.com/migolan/route_analysis
(have to download and run the notebook because it uses interactive bokeh plots)

**Comment by migolan** [comment] 2021-08-08 18:04
Here are some results for the median filter:

The median filter provides a much smoother altitude profile, compared to the VW algorithm:
![pasted image 0](https://user-images.githubusercontent.com/41941445/128640931-5c2d6a0a-4a99-45e2-809f-01dfd3738b86.png)
These parameters were chosen for the median filter, because they minimize route deviation due to noise, for example in the following figures (we can see that these deviations in the recorded routes are due to noise by comparing to the planned route):
<img src="https://user-images.githubusercontent.com/41941445/128640943-5e588155-e132-475d-87ce-74bb0d6a5f7d.png" width="300">
<img src="https://user-images.githubusercontent.com/41941445/128640945-0c1b95b4-8278-4958-8ec0-a48ad6d70ef1.png" width="300">
According to Google Maps, the true total gain/loss for this route are 87m/-377m, and the median filter results with close values for all 3 track files.

Good results are achieved for the Havar crack route as well:
![pasted image 0 (1)](https://user-images.githubusercontent.com/41941445/128640958-0a831eda-0538-4e86-99f4-15a60c00f67d.png)
According to Google Maps, the true total gain/loss for this route is around 280m, which is achieved for both track files using the median filter with the selected parameters.

If you'd like, I can gather more recorded routes from users (or from you, if you have any) and check how the median filter performs on them vs a planned route, or we can proceed to js implementation.
What do you think?
@HarelM @zstadler

**Comment by HarelM** [comment] 2021-08-08 19:52
This is a great analysis! Thanks!!
I think there results are good enough to proceed with the implementation. We can always revisit this in the future if we find that the algorithm needs improvements. Once this is in place in the site we can ask people to try it out and get more data.
Let's proceed.

**Comment by HarelM** [comment] 2021-08-11 16:04
@migolan I would like to publish a new version in the next days-week and it would be extremely cool if this feature would be in that version.
Please let me know if this timeline is possible for you.
Thanks again for all the hard work!!!

**Comment by migolan** [comment] 2021-08-11 16:25
Yes! I believe that by Sunday I can get something going. Find a moving median package on npm, now looking for something to do the linear resampling (if you know of any such package).

**Comment by HarelM** [comment] 2021-08-11 18:08
Or maybe that:
https://bl.ocks.org/mlunacek/2f57ab31dfdea873f9c8a6fa252208a2
Try googling "d3 resample" and see what you get...
d3 is already used in the site so this is a good direction I guess :-)

**Closed** 2021-08-20 19:05 UTC
Labels: enhancement, Low
