### ISSUE TITLE
Change the color of the track according to the slope

### ISSUE THREAD

**Issue by dovgazit** [IsraelHikingMap/Site#1337] opened 2020-10-24 14:12 UTC
Request change / improvement shows route line.

View of the route according to the change in altitude.  This nice option exists in the Oruxmap app.  Gives a view and trends in the route while navigating.  Navigate before ascending or descending without opening the altitude graph.

**Comment by HarelM** [comment] 2020-10-24 14:21
This might help in the implantation:
https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/

**Comment by dovgazit** [comment] 2020-10-25 05:55
True, this is the general idea.  A perusal of the code shows that the treatment discusses only from a flat blue state to a red rise, 5 color degrees.  Recommends dealing with declines as well.

**Comment by zstadler** [comment] 2020-10-25 12:22
AFAIK, in Oruxmaps, the color is associated with the slope of the trail, not the height.

**Comment by dovgazit** [comment] 2020-10-25 20:00
True, the color is associated with the rate of climb or slope

**Comment by HarelM** [comment] 2020-11-01 06:37
Seems like the infrastructure doesn't support this yet. Maybe in the future it will be supported but right now it's not possible.
See:
https://github.com/mapbox/mapbox-gl-js/issues/8977
I'll be closing this and monitor the other thread...
Sorry....

**Comment by HarelM** [comment] 2020-12-20 12:52
Seems like there's a solution in that thread that I need to check.
Reopening...

**Comment by HarelM** [comment] 2021-03-29 18:59
The concept of the solution in the above thread is the following:
1. Create a very large dictionary of colors and distance where the distance is between 0 (beginning of the line) to 1 (end of the line).
2. This dictionary is then placed inside the gradient line progress layer to basically map every location in the line to a different color - thus creating the required effect...

This is an interesting hack to this issue...

**Comment by HarelM** [comment] 2021-03-30 12:52
I managed to do the following as a POC to present the **height** of the route using colors:
![image](https://user-images.githubusercontent.com/3269297/112990874-34e8c700-916f-11eb-848b-e69e923e78b0.png)
I'm still not clear how to convert slope values into colors - i.e. what is considered the maximal slope? 100%? what is the minimal slope? -100%? Slope can get weird values if looking at the slope chart in the site so I'm not sure how valuable this would be... :-( 
What color should be for no slope (0%)? green? downhill - blue? uphill red?
If you have some suggestions it would be great...

**Comment by HarelM** [comment] 2021-04-01 20:23
Ok, moved the code to the right place, added color according to slope.
Here's an example of the coloring I chose: red for uphill, blue for downhill, green for plato (kinda):
https://israelhiking.osm.org.il/map/15.11/32.2538/35.3325
![image](https://user-images.githubusercontent.com/3269297/113346548-a88bff00-933c-11eb-9606-e91900affa7f.png)

But since I don't have a scale for the slope the following could happen:
![image](https://user-images.githubusercontent.com/3269297/113349332-88f6d580-9340-11eb-9a5d-d75969c63d40.png)
https://israelhiking.osm.org.il/map/16.10/32.3644/34.8566

Since this would be available for advanced users only by clicking the slope chart I hope they would be wise enough study it...

@valleyofdawn

**Comment by HarelM** [comment] 2021-04-01 20:35
Moving to awaiting info for further discussion, I can upload it to the website only if you would like to play with it before releasing to the application stores.
Let me know...

**Comment by HarelM** [comment] 2021-04-02 12:01
Feedback summary:
Slope should be between 25% and -40% and the chart should be scaled accordingly. blue would be -40%, green would be 0%, yellow would be 10% and red will be 25%.

**Closed** 2021-04-02 12:37 UTC
Labels: Low, enhancement, important

**Comment by zstadler** [comment] 2021-04-03 10:04
<div dir="rtl">
אם מפעילים את הצביעה לפי שיפוע היא נעלמת כשיוצאים וחוזרים לאפליקציה. לדעתי עדיף שהבחירה תישמר יחד איתה.
<br><br>

לדעתי כדאי שישמר גם המצב המפורט של הסטטיסטיקה: 
1. מוסתרת/מצומצמת/גרף/טבלה
2. נ"צ לק"ם

**Comment by dovgazit** [comment] 2021-04-11 09:15
Recommends improving color resolution and using more than four colors. I enclose a picture of the shades and gradients used by the OruxMaps app.

Attaches a link to 3 photos of routes - https://photos.app.goo.gl/DYf7BuDNtDinVXKg6
One of the Tel Aviv promenades is all green and it is indeed normal, there are no significant slopes at all.
The ascent route in "northern Cesalon, which already has a more significant slope but looks rather greenish.
Compared to the same track (Cesalon) in the third image in the Oruxmaps apps, the track looks more yellow-orange

![OruxColor](https://user-images.githubusercontent.com/43773740/114298543-8f631b00-9abf-11eb-980b-2eefdca281c0.jpg)

**Comment by HarelM** [comment] 2021-04-11 09:23
@valleyofdawn please advise.
In our last conversation you mentioned that the slopes should be between -15% and 15% and that green should be 0%, yellow 5%, red 15% and blue -15%. If you think the scale above is better please approve.

@zstadler Application state related to the chart is not part of this issue and needs a discussion as I'm not sure I agree with you...

**Comment by dovgazit** [comment] 2021-04-13 03:57
The colors cover the directional arrows, was nice with it possible to combine arrows and colors

**Comment by HarelM** [comment] 2021-04-13 05:32
Placing the arrows on top of the coloring will hide the color and it is not possible to make the arrows themselfs with the right color so I don't see how this is possible...

**Comment by dovgazit** [comment] 2021-04-13 05:53
Maybe as attached
![WhatsApp Image 2021-04-13 at 08 50 55](https://user-images.githubusercontent.com/43773740/114503200-97dd6200-9c35-11eb-9d89-e3e237add004.jpeg)

**Comment by HarelM** [comment] 2021-04-13 08:47
This seems a bit too much for me in terms of copying...
I think I'll keep it the way it is now to avoid infringing any copyright laws...

**Comment by michaelmbr** [comment] 2021-04-19 07:23
First, I want to thank Harel for producing this exceptional app. It is the best hiking planner. 
I want to add my two cents on the slope color code. 
Since the +15 -15 deg slope color code was rolled out, the **actual** slope for steeper inclinations has not only gone missing but is also now impossible to obtain. It is not only a grievance - it can also be dangerous. A biker might not be able to brake. A hiker may want to plan routes that avoid very steep climbs or descents.
At the moment I am solving "for myself" by using a previous APK downloaded from https://apkpure.com/israel-hiking-map/il.org.osm.israelhiking/versions in my phone, but IMO the feature should be rolled back until a way to display **real** data is found. Those are just a few suggestions
1 - It should be trivial to offer it as an optional layer.
2 - The color code could be calculated according to the tracks' higher and lower inclination values instead of hard coded.
3 - It could be added for bike planning only.
4 - It could be shown only if selecting an area of the slope graph.

ETC.

**Comment by dovgazit** [comment] 2021-04-19 08:32
Repay to michaelmbr:
_I'm on  Ver. 9.8.32_
1. The slope color is optional on "Slope Graph",  In my opinion, there is no need for a new layer, optional in the graph of heights and statistics is OK.

2. Not sure I understood paragraph 2, but in my opinion, the calculation should be according to the percentage of slope. If you climb 2% over a long distance the color should still be green. If you climb 15% to 50 meters I would expect a red color. It is true that distance also has value but in my opinion, it is more difficult to calculate. This can be seen in the graph itself and not in the colors.

3. Once the colors are an **optional matter**, they can be turned on and off for both pedestrians and motorized vehicles why only for bicycles?

4. Why? I would like to see it on the whole track and not just on a selected segment. The colors on the whole track give a general reference to the color of the track.

Last Saturday I rode (on a motorcycle) the [attached track](https://israelhiking.osm.org.il/share/BWRYl37d1k), in my opinion, the colors reflect **superbly** the track.

**### Great app !!!**

**Comment by michaelmbr** [comment] 2021-04-19 10:07
> Repay to michaelmbr:
> _I'm on Ver. 9.8.32_
> 
> 1. The slope color is optional on "Slope Graph",  In my opinion, there is no need for a new layer, optional in the graph of heights and statistics is OK.

Nope. Slope colors are **always** shown when slope is selected, and **always** disappear when slope is de-selected. I don't need them, but the point is not this. The point is to have real inclinations and not +-15 deg boundaries. 

> 2. Not sure I understood paragraph 2, but in my opinion, the calculation should be according to the percentage of slope. If you climb 2% over a long distance the color should still be green. If you climb 15% to 50 meters I would expect a red color. It is true that distance also has value but in my opinion, it is more difficult to calculate. This can be seen in the graph itself and not in the colors.

The slope in the attached pict is 30 deg, not 15 deg. The colors are not the issue, only to have the real values.

![image](https://user-images.githubusercontent.com/82799687/115217777-80f3af80-a10e-11eb-9e63-f12073da6add.png)


> 3. Once the colors are an **optional matter**, they can be turned on and off for both pedestrians and motorized vehicles why only for bicycles?

Generic idea. I want the real slopes back, don't care about the colors or layers.

> 4. Why? I would like to see it on the whole track and not just on a selected segment. The colors on the whole track give a general reference to the color of the track.

Inasmuch as the slope values are real and not fictional as now - I don't care.

> 
> Last Saturday I rode (on a motorcycle) the [attached track](https://israelhiking.osm.org.il/share/BWRYl37d1k), in my opinion, the colors reflect **superbly** the track.

The range of inclinations in your track falls within the +15 to -15 degrees, so it fits one instance only, where the inclinations are gentle, Refer to the first picture I attached. :)

![image](https://user-images.githubusercontent.com/82799687/115218305-168f3f00-a10f-11eb-8293-3edf0a9975c4.png)

> 
> **### Great app !!!**

It is not great, it is the best ! :)

**Comment by michaelmbr** [comment] 2021-04-19 10:10
> Repay to michaelmbr:
> _I'm on Ver. 9.8.32_
> 
> 1. The slope color is optional on "Slope Graph",  In my opinion, there is no need for a new layer, optional in the graph of heights and statistics is OK.
> 2. Not sure I understood paragraph 2, but in my opinion, the calculation should be according to the percentage of slope. If you climb 2% over a long distance the color should still be green. If you climb 15% to 50 meters I would expect a red color. It is true that distance also has value but in my opinion, it is more difficult to calculate. This can be seen in the graph itself and not in the colors.
> 3. Once the colors are an **optional matter**, they can be turned on and off for both pedestrians and motorized vehicles why only for bicycles?
> 4. Why? I would like to see it on the whole track and not just on a selected segment. The colors on the whole track give a general reference to the color of the track.
> 
> Last Saturday I rode (on a motorcycle) the [attached track](https://israelhiking.osm.org.il/share/BWRYl37d1k), in my opinion, the colors reflect **superbly** the track.
> 
> **### Great app !!!**

The whole idea is: never mind whatever system you guys decide for displaying inclinations, just make them **accurate** and not limited (and thus **false**) because of some arbitrary UI.

**Comment by michaelmbr** [comment] 2021-04-19 10:12
![image](https://user-images.githubusercontent.com/82799687/115220187-ed6fae00-a110-11eb-9c84-e63dd8434598.png)

**Comment by valleyofdawn** [comment] 2021-04-19 15:29
My 2 cents:
I don't use the slope feature nor the technicolor routes but the truncated slope graph feels like a bug
Ideally the slope graph should not have a cut-off at all.
Perhaps this can be achieved by using a lookup table for the colors which doesn't max out at 15% but assigns red to everything above it. (Sigmoid shsped)
15% is good for bicycles. Perhaps hikers need higher slopes.

**Comment by HarelM** [comment] 2021-04-20 07:25
Added a few changes: 
+-20 as max slope for coloring.
No cut of to slope chart but added minimum scale so that when the slope is low it will look that way in the chart
Added small arrows on the route to indicate direction.
I'll release it to the site soon so you could play with it and let me know if it cover your needs, if you approve the changes I'll release to the apps as well...

**Comment by HarelM** [comment] 2021-04-20 07:28
![image](https://user-images.githubusercontent.com/3269297/115355163-12245e00-a1c3-11eb-930a-549c13ed6c12.png)

**Comment by HarelM** [comment] 2021-04-20 08:51
I've published the changes to the site (only). Make sure you refresh the page before you test the feature.
Kindly let me know here if this is good enough or need to be improved.

**Comment by michaelmbr** [comment] 2021-04-20 09:25
Hi, it looks fine now, thanks for the fix ! 
A small side note: the slope graph is "symmetrical" ie, the "larger" offset (in the plus or minus inclination) is mirrored in the other side, which is not strictly necessary. It is not a bug, of course, but there is no need for symmetry IMO. :)
Do you have a time frame for the fix in the apk ?

**Comment by HarelM** [comment] 2021-04-20 09:28
I wanted the slope graph to appear in the middle, so it's more of a UI decision.
I'm guessing that I'll publish this and other fixes within a month, give or take...

**Comment by michaelmbr** [comment] 2021-04-20 10:00
Hi Harel, sure thing, I am sorry I even mentioned that :)
*מיכאל לוינגר - שרותי IT - **אם בי אר קומיוטק בע"מ*

***@***.*** ***@***.***>0542284055*

**Comment by HarelM** [comment] 2021-04-20 10:03
No worries :-)
