### ISSUE TITLE
System text size affects the appearance of App Icons

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1099] opened 2019-12-07 07:34 UTC
## Bug
System text size affects the appearance of Icons
## What I expect to happen
The icons to look the same regardless of System text size 

## What really happened
They shrink and grow.
This is a minor aesthetic problem but still

## What I did that caused the issue - step by step
Go to the Android settings and change the system text size to small on large
go back to the IHM app and watch the icons 
![image](https://user-images.githubusercontent.com/689201/70370829-c24a3d00-18d4-11ea-9893-d40ab11dcba0.png)
![image](https://user-images.githubusercontent.com/689201/70370830-cb3b0e80-18d4-11ea-8fd6-bdac333f2996.png)

**Comment by HarelM** [comment] 2019-12-07 07:47
Duplicate of #1070, any chance you can add the images to the other issue?

**Closed by HarelM** 2019-12-07 07:47 UTC
Labels: duplicate

**Comment by valleyofdawn** [comment] 2019-12-07 08:00
sure
