### ISSUE TITLE
Hide the "undo" button when in read-only mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#931] opened 2019-01-23 18:44 UTC
## What I expect to happen
The undo button to show only when in Route edit mode or POI create mode (terminology taken from #537)

## What really happened
Undo button is always visible in the beta and app

## Thing I think the developers should know, images, links etc.
![Current view](https://user-images.githubusercontent.com/1304610/51629097-6510fb80-1f4f-11e9-96dc-dbcc36adc744.png) vs. ![Beta view](https://user-images.githubusercontent.com/1304610/51629170-8eca2280-1f4f-11e9-9ab3-3448e31f779a.png)

**Comment by HarelM** [comment] 2019-01-23 18:52
This is by design.
I don't think you should be in edit mode in order to undo your actions.
Let's move all the discussion about the undo in a single issue to see that we cover all the cases: #922

**Comment by HarelM** [comment] 2019-01-28 21:23
Undo also works for adding and deleting a route, and also when opening a share to allow the user to retrieve lost data.
I don't see how the user will be able to benefit from that when the undo is visible only when editing a route.
I think this issue need to be closed.

**Comment by zstadler** [comment] 2019-02-09 05:18
We've discussed the option to add a "redo" button that will also help recovering from accidental press of the undo button.

**Comment by HarelM** [comment] 2019-05-04 16:12
Looking back at this again, I'm not in favor of adding another button to the main interface... I think the current UX is good enough. I'm tending towards closing this issue...

**Comment by valleyofdawn** [comment] 2019-05-05 06:12
Although "redo" is useful, I agree its not worth complicating the interface further.
I do think that after terminating a recording it should stay grayed out. It's not like an accidentally deleted  planned route segment that you can easily add back. Recordings should be untouchable.

**Comment by HarelM** [comment] 2019-05-05 09:02
When the recording is done the route is saved to "my traces". I don't think graying out the undo is necessary, moreover, private routes are treated the same - once a recording is done it is being converted to regular private route, for simplicity, I do not want to create another type of private route.
Closing as I think we are aligned.

**Closed by HarelM** 2019-05-05 09:02 UTC
Labels: Low, bug
