### ISSUE TITLE
Utilize the back button to close windows

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#850] opened 2018-10-11 20:34 UTC
## What I expect to happen
When a window (eg. maps, poi) is open within the app I expect the smartphone back button to close it.

## What really happened
It closes the entire app.

This behavior is at odds with the norm in mobile apps, and causes accidental closing of the app.

**Comment by HarelM** [comment] 2018-10-11 20:38
duplicate of #796.
Feel free to add data there. closing.

**Closed by HarelM** 2018-10-11 20:38 UTC
Labels: App, enhancement
