### ISSUE TITLE
App freezes on return to focus

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1033] opened 2019-05-15 08:13 UTC
## What I expect to happen
While recording a track on the app, closing the screen (to save energy) and returning after a while I expect the app to immediately show my position, the logged track and the map.

## What really happened
Sometimes, but not always, it shows the position I was when I closed the screen, the app is not responsive to any touch gesture or button press. 
After a few minutes, the app sometimes awakens, completes the missing track and goes on to function.

## What I did that caused the issue - step by step
Turned on current location, turned on recording, used the app for 1.5 hours (out of town but in areas with generally fair reception), intermittently closing and opening the screen. Observed the above phenomenon

## My environment
Xiaomi phone
Android
IHM vesrsion 8.0.301

This happened on previous versions (leaflet based) and previous phones.

## Thing I think the developers should know, images, links etc.
Currently this is not easily reproducible,
Ideas on how to document the bug and on possible conditions to trigger it are welcome.

**Comment by zstadler** [comment] 2019-05-15 11:01
I assume part of the delay is related to the updating of the recording line since the last time it was viewed.

If so, I'd like to suggest a few things:
1. When the recording is active in the background, the app will be activated once evey few minutes, and the recording will be updated
2. When the user brings the app to the foreground, it will immediately show the current location. The recording will start updating in the background will be shown on the screen after the update is completed.

P. S., activating the application every few second may also reduce occurances where the system terminates the app.

**Comment by HarelM** [comment] 2019-05-15 20:33
Debug version was sent. Unfortunately I don't think Cordova framework can do the suggestions above.
Let's see if we can get anything from the logs.

**Comment by HarelM** [comment] 2019-06-02 18:08
@valleyofdawn are you able to reproduce this with latest debug version?

**Comment by HarelM** [comment] 2019-07-08 15:40
@valleyofdawn I'm closing this issue. In case this happens again please reopen this issue.

**Comment by valleyofdawn** [comment] 2019-08-19 08:42
Happened again with the debug version and Cordova BG Geolocation.
Although the app didn't stop or crash and recording was continuous there was a slowdown whenever it returned to focus. It took longer and longer each time, the app was unresponsive for several seconds, then showed a remote location (with no location arrow) and than continued tracking. All the time the BG geolocation module kept beeping to indicate new location readings.
Attching log files.
[log_2019-08-17_07-39-56.890Z.txt](https://github.com/IsraelHikingMap/Site/files/3514899/log_2019-08-17_07-39-56.890Z.txt)
[2019-08-17_07-13-26.277_מסלול_2019-08-17.gpx.txt](https://github.com/IsraelHikingMap/Site/files/3514901/2019-08-17_07-13-26.277_._2019-08-17.gpx.txt)
[2019-08-17_06-31-34.387_מסלול_2019-08-17.csv.txt](https://github.com/IsraelHikingMap/Site/files/3514904/2019-08-17_06-31-34.387_._2019-08-17.csv.txt)

**Comment by HarelM** [comment] 2019-08-19 08:48
I wouldn't read much into it right now as we are talking about a debug version which is a lot slower than release version.
Let's continue monitoring the Cordova GB plugin and see if it meets our needs. If it does and we decide to buy it, then we can retest this on a release version which should handle this better...

**Comment by valleyofdawn** [comment] 2019-08-20 08:09
Tried it again this morning.
The movement to a different spot is probably because I was fiddling with the screen while the app was unresponsive.
Today I watched the screen first after 30 min of it being off - there was a 45 sec delay before it became responsive. I opened it again after another hour and it took it 1.5 min to wake up - so it's more than a minor inconvenience.
On the up side - recording was continuous so the new background recording module might be working after all.

**Comment by valleyofdawn** [comment] 2019-08-28 12:24
Have now been making sure to delete all existing routes before recording and stability has improved.
In the last 3 rides (longish ones) I only had one such issue after a long (24 min) stop.

**Comment by HarelM** [comment] 2019-09-14 17:10
@valleyofdawn does this still happens with the release version or can this issue be closed?

**Comment by valleyofdawn** [comment] 2019-09-14 17:34
It hasn't happened recently. I can try again with more challenging conditions, namely other open routes in the background.

**Comment by HarelM** [comment] 2019-09-28 11:48
I'm guessing this is due to the usage of the debug version.
Closing, please reopen if it happens again.

**Comment by valleyofdawn** [comment] 2019-10-21 19:01
It happened two more times. Took 2 or 2 minutes for the app to unfreeze.
My guess is that this is what causes the crashes when recording a track in the background.
It never happens when I'm recording in the foreground. 
It's more likely to happen the longer the recording is and the longer the app is in the background.

**Comment by HarelM** [comment] 2019-10-21 19:05
This is not helping at all.
Please send the logs and the time it happened so I can review it.

**Comment by valleyofdawn** [comment] 2019-10-22 10:17
No logs, this was done with the public beta since you said last time that:
"I'm guessing this is due to the usage of the debug version" and the asked " does this still happens with the release version?"
Should I install the debug version again? Does it have an up-to-date build? You couldn't find anything indicative clues in the log last time. It must be getting location updates while stalled since eventually (after up to 2 minutes) it catches up and starts functioning.

**Comment by HarelM** [comment] 2019-10-22 10:31
There's a report a problem button in the release app. There's no need for debug version anymore.
Please click it and add the attachment here along with a detailed description of what you did and when.

**Comment by valleyofdawn** [comment] 2019-10-22 12:03
I pressed it now but nothing happened. Am I supposed to get any feedback?

**Comment by HarelM** [comment] 2019-10-22 12:42
It might take a few seconds but then you should select the mail app you prefer.

**Comment by valleyofdawn** [comment] 2019-10-22 12:53
Nada. Should I change any app authorizations?

**Comment by HarelM** [comment] 2019-10-22 13:39
Doesn't work for me either. I'll try and find out way later tonight. Not related to this issue though...

**Comment by HarelM** [comment] 2019-10-22 19:29
I have opened a separate issue for this: #1077.
Please update the app tomorrow morning and try sending the report again.
It should create a file inside the IHM folder if nothing else happens and you should be able to send it here as a temporary solution...

**Comment by valleyofdawn** [comment] 2019-10-23 05:54
The reporting button works now.
Since I don't have the timestamps of when freezing and thawing happened I'll try to recreate the problem in tomorrow morning's ride and send a full report. If you want I can send the current log file too.

**Comment by HarelM** [comment] 2019-10-23 06:04
Let's wait for tomorrow then.

**Comment by valleyofdawn** [comment] 2019-10-24 13:02
Started recording at 6:55 this  morning (2019-10-24). Turned off the screen immediately.
Turned on the screen at 7:42.
The app was unresponsive, showed the IHM logo with the rotating dots (image 1), did not change for several minutes. Closed the screen, opened it several more times with the same results.
Turned the screen on again at 8:27. The map showed up and it told me the previous recording was disrupted (Image 2). Resumed the recording.
The rest of the recording went well.
Attaching relevant files.
![Screenshot_2019-10-24-07-42-01-131_il org osm israelhiking](https://user-images.githubusercontent.com/689201/67487910-74a4a880-f677-11e9-99e2-a2746b1ae6ed.png)
![Screenshot_2019-10-24-08-27-02-044_il org osm israelhiking](https://user-images.githubusercontent.com/689201/67487911-753d3f00-f677-11e9-837d-7b0e2fb2f7ec.png)
[log.txt](https://github.com/IsraelHikingMap/Site/files/3767608/log.txt)
[2019-10-24_06-12-27.373_מסלול_2019-10-24.gpx.txt](https://github.com/IsraelHikingMap/Site/files/3767610/2019-10-24_06-12-27.373_._2019-10-24.gpx.txt)

**Comment by valleyofdawn** [comment] 2019-10-27 10:05
Another such instance yesterday.
Several stalls. Their length seems to be proportional to how long I waited since the last time I set the screen on.
The times I noticed it stalled were 8:56, 9:21, 9:34. 9:53. It takes from seconds to 5 minutes for the app to recover.
The eventual recording was complete - although I could only stop recording on the car on my way home because it was unresponsive.

Nonetheless, when I reopened the app today it told me the recording was incomplete (at Km mark 10.27) and suggested I continue recording.
Attaching log and GPX.
[log.txt](https://github.com/IsraelHikingMap/Site/files/3775701/log.txt)
[Adulam.gpx.txt](https://github.com/IsraelHikingMap/Site/files/3775702/Adulam.gpx.txt)

**Comment by HarelM** [comment] 2019-10-27 10:06
Are you using the vector map?

**Comment by valleyofdawn** [comment] 2019-10-27 10:08
This time I did, the 3 previous times I didn't.

**Comment by HarelM** [comment] 2019-10-27 10:11
Ok. I'll remove the recording option then.
Please let me know if it happens without recording as well.

**Comment by valleyofdawn** [comment] 2019-10-27 10:31
OK let me know when it's in appveyor.

**Comment by HarelM** [comment] 2019-10-27 13:16
No need, I'll publish it straight to production. Make sure you install the app from the play store.

**Comment by HarelM** [comment] 2020-01-30 14:44
@valleyofdawn I think we can track this as part of: #1039.
Closing this as part of the definition of recording in the background.
If this happens again after the latest fix please report it in #1039, I hope this is now completely fixed.

**Closed by HarelM** 2020-01-30 14:44 UTC
Labels: App, Critical, bug
