### ISSUE TITLE
Unable to delete shared track

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#535] opened 2017-10-31 20:52 UTC
## What I expect to happen
Pressing the delete (trash) icon should remove a shared track from my shared tracks

## What really happened
Nothing

## What I did that caused the issue - step by step
Share a track
Click on the wrench icon next to the user name
Click on My Shares
Click on the delete icon next to the shared track

## My environment
* Operating System and version:
Windows 10

* Web Browser and version:
Chrome  61.0.3163.100

**Comment by HarelM** [comment] 2017-10-31 22:50
Thanks for reporting! 
I was able to reproduce the issue, hopefully will be fixed in the next few days.

**Comment by HarelM** [comment] 2017-10-31 23:03
You were right, this was caused by the database migration, will be published soon.
Thanks again for reporting!

**Closed** 2017-10-31 23:02 UTC
Labels: bug, Critical
