### ISSUE TITLE
Picture upload removed a `waterway` tag

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1446] opened 2021-02-28 11:12 UTC
## What I expect to happen
Picture uploads from IHM should not remove or change existing OSM tags

## What really happened
In [changeset 99419355](https://www.openstreetmap.org/changeset/99419355) [user מיכל](https://www.openstreetmap.org/user/%D7%9E%D7%99%D7%9B%D7%9C) used IHM to add a picture to [way 181440262](https://www.openstreetmap.org/way/181440262) - נחל פרס.

This update had a side effect where the `waterway=stream` tag of the way was deleted, as can be seen when comparing version 9 and 10 at http://osm.mapki.com/history/way.php?id=181440262

  | Ver 9 | Ver 10
-- | -- | --
Primitive Info
Time | 2020-09-20T08:16:51Z | 2021-02-17T04:50:06Z
Changeset# | [91168328](http://osm.org/browse/changeset/91168328) | [99419355](http://osm.org/browse/changeset/99419355)
User | [valleyofdawn](http://osm.org/user/valleyofdawn) | [מיכל](http://osm.org/user/%D7%9E%D7%99%D7%9B%D7%9C)
Tags
name | נחל␣פרס | נחל␣פרס
source | Bing | Bing
waterway | stream |  
intermittent | yes | yes
name:en | Peres | Peres
name:he | נחל␣פרס | נחל␣פרס
description |   |  
description:he |   |  
wikipedia | he:נחל␣פרס | he:נחל␣פרס
wikipedia:he  נחל␣פרס
image |   | [https://upload.wikim…](https://upload.wikimedia.org/wikipedia/he/5/59/Wadi_peres.JPG)

## What I did that caused the issue - step by step
It is not clear what the user has done. One possible scenario is:
1. Search for "נחל פרס"
2. Click the "edit" button
3. Add the picture
4. Click the "save" button

**Comment by HarelM** [comment] 2021-02-28 19:29
Seems like this happened before to the same stream, and I'm pretty sure I fixed this in the past... Nevertheless, I'll check it after I finish #1407, hopefully it will be solved there.

**Comment by HarelM** [comment] 2021-03-23 19:20
Seems like I'm not able to reproduce it after the changes made in #1407.
Closing this for now.
If the issue will return I'll either reopen or open another issue.

**Closed by HarelM** 2021-03-23 19:20 UTC
Labels: Critical, bug
