### ISSUE TITLE
Show all of the points on track when edit

### ISSUE THREAD

**Issue by moshfeu** [IsraelHikingMap/Site#331] opened 2017-03-26 11:05 UTC
I'm trying to edit a track which I recorded. The problem is that I have just few points to edit and it's hard to edit the right track this way. Is there a way to display all the points?

Thanks

**Your great app**
<img width="548" alt="screen shot 2017-03-26 at 1 59 10 pm" src="https://cloud.githubusercontent.com/assets/3723951/24330702/12c0107c-122d-11e7-93e8-603f93c67b28.png">

**Another web app**
<img width="585" alt="screen shot 2017-03-26 at 2 02 39 pm" src="https://cloud.githubusercontent.com/assets/3723951/24330703/12c0cbc0-122d-11e7-86bf-c713797b3c2a.png">

**Comment by HarelM** [comment] 2017-03-26 11:24
Unfortunately for you this is by design...
We read a file and place only important "knobs" on it so you can manipulate it without having too many points.
Consider the following scenario (which we believe is the general use case):
1. Open a file I recorded.
2. Move some of the "knobs" so that the route will snap to the existing OSM database.
3. Share the route.

In the above case you'll have tons of points to move in order to achieve a route based on OSM database.

You can however create a local version of the site and change the configuration so that every point will be considered as "Important" point, not sure it help in your case.
What is the general use case for this feature? Can you describe something that a user would do that requires this capability?

Not sure I made myself clear, but I think you asked in the past if you can run this server locally, right?

**Comment by moshfeu** [comment] 2017-03-26 11:51
I agree that the scenario you described is the general. But my scenario is common too. The scenario is that I record a track. Most of the time the track is not "clear" because of GPS disconnection or faster driving or mistakes that I do in the navigation. 
After I come home I want to fix the record and this is the scenario. I can't fix the track that's way. 
You scenario is for **build** a track. My scenario is to edit and fix.

I think that the right solution is to add a checkbox (or something) that ask the user if he wants to see **all** the "knobs" or not.

I cloned this project in the past, but now, unfortunately I have no time to dive into it.

**Comment by HarelM** [comment] 2017-03-26 11:59
The only place I can think of adding a feature like that is in the advanced route setting - adding a button: "Allow points manipulation" - this button will create "knobs" on all the route's points.
Note that this can cause the browser to be slow if the number of points is big...
The problem is that there's already too many buttons there.
I'll think about it, I can't promise anything. feel free to submit a pull request if you find the time to implement it yourself.

**Comment by moshfeu** [comment] 2017-03-26 12:03
Sounds good for me :)

Thanks

**Comment by HarelM** [comment] 2017-03-26 12:04
Still not implemented... 😊

**Comment by HarelM** [comment] 2017-06-11 14:09
This feature collides with #351 - the problem is that when there are too many point the browser has a hard time presenting the route, and editing will not be possible.
Also this action will be very hard to do as a symetric operation - meaning the user will not be able to undo once he clicks on say "show all points" button.
I think it will be better to leave this feature to other route editors which do not have routing and snapping.

**Comment by moshfeu** [comment] 2017-06-11 14:31
`meaning the user will not be able to undo once he clicks on say "show all points" button`. I'm not sure I understand.. He couldn't to uncheck this option and return to the lower points state?
I understand that is can cause the browser to get slow, that why it advanced. If it doesn't work for a specific track, the user should not use it.
I will trying to implement it by myself and you can check it. I have a list of features I want to work on, I hope I will get to all of them :)

**Comment by HarelM** [comment] 2017-06-11 14:40
Note that I migrated the UI to angular 4 in Angular4 branch.
There's a bug on chrome mobile over there which I hope will be solved soon and I'll be able to merge these changes to the stable version, but currently I don't get any answers there so I'm not sure what to do. If you have so time and want to tackle a very hard bug I'll appreciate it a lot as I don't have a clue how to solve it.
I think it will be wiser to work on that branch if you want to do UI changes but since this is not in stable the instructions is not written well enough I think.
So it's kinda in the middle since I don't know if I'll ever merge this branch... :-/
In any case, if you put it on a server and send a link we can talk about how useful and if the UX is well and I could probably write it again if need be.
The thing about this feature colliding with #351 is that the server will reduce the number of points when opening a file, before presenting it in the UI, which will make this feature not so great in terms of editing a file...

**Comment by moshfeu** [comment] 2017-06-12 07:28
I will be happy to help if I can. Now, when I succeed to run the project, I can try. Can you describe me the problem? Or do you have a link to the issue?

**Comment by HarelM** [comment] 2017-06-12 08:41
https://github.com/angular/angular/issues/17039
I tired to create a small reproduction project and placed it on our server to be able to test it on mobile chrome - the link is in the above issue.
The following is the angular 4 brnach:
https://github.com/IsraelHikingMap/Site/tree/Angular4
I now see that the instructions are up to date so you should be able to work on that.
I would be greatly appreciate if you could solve this bug, even if it means changing the code here as a workaround...

**Comment by moshfeu** [comment] 2017-06-12 16:48
When I'm running the app (Angular4 branch) from local using [ngrok](https://ngrok.com/) and press the graph button the track statics popup is displaying. Did you resolved it?

**Comment by HarelM** [comment] 2017-06-12 16:55
This happens on mobile chrome, not in the desktop...

**Comment by moshfeu** [comment] 2017-06-12 21:27
I understood. I run the local app on my **mobile device** using ngrok service. Can we continue the discussion via email or whatsapp or something?

**Comment by HarelM** [comment] 2017-06-12 21:49
Sure, I'm at harel.mazor at gmail dot com.
I'm not familiar with ngork.
Let me know if the following address works on you mobile chrome:
http://israelhiking.osm.org.il/issue17039/
If it does then I need to understand why it doesn't work on mine...

**Comment by HarelM** [comment] 2017-11-14 17:38
As this collides with #351 which I think is a more important feature for performance and the fact that this site is not intended for editing GPX traces as there are other sites that can do it I'm closing this for the same reason as #550.

**Comment by HarelM** [comment] 2017-11-17 17:34
After rethinking this and the fact that one can't edit his own GPX file properly I think I can add a button in advanced route setting that will look like multiple "drops" to allow the user to gain full control over an imported file.

**Closed** 2017-11-17 23:14 UTC
Labels: enhancement, Medium

**Comment by HarelM** [comment] 2017-11-17 23:22
Here's a pre-release glimpse.
![image](https://user-images.githubusercontent.com/3269297/32973168-bfdc6338-cbfe-11e7-920f-dbc699db0444.png)

**Comment by moshfeu** [comment] 2017-11-19 10:33
Looks great :)
