### ISSUE TITLE
Preference of Hebrew Wikipedia

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/Site#1558] opened 2021-07-21 20:47 UTC
## What I expect to happen
If the POI has links to Hebrew and English Wikipedia, the link of name should be to Hebrew Wikipedia (`wikipedia:he` or auto merging).

## What really happened
The link to wikipedia tag.

## What I did that caused the issue - step by step
1. Go to [Sde Boker](https://israelhiking.osm.org.il/poi/OSM/node_278469889?language=he)
2. Click on the name.

## Things I think the developers should know, images, links etc.
You can get the link from Wikidata too.
https://www.wikidata.org/w/api.php?action=wbgetentities&props=sitelinks/urls&ids=Q1026531&sitefilter=hewiki&format=json
See more in [stackoverflow](https://stackoverflow.com/questions/37079989/how-to-get-wikipedia-page-from-wikidata-id).

**Comment by HarelM** [comment] 2021-07-22 04:56
This is basically a duplicate of #1165 and I don't think anything had changed. Sorry. Fixing this is very complicated and did not seem to worth the effort.
If you world like to send a PR that will resolve this I'm perfectly fine with it, but otherwise I'll close this issue...

**Comment by HarelM** [comment] 2021-07-22 05:07
Actually, I might be able to only apply this for wikipedia links in Hebrew and English and not generalize this.
I'll think about it and if I find an easy solution I'll fix this.

**Comment by HarelM** [comment] 2021-07-22 06:49
Closing this in favor or reopening the original issue #1165.

**Closed by HarelM** 2021-07-22 06:49 UTC
