### ISSUE TITLE
Point edit is activated after adding a POI to private route

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#509] opened 2017-10-12 12:48 UTC
## What I expect to happen
No change in editing mode after adding a POI from the layer

## What really happened
Point editing was activated:

![image](https://user-images.githubusercontent.com/1304610/31496522-6a560678-af64-11e7-9a59-87a72c72b7e2.png)

## What I did that caused the issue - step by step
1. Disable any edit mode
2. Show the POI layer
3. Click on a POI
4. Click on the "+"
5. The cursor is now in POI add/edit mode

## My environment
* Operating System and version: Windows 10 home
* Web Browser and version: Firefox

**Comment by HarelM** [comment] 2017-10-12 14:13
This is by design, I can't find the original issue that requested that once you add a route from a POI you'll be able to edit it immediately.
A different requirement might be for a point.
In any case this is not a bug...

**Comment by zstadler** [comment] 2017-10-12 18:51
I see the rational of being able to edit such a POI immediately. 

Therefore, I suggest that the result of clicking near a POI will be the same regardless if "Edit Points" mode was active or not before the click:

![image](https://user-images.githubusercontent.com/1304610/31513381-daad9706-af96-11e7-8e66-d3f118ebb295.png)

**Comment by HarelM** [comment] 2017-10-18 16:38
This is hard to implement and will have bad results when there are several close private POIs.
If you have a better approach that might help let me know. I don't have a good idea hot to properly solve this (POI on top of POI at the exact same location).

**Comment by HarelM** [comment] 2017-10-31 23:22
@zstadler maybe you can use this issue to describe what we agreed on the phone today.
If not, please close this and open a new one as it will probably cover this one as well.

**Comment by HarelM** [comment] 2017-11-01 20:12
Closed in favor of a general issue to cover all scenarios: #537

**Closed by HarelM** 2017-11-01 20:12 UTC
Labels: Help wanted: UX
