### ISSUE TITLE
Can't add a shared route on a mobile browser

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#991] opened 2019-03-18 06:20 UTC
## What I expect to happen
Being able to view old shares when using my phone's browser.

## What really happened
When I'm browsing to the site using my phone, and I want to add an old share of mine, I can see the list of available shares. But I can not scroll down to the buttons of "Present share" or "Add to routes" (What is the difference between them anyway?)
![image](https://user-images.githubusercontent.com/538720/54510426-e2f0f200-4955-11e9-8107-1d9b9d1a5fec.png)

When I tried using the Android app it worked fine.
![image](https://user-images.githubusercontent.com/538720/54510631-d325dd80-4956-11e9-86f9-891d68019671.png)

Checking in Chrome Stable was also working as expected
![image](https://user-images.githubusercontent.com/538720/54510580-a1ad1200-4956-11e9-86d2-37496574a30b.png)

## My environment
* Operating System and version: Android Q Beta 1
* Web Browser and version: Chrome Canary 75.0.3736.0

**Comment by HarelM** [comment] 2019-03-18 08:15
Thanks for taking the time and opening a bug.
Present share - means you select it so you can also update it. Add a route doesn't change the selected share so you can merge two shares into one for example.
This is a duplicate of #818.
Using the app should solve it, so I'm not sure this is interesting...

**Comment by ATGardner** [comment] 2019-03-18 08:33
This is happening on my Chrome Canary (not on stable) - it might be related to some bug on Canary, or it might soon make its way into the stable version as well.
And using the Android app is not an (easily available) option for users with non-Israeli Play Stores,

**Comment by HarelM** [comment] 2019-05-04 15:53
@ATGardner please let me know if you see this happens in the future, I'll close this issue for now as there's nothing I'm planning to do here.

**Closed by HarelM** 2019-05-04 15:53 UTC
Labels: Low, bug, duplicate

**Comment by ATGardner** [comment] 2019-05-04 15:58
It's definitely still happening in my Chrome Canary browser on my phone.
It might be caused by a bug in Chrome, or it might soon move from Chrome Canary to dev->debug->stable, and stop working for anyone who is using Chrome for Android with your website.
