### ISSUE TITLE
Lose the editing route points

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#183] opened 2016-07-07 14:27 UTC
They obscure the view, are arbitrary (not necessarily POIs). You can drag any point along the way anyway. This would also eliminate the ambiguous appearance of POIs and WPTs.

**Comment by HarelM** [comment] 2016-07-11 20:51
See issue #114.
I'm not planning on losing them, I think they are needed.
Keeping this open until the above issue is closed.

**Comment by zstadler** [comment] 2016-07-16 10:06
IMH, the route points are a significant disadvantage for using our map for sharing trails and embedding in other sites.

The route points are useful for editing. But a shared trail is expected to be viewed, not edited (at least by most viewers, and initially by all viewers).

I suggest that:
* Route points are shown only when in editing mode.
* Non-edit mode remains the default mode
* When not in editing mode
  * waypoints show as a small icon, such as a circle, dot or X, to clearly show the exact location
  * Labels are shown, if a waypoint has a "name" tag

For example, take [this trip description](https://sites.google.com/site/mountainbikeridesinisrael/Home/mtb-israel/bnot5b):
The Author's own map is:
<img width="450" src="https://b9cbe4b1-a-62cb3a1a-s-sites.googlegroups.com/site/marley41a/file/bnot5b-map.jpg?attachauth=ANoY7cqAYc08nLRoy38lTVrlqxnyd1_gPU780O2pBIrSS3yC7ItlAqQ5xQ55fJQYs5VGuynpLYUN-84vXg6HHwOVbjblkR6fKIfHQLnlsxC6siV_4YLDVmR048hW1Ac2gg65oRaNl_lg3CWxeRcD3twit47lcKvoBJhXu12Yu0Y5OaGuE_WdkVwCH1WzeZWe8KZqnhZjvtblY7eqxALaCx95HUOT4A8RiQ%3D%3D&attredirects=0" >

Israel MTB map shows the GPX file with our own-generated route points,
while the GPX file did not contain any waypoints:
<img width="450" src="https://cloud.githubusercontent.com/assets/1304610/16894043/3b7a4380-4b53-11e6-99be-65ecbb34aedf.png">

Amud Anan shows just the track included in the GPX file:
<img width="450" src="https://cloud.githubusercontent.com/assets/1304610/16894034/c7af08aa-4b52-11e6-8fd2-d7b7408351ef.png">

**Comment by HarelM** [comment] 2016-07-16 11:49
I don't think you can really compare amud anan to our site since amud anan doesn't have editing capabilities.
Having said that, I do agree that viewing a route should look different than editing it.
The current issue I'm facing with this idea is the fact that you have two editing modes:
1. Adding point editing mode (currently with the hover dashed line).
2. Route change editing mode - you can move points and add middle points.
In both cases the points should appear big I think.

When the route in not active (happens when another route is active) the route is presented with no points.

I don't have a clear way to combine all the states above to a clear and easy user experience.

Thoughts are welcome.

**Comment by zstadler** [comment] 2016-07-16 12:48
I think first editing mode is enough, and it should behave as it does today:
* Mouse click-drag or touch-drag on the existing route modifies it by either moving an existing point or adding a new point between existing points.
* Mouse click away from the track extends the route with a new point.
* The only thing I would change is to omit the dashed line from the end of the route to the cursor

BTW, Amud Anan does have route creation editing mode. It does not have map-based routing for the edited route.

**Comment by valleyofdawn** [comment] 2016-07-16 13:09
I think that limited editing capabilities on the mobile device is OK. I wouldn't show any handles in display mode, which should be default. Show just small draggable dots when in edit mode. There should be just one edit mode. Touching a point off course would add it. Touching a dot on course would drag it. Hover is not necessary on a mobile device.

**Comment by HarelM** [comment] 2016-07-16 14:55
There's no hover on mobile devices anyway I don't need to do anything special to prevent that and I would like the solution to this problem to work the same for all kind of devices, otherwise it will be very difficult for me to change a behavior and maintain it.
Amud-Anan has either route creating or route viewing not route editing/updating which is where the issue is... let's remove it from our discussion for now at it is very partial compared to our capabilities.

The proposal for a change is as follows:
A route will be presented as read-only by default - small points to indicate where the route is passing through and labels as it has today to indicate POIs. POIs that are not part of a route will have a "big" marker to indicate where the POI is + label.
When a user clicks the pencil the route will transform and the route points will grow so that the user will be able to edit them, clicking the pencil again will transform back to read-only.
Editing will be like today - except for when clicking on a route point a menu will pop to allow adding text (like in POIs today) and delete the route point (no more double click, I think I can allow "del" key in this state).
When user clicks on the map-maker near the pencil (see issue #182) he will have the above editing capabilities but clicking on the map will add a POI and not a route point.

Does this cover all your wish-list?

**Comment by zstadler** [comment] 2016-07-17 07:01
Loading GPX tracks in Read-only mode:
- GPX tracks (recordings) can contain hundreds and thousands of track points. None of them is more significant than the other (except the start and the end points). When loading a track, route editing points should not be created until editing mode is entered. This will prevent showing artificially-created route-editing points that were not in the file. These points will only be useful if and when editing mode is entered.
- GPX routes (plans) need to show they route points when loaded in read-only mode.

@HarelM About POI editing mode proposal:
- Do you mean that in POI editing mode it will be possible to modify the line by moving point and adding new intermediate points?
- What's the touch-screen equivalent of a right click? Long press!?
- Will double-click continue to delete a POI?

Side notes:
- Assuming the duplicate label refers to issue #144. This issue and issue #114 are related yet independent issues. They are not duplicates. Issue #114 refers to the arrangement of buttons in the different modes: read-only, routing, POI-editing. This issue refers to the POI and track visualization and operations in each mode. Each of the issues can be implemented independently: new button arrangement with existing visuals and operations , or new visualization and operations with existing buttons arrangements.

- Amud Anan allows editing of routes. For example, you may edit http://amudanan.co.il/?url=http://www.jeepolog.com/UserFiles/TWL/eshtaol2.twl. Editing of large tracks, with more than 500 track points, is not allowed. Indeed this is possible in IHM that simplifies the track.

**Comment by HarelM** [comment] 2016-07-23 02:17
While you might be right about this issue not being a duplicate of issue #114 they will both be implemented in the coming major release - version 4.0.

> Do you mean that in POI editing mode it will be possible to modify the line by moving point and adding new intermediate points?

Yes.

> What's the touch-screen equivalent of a right click? Long press!?

I don't know, it might be, but I intend to remove double click completely.

> Will double-click continue to delete a POI?

No, When a user will click on a POI he will have a delete button inside the pop-up menu, I'll post a screenshot soon.

**Comment by zstadler** [comment] 2016-07-24 14:08
I think that mixed editing of waypoints (POIs) and routepoints is creates unclear user interface. 
For example, with mixed editing, it will be difficult to select a waypoint located at where two routes meet.
It is also not aligned with the recent agreement to separate waypoints from tracks.

**Closed** 2016-07-24 21:58 UTC
Labels: duplicate, enhancement
