### ISSUE TITLE
Add an "eye" to the Layers menu command

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1362] opened 2020-11-11 03:40 UTC
Feature request

## What I expect to happen
An "eye" shall be added to the Layers menu entry. This will unify the UI language with the 3 menu items above it.  
An ability to close the Layers pane shall be added as a new functionality to the menu, with the same operation the X now does, in that pane.

![Eye](https://user-images.githubusercontent.com/49042192/98762461-59bae880-23e0-11eb-84ae-9c76d061b3ee.PNG)

**Comment by HarelM** [comment] 2020-11-11 07:27
Duplicate of #1358

**Closed by HarelM** 2020-11-11 07:27 UTC
