### ISSUE TITLE
Issues with Recorded track on the beta app

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1009] opened 2019-04-28 09:39 UTC
## Bug

1) I expected the recorded track to be continuous - not dashed.

2) After stopping the recording and entering edit mode, I expected a new route to open. Instead it started editing the recorded track.
The likely scenario for editing in the field is of a planned route (that you need to shorten, add a detour etc), not the one you are recording.

8.0.270 app version

**Comment by HarelM** [comment] 2019-04-28 10:54
I've opened a new issue for 1: #1011.
I do not agree about 2 - I expect the selected route to be the recorded route so the user can save it or share it, expecting the app to create a new route is counter intuitive IMO.
Please close this issue.

**Comment by HarelM** [comment] 2019-04-28 10:56
Also it is not related to the beta version, if you feel strongly about it please open a separate issue with a feature request as this is clearly not a bug.

**Comment by valleyofdawn** [comment] 2019-04-28 11:23
Doesn't saving and sharing pertain to all tracks, not just the active ones?
You refer to the recorded track as just another route, obtained by recording rather than planning.
In a navigation app (which I believe that is what our app should be) it is a fundamentally different entity than the planed routes. It's used for reference and documentation and should be protected from accidental editing.
Users would like to examine it for stats and share it after their trip and accidentally ruining it would, I believe; be a major turn-off.

**Comment by HarelM** [comment] 2019-04-28 11:31
Saving is by default to current track only.
You have undo to prevent ruining, and the route is also saved to your personal tracks when the recording is finished- so there's no real issue with data loss.
Closing, I have added instructions on what are the available options.

**Closed by HarelM** 2019-04-28 11:31 UTC
Labels: High, enhancement
