### ISSUE TITLE
auth w/ google token fails

### ISSUE THREAD

**Issue by michaelmbr** [IsraelHikingMap/Site#1549] opened 2021-07-12 08:20 UTC
## Bug
Maybe it is not yet implemented, or needs a token refresh on google oauth backoffice
## What I expect to happen
Use Google account auth token
## What really happened
error 403 google can't sign you in safely inside this app you can use google sign-in by visiting this app's webiste in a browser like safari or chrome
## What I did that caused the issue - step by step
Tried using google auth on sign-in window of the app on a new phone
## My environment
(replacement phone, samsung J7 Pro w/ android 8.1.0), using the updated android IHM app
## Things I think the developers should know, images, links etc.
Love the program, use it a lot.

**Comment by HarelM** [comment] 2021-07-12 08:27
Thanks for taking the time to open this issue!
This is basically a duplicate of #803.
I also tried to address this in #1433, but didn't get any response from the maintainer of the relevant plugin.
I wasn't able to fix this due to what seems to be some Cordova limitations with in-app-browser and other headers problems.
Feel free to submit a PR to resolve this.
I'll be closing this, if you send a PR I'll reopen.

**Closed by HarelM** 2021-07-12 08:27 UTC

**Comment by michaelmbr** [comment] 2021-07-12 08:36
Thanks Harel I'll try to check the status on OSM

בתאריך יום ב׳, 12 ביולי 2021, 11:27, מאת Harel M ***@***.***

**Comment by michaelmbr** [comment] 2021-07-12 08:51
On OSM it works, so I guess it is something dev-related which is out of my
scope of expertise. It is NOT a very important feature, but rather a
significantly easier method to access the subscription without resorting to
an application centric credential,

Michael

**Comment by HarelM** [comment] 2021-07-12 11:28
I agree... but current ROI is low as the complexity of this feature seems high...
