### ISSUE TITLE
Cant edit existing recording 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1410] opened 2020-12-25 18:08 UTC
## Bug
When editing an existing recording, the red end route dot disappears. 

## What I expect to happen
Keep red dot as an anchor so I can edit in the middle of the route

## What really happened
Funny behavior when editing the file

## What I did that caused the issue - step by step
Downloaded a recording from Strava and tried editing it

## My environment
* Operating System and version: Win10
* Web Browser and version:  Chrome

## Things I think the developers should know, images, links etc.
An example file is here 
https://drive.google.com/open?id=1ZY8ksmRujudeEFB021-Q-i5i3V3fFS4u

**Comment by HarelM** [comment] 2020-12-25 18:12
Thanks for taking the time to report this.
This was already fixed but not published yet.

**Comment by HarelM** [comment] 2020-12-25 18:47
Closing as duplicate of #1396

**Closed by HarelM** 2020-12-25 18:47 UTC
Labels: duplicate
