### ISSUE TITLE
The statistics button doesn't appear on the bigger elevation chart

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Site#990] opened 2019-03-18 06:09 UTC
## What I expect to happen
this is the small chart -
![image](https://user-images.githubusercontent.com/538720/54510202-0d8e7b00-4955-11e9-8c7a-5821ae9348b7.png)

and this is the large chart -
![image](https://user-images.githubusercontent.com/538720/54510217-20a14b00-4955-11e9-8e0e-44d393425edf.png)

The statistics button doesn't appear on the larger one.

## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment] 2019-03-18 08:21
This is partially by design - see #854.
The statics window doesn't look nice when stretched and there's no extra data when using full screen.
Can you please elaborate on the user flow that will require the statistics on the wide graph?

**Comment by HarelM** [comment] 2019-03-18 22:27
Closing in favor of #989

**Closed by HarelM** 2019-03-18 22:27 UTC
Labels: invalid
