### ISSUE TITLE
English mode is not stored in shares

### ISSUE THREAD

**Issue by E-Reuven** [IsraelHikingMap/Site#570] opened 2017-12-04 22:45 UTC
## Bug/Feature
When generating a sharing-link, the links always displays the Hebrew version of the map even if the share was made when English was the selected language. 

## What I expect to happen
Language selection should be accounted in (just like map extent) when generating a share link.

## What really happened
The share links always points to the Hebrew-language map.

**Comment by HarelM** [comment] 2017-12-07 18:27
One can argue that this is not a shareable option as the language is decided by the user, the same why that you would send a word file to a friend and the language of the word application's interface won't change.
I understand the requirement, and I don't think it's hard to implement, but I'm not sure it's a correct behavior...

**Comment by E-Reuven** [comment] 2017-12-08 16:08
One could definitely argue about that. 
In this case I think the comparison of a Word file being shared with Word programs that have different interfaces (or even versions) is not a good one, since your website encapsulates both the Word "file" and the Word "program" together.

When I click "share" in your website, I want to share the experience I am having right now in your website with a friend, thus I expect the link to recreate my experience in my friend's computer on your website.

**Comment by HarelM** [comment] 2017-12-08 22:31
The more I think about it the less I agree this should be the expected behavior.
When one changes his preferences for a user interface language one should not expect it to be shared.
When you send a link to a website you do not expect the browser to change language on the receiving party.
Lets assume for a second there are more than Hebrew and English language interfaces where we both can read and understand, let's assume you prefer Russian UI (which I do not speak or know how to read) - if I receive a share and it would change my site to be in Russian it would piss me off as I'll need to search and find where to change the language back as I wouldn't be able to use the site properly (Although it is designed to reduce this effect as it uses Icons for most buttons, but still).

**Comment by E-Reuven** [comment] 2017-12-08 22:38
> if I receive a share and it would change my site to be in Russian it would piss me off as I'll need to search and find where to change the language back
That's **exactly what's happening** when I'm sending a link to a non-Hebrew speaker. The link always open your website in Hebrew for him, which pisses him off since he cannot read Hebrew and need to search and find where to change the language to English.

Again, we need to ask what's the user story? The user-story of "share" is to share the **exact experience** he is having right now when click the "share" button. If a user intends to share a link with an English speaking friend, he will switch to English - to make sure that (for example) the English labels in the extent of the map are not cut out etc., and only then click "share".

**Comment by HarelM** [comment] 2017-12-08 23:09
The link opens the website in the last selected user language - the default is Hebrew - since your friend never used this site he would need to change the language once (per device that is), from then on when you'll share a link it will open his preferred language - which should not be coupled with yours while creating the share, IMHO.

I understand the user story but I think you are looking at it from a narrow point of view.
If you decide to change your UI to Russian and send me a link I would not want my UI to change to  Russian.

**Comment by E-Reuven** [comment] 2017-12-08 23:18
>  since your friend never used this site he would need to change the language once 

Exactly, now I'm sending links to friends who don't normally use the site (I'm the one who is using it regularly) so it's a thing I need to explain every time I send a "share" link.

> I understand the user story but I think you are looking at it from a narrow point of view.
> If you decide to change your UI to Russian and send me a link I would not want my UI to change to Russian.

I think you're missing the user story here. As a user, if I'm using a Russian UI, and I'm sending a link to you - and I know you're a Hebrew-only speaker (you're my friend, I know you :) ) - I will change the interface to Hebrew and then share the screen I'm seeing, that's what people do - they expect that exactly what they see will be shared when they use a 'share' option.
Think of an article in Ynet. If I want to share it with an English-speaking friend, I will share the English article (on YnetNews.com) and not the Hebrew article (on Ynet.co.il). That could also go for Facebook etc. People share what they want to share - the exact experience they have.

**Comment by HarelM** [comment] 2017-12-08 23:32
As I said, I understand the requirement, I just don't agree with your perspective - you believe the language is a shareable property and I don't.
Ynet is not a good example as it is not an application - it's a portal with links, it doesn't have a UI language you can change while working with it.
Facebook on the other hand does:
the following bar is in the language of your choosing:
![image](https://user-images.githubusercontent.com/3269297/33789333-7b636a0c-dc80-11e7-9eda-7cc6e99686b3.png)
If you'll send me a Facebook link it will not change and you won't expect it to change when sharing.

**Comment by E-Reuven** [comment] 2017-12-08 23:40
Of course the interface language will not change on Facebook, I was talking on a particular Facebook post. If I'm sharing a Hebrew Facebook post, you will get a Hebrew Facebook post. If I'm sharing an English Facebook post, you'll get an English Facebook post.

One thing is **data**, the other thing is the **interface**.
In IsraelHikingMap, your are not differentiating the interface from the map. The map itself is **data**, why don't you let people select the map they want to see, without changing interface?
If you could let me choose the map I want, including whether that's an Hebrew or an English map, without any relation to the interface language, I think that might be solving the problem:

1) Interface language can be still totally user-dependent, as today (not stored in a "share" link)
2) The share link will include an indication of the selected/viewed map when the sharing user clicked "share".

**Comment by HarelM** [comment] 2017-12-08 23:49
There's no problem in doing it today:
1. Open the left pane
2. Click advance options
3. Add a baselayer
4. Set the address to: https://israelhiking.osm.org.il/English/Tiles/{z}/{x}/{y}.png
5. Share.

Here's an example:
https://israelhiking.osm.org.il/#!/?s=18CwxgTjpX

**Comment by E-Reuven** [comment] 2017-12-08 23:53
Thanks! 
That solves the problem. However, that's far from obvious..

1. What's the URL for the MTB map in English?
2. Could you have the links to the English map pre-set on the left pane?

**Comment by HarelM** [comment] 2017-12-09 00:25
https://israelhiking.osm.org.il/English/mtbTiles/{z}/{x}/{y}.png
Not sure what you mean by 2 - if you mean left aligned then it's probably doable but I have better things to take care of, if you wish to do it you are welcome to send a pull request.

Regarding the fact that it's not obvious, well, I'm trying to keep the things that are relevant to 90% of the users as the obvious stuff and allow the more complex things less obvious and user friendly for the power user as most users will not use them.
Closing...

**Closed by HarelM** 2017-12-09 00:25 UTC

**Comment by E-Reuven** [comment] 2017-12-09 00:28
Thanks for the MTB map link.

About #2 - I'm not talking about alignment at all. I was asking - could you have the English map layers already preset in the "layers pane"? (so one would not need to add them manually).

**Comment by HarelM** [comment] 2017-12-09 00:33
No, sorry, not planning on adding two more layer just for sharing an English version of the map...

**Comment by E-Reuven** [comment] 2017-12-09 00:38
If you put it this way, there's definitely no point :)

But, having the option to select an English map can be a platform to benefit other uses (not sharing). People will begin using it (currently we are all unaware of the possibility to use an English map in a Hebrew interface, as I had).
