### ISSUE TITLE
Israelhiking  - missing information

### ISSUE THREAD

**Issue by esterkru** [IsraelHikingMap/Site#1417] opened 2020-12-31 09:36 UTC
## What I expect to happen
The road from the green to the red dot should go through the tunnel that passes under Road No. 1 as I marked in the attachment.
![ic](https://user-images.githubusercontent.com/39528992/103404087-02710300-4b5b-11eb-91e2-f1a75874c485.PNG)

## What really happened
The route does not refer to the tunnel but makes a detour through the bike path.

## What I did that caused the issue - step by step
I marked the 2 points and the israelhiking app marked the route between them

## My environment
* Operating System and version: windows 
* Web Browser and version: chrome

## Things I think the developers should know, images, links etc.
----

**Comment by HarelM** [comment] 2020-12-31 09:40
Thanks for taking the time to report this issue.
Can you please share the location of this tunnel?
In most cases the problem is with the mapping itself and not the site...

**Comment by HarelM** [comment] 2020-12-31 09:45
The amazing thing with vector maps is that you can really zoom in to see mapping issues,
It is clear when you zoom in that the steps and tunnel are not connected:
![image](https://user-images.githubusercontent.com/3269297/103404705-482ecb00-4b5d-11eb-9013-55dd1992183c.png)
Hence the routing is going through the path and not though the tunnel.
For now I'll be closing this issue, feel free to continue writing here if you need any assistance in editing the map.

**Closed by HarelM** 2020-12-31 09:45 UTC
