### ISSUE TITLE
Wrong merge for שדרות

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1098] opened 2019-12-03 09:11 UTC
## What I expect to happen
The merge of Sderot should be for the city in both OSM and Wikipedia

## What really happened
The [IHM Hebrew POI for Sderot](https://israelhiking.osm.org.il/poi/OSM/node_278474577?language=he) merges the [OSM `place=town` node](https://www.openstreetmap.org/node/278474577) with the Wikipedia entry for the [Sderot railway station](https://he.wikipedia.org/wiki/%D7%AA%D7%97%D7%A0%D7%AA_%D7%94%D7%A8%D7%9B%D7%91%D7%AA_%D7%A9%D7%93%D7%A8%D7%95%D7%AA) rather than the [Sderot city](https://he.wikipedia.org/wiki/%D7%A9%D7%93%D7%A8%D7%95%D7%AA) entry.

## What I did that caused the issue - step by step
Use the Wikipedia link in the [IHM Hebrew POI for Sderot](https://israelhiking.osm.org.il/poi/OSM/node_278474577?language=he).

**Comment by zstadler** [comment] 2019-12-03 09:17
Note that the desired Wikipedia entry has the same name as the OSM entry and it is geographically closer:
![image](https://user-images.githubusercontent.com/1304610/70037005-79d20d00-15be-11ea-8a4a-74d4c3f65690.png)

**Comment by HarelM** [comment] 2019-12-03 13:05
@zstadler I think this might be a duplicate of #1084.
I have fixed something similar lately in Nahariya.
Can you check if you see the same issue with the offline POIs? They have gone through the new merge process which has yet to be published to the site. If you don't see the issue there then you can close this issue.
I'll check later on my dev machine nevertheless...

**Comment by HarelM** [comment] 2019-12-03 20:13
The problem is that the wrong merge (before my current fix) leaked into OSM :-(.
See here:
https://www.openstreetmap.org/node/278474577/history
I'll fix the OSM entry.

**Closed by HarelM** 2019-12-03 20:13 UTC
