### ISSUE TITLE
Update osm database for routing

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#129] opened 2015-12-09 08:50 UTC
http://israelhiking.osm.org.il/#/?s=4VvDqZWasG fails to create a route in hiking mode from the green track to the unmarked track, but the near-by http://israelhiking.osm.org.il/#/?s=cJHLJzWKpT succeeds.

Also the success is partial, as the route does not start from the start point itself on the green track, but about 1 km West of it.

I've checked the OSM data, and the green trail is well connected to the junction with Red track.

**Comment by HarelM** [comment] 2015-12-09 20:20
Maybe we need to update the routing database, I'm guessing it wasn't updated since I first loaded the routing service.
Also if this continues we should contact graphhopper and let them know, there's not much I'm doing besides proxying the request...

**Comment by zstadler** [comment] 2015-12-10 07:42
I've just ran into a [similar behavior here](http://israelhiking.osm.org.il/#/?s=KcPZcPZSEU).

How difficult is this update?
Can we run the update daily, as the graphhopper team replied on [stackoverflow](http://stackoverflow.com/questions/23209600/graphhopper-how-ofter-the-map-database-is-updated)?

**Comment by HarelM** [comment] 2015-12-10 07:50
There's no problem doing it nightly, the process is very simple:
Close the GH process
delete the GH local cache (folder) 
place the new osm file and start the GH process.

**Comment by zstadler** [comment] 2015-12-10 07:53
It looks like a DB issue as graphhopper gives a good [route for the second example](https://graphhopper.com/maps/?point=30.091969%2C34.873867&point=30.095534%2C34.919872&locale=en-US&vehicle=car&weighting=fastest&elevation=true&layer=TF%20Cycle)

**Comment by zstadler** [comment] 2015-12-20 08:17
Harel,
I'd like to refresh the local cache.

Can you elaborate 
* Which directory is the Graphhopper local cache (folder)?
* Which file is the OSM db?
* How to restart the Graphhopper process?

If possible, I'll add it to the map creation process to the map and its routing info are kept in sync.

**Comment by HarelM** [comment] 2015-12-27 22:19
GraphHopper files can be found in two folders:
 * C:\IsraelHiking\graphhopper-0.6
 * C:\IsraelHiking\graphhopper-0.6-backup

These folders are a complete duplicate of each other in order to always be "online", so the instructions are the same for both basically.
The following steps are needed in order to update the routing database (lets start with the backup folder):
1. Copy the latest israel-and-palestine-latest.osm.pbf to this folder.
2. Delete the israel-and-palestine-latest.osm-gh folder in that folder.
3. Run "Run.cmd" - this should create israel-and-palestine-latest.osm-gh folder and fail at the end because the 8989 port is taken. it should run for about 5 min before failing, it does not end the process so I'm not sure how to know it had finished automatically (except for a predefined timeout) but java throws exceptions to the console...
4. Kill the GH process and click "Run.cmd" again, this time it should start the GH server from the backup folder. success message should look somewhat like the following:
```INFO  com.graphhopper.http.GHServer - Started server at HTTP :8989```
5. Do steps 1-4 for the regular folder.

At the end of these steps both the backup and regular folder should be up-to-date with latest osm data and the process should run from the regular folder.

I just finished doing it now so the database should be up-to-date (26.12.2015).

**Comment by zstadler** [comment] 2015-12-31 10:21
I thought of a slightly different approach using a single graphhopper directory:

1. Copy the latest pbf file, if needed, or quit if no update is needed
2. Build the new routing database in a new directory, say israel-and-palestine-latest.osm-gh-new
  * Using  com.graphhopper.tools.Import class
3. Delete the israel-and-palestine-latest.osm-gh-old directory, if exists.
4. Kill the running server
  * Using wmic to identify and terminate the Java process running the graphhopper server
5. Rename israel-and-palestine-latest.osm-gh to israel-and-palestine-latest.osm-gh-old
6. Rename israel-and-palestine-latest.osm-gh-new to israel-and-palestine-latest.osm-gh
7. Start a new server
8. Delete the israel-and-palestine-latest.osm-gh-old directory, if exists.

Steps 5 and 6 should be very quick, much quicker than deleting the directory as done in step 8.

**Comment by HarelM** [comment] 2015-12-31 14:15
Sound good, assuming it's possible.

**Comment by zstadler** [comment] 2015-12-31 22:50
Done.

Should the refresh.cmd file be part of repository? If so, where?

**Comment by HarelM** [comment] 2016-01-01 10:56
The GH config is part of this repository, Since they are considered related placing them one next to the other would make sense for me.
I would add a few words to the readme.md file explaining where to place this file and how to configure it in the task scheduler for future reference.
I would also add "title" commands in the script itself instead of comments - this way we will know what the current cmd window is doing.
one last thing is the start server command which looks a bit more complicated compared to what I ran (you can have a look at the run.cmd I created).
Regardless, great work!

**Comment by zstadler** [comment] 2016-01-03 05:27
Perhaps it would make sense to create a separate directory for files that should be added to the Graphhopper installation hierarchy?

**Closed** 2016-01-15 11:28 UTC
Labels: bug
