### ISSUE TITLE
F.R- Add public transportation layer

### ISSUE THREAD

**Issue by Yaniv125** [IsraelHikingMap/Site#1389] opened 2020-12-08 10:58 UTC
Important enhancement:
1. Information about where are bus stops located
2. Open public transportation app on each bus stop
3. Navigate to each bus stop

Good enhancement:
4. What bus lines are in each bus stop
5. Schedule for each line (static and real time)
6. line stops

Advance enhancement:
7. Full navigate to any point or address

How to get this information:
https://www.gov.il/he/departments/general/gtfs_general_transit_feed_specifications

Thanks in advance.
Yaniv.

**Comment by HarelM** [comment] 2020-12-08 11:31
Thanks for the suggestion but I think other apps can and should do it, wouldn't you agree?
Regarding showing bus stops on the map please open an issue in the vectormap repository.
If you want to create an external layer of stops and maintain them I can instruct you raw to do it.

**Comment by Yaniv125** [comment] 2020-12-08 12:12
Thanks for your quick reply!

I split the "bug" in to 3 level: Important, Good and Advance 
The Important is all about linking to "other apps".

Today there is a gap between public transportation apps and hiking maps.
Public transportation apps can't navigate users if they are on hiking points, simply, because they don't have hiking information.

So to overcome this gap , I think it's important to add bus stops layer on the map, so when the user click on a bus stop he will have the option to save the point or/and open it is Public transportation apps.

To get bus stops location information (they updated the static data every week) you need to be register to gov...

**Comment by HarelM** [comment] 2020-12-08 12:35
Bus stops exists in OSM and there's a script that updates them, so in theory you don't need gov data.
For example the following:
https://israelhiking.osm.org.il/poi/OSM/node_1803076744?language=he
Searching תחנת תמרת will result in getting the relevant point.
Having said that, bus stops are of low priority for search and so it will be hard to find them...

I'm not familiar with transportation apps.
There's a feature that's about to land in the next release that might be helpful for this: #1381.
If transportation apps support the [`geo` scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme) this might solve this request, I'm not sure.
If you can check how one can send a location to the transportation apps it would be great...

**Comment by HarelM** [comment] 2020-12-08 12:50
As to the "good" and "advanced" part - I don't think it should be part of this app.
As you said, there are transportation app which are designed to handle the exact scenario of allowing a user to get to a specific bus stop, including time, bus stops, the current location of bugs and what not...
I believe this is the same concept with Waze - you use another app to get you to the starting point of your route and from there on the app will server you when you hike/ride etc.
We did integrated a share location to Waze feature but I don't think we should try and replace Waze (for obvious reasons :-)).
In any case, I'm leaning towards closing this issue as a duplicate of #1381 since I think it can solve the main requirement here, assuming one can create a private POI and share its location with transportation app, waze app, maps app etc...
Please let me know if I'm missing out something basic here...

**Comment by Yaniv125** [comment] 2020-12-08 13:18
gov data is the most reliable one (they update it every week)

about what now exists, It's not practical
it need to be in "Points of Interest" ->bus stops
Then click on a bus stop point to
a. navigate to that point from hiking point
b. open it is Public transportation apps.

I agree on "good" and "advanced" 

I cant see how this bug duplicate  #1381 since there is no practical bus stops point

P.S I test this problem in real hiking, Its very hard to plan, because of this gap...

**Comment by HarelM** [comment] 2020-12-08 14:01
I don't see bus stops getting to be a POI - their name is not defined, there's no point in adding a description and the image is not interesting - i.e. this is not what the site defines as POI.
Having said that, and bare with me:
Lets assume for a minute that bus stops can be seen on the map like gas stations currently do, for example here:
https://israelhiking.osm.org.il/map/18.03/32.7035/35.1932
Planning a route to from a bus stop is possible right now (assuming the above).
In my point of view the only missing part here is the navigation/transportation to the selected bus stop.
Assuming there's a transpiration app that can receive the `geo` scheme as mentioned above all you need to do is create a private POI on the relevant bus station and share the location of that POI with the transportation app.
If all my assumptions are correct issue #1381 should be sufficient to allow this, even if the user experience is not great...

**Comment by Yaniv125** [comment] 2020-12-08 14:16
I understand...I will test that on the next release (assuming bus stops can be seen on the map)
My question is, will work on desktop ? (like linking to google maps or moovit (desktop))

**Comment by HarelM** [comment] 2020-12-08 14:29
Probably not. Sharing data from website on desktop doesn't have a good way to do it currently and most users do not work on the desktop these days...
I would advise to test the following link inside the article and see what happens when you use a desktop app and your mobile browser:
https://en.wikipedia.org/wiki/Geo_URI_scheme
Seems like when clicking this on desktop nothing happens, probably needs a chrome extension to work, so I don't have high hopes...
If moveit or googlemaps is the transportation app of your choice I would make sure it support the above link.
In any case, you could plan the route from desktop, upload to cloud, open in the phone and check the transportation solution...

**Comment by Yaniv125** [comment] 2020-12-08 14:44
desktop - I mean 
Create any point (bus stop, gas...) at IsraelHikingMap site "desktop version" and open it in google map or moovit...
But, maybe this is different bug (or this is possible and I missed it)

**Comment by HarelM** [comment] 2020-12-08 14:56
I don't think this is possible without being specific like we do in Waze for public POIs.
Since there's no known market leader (At least I'm not aware of one) for public transportation I'm not sure this can be done in the desktop version, and sharing a geo location in desktop doesn't work without all kinds of plugins.
So the bottom line is that this feature (#1381) will not work in the desktop...

**Comment by Yaniv125** [comment] 2020-12-08 15:03
If I remember correctly google map have API for that, I can search for that if needed

**Comment by HarelM** [comment] 2020-12-09 07:26
> If I remember correctly google map have API for that, I can search for that if needed
Please do, I believe we con continue this specific requirement in #1381 thread...

**Comment by Yaniv125** [comment] 2020-12-09 10:03
https://developers.google.com/maps/documentation/javascript/geolocation

O.K I will test the public transportation implementation  (on #1381 thread)

Thank you for your replies

**Comment by HarelM** [comment] 2020-12-19 22:24
As for a layer to show the bus stops the solution is the same as #1353 i.e. create a custom layer with only bus stops and add it to the overlay layers much like the waterhole layer.
See this linked issue: IsraelHikingMap/VectorMap#72

**Closed by HarelM** 2020-12-19 22:24 UTC
