### ISSUE TITLE
Open file fails on Android 11

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1451] opened 2021-03-03 11:59 UTC
## What I expect to happen
"Menu -> Save - Share - Files -> Open a file" should work on Android 11 or not be available

## What I did that caused the issue - step by step
1. Save a gpx file on an Android 11 device
2. "Menu -> Save - Share - Files -> Open a file"
3. Select the file and press "Done"
The file is not opened and the application returns to the "Save - Share - Files" choices.

## My environment
* Operating System and version: Android 11
* Web Browser and version: 9.6.126

## Things I think the developers should know, images, links etc.
- User's report was received by mail
- Opening the same file using "Open with... -> Israel Hiking Map" works as expected on Android 11

**Comment by HarelM** [comment] 2021-03-26 23:30
I'm unable to reproduce this on the android emulator when using API level 30 (Android 11).
I don't have the done button though.
Can you share more screenshots of the reproductions steps or a shot screen capture movie?

**Comment by HarelM** [comment] 2021-04-26 20:09
@zstadler can you test this and close this issue if this is not a real problem?

**Comment by zstadler** [comment] 2021-04-27 06:12
It works now!

**Closed** 2021-04-27 06:12 UTC
Labels: App, Medium, bug

**Comment by abhishek7077** [comment] 2021-09-11 03:09
> I'm unable to reproduce this on the android emulator when using API level 30 (Android 11).
> I don't have the done button though.
> Can you share more screenshots of the reproductions steps or a shot screen capture movie?

Could you please check on real device?

**Comment by HarelM** [comment] 2021-09-11 04:35
This was tested or real devices to be working, including right now.
If you encounter an issue please use the app's report a problem button and send us a mail with the relevant screen shots.
