### ISSUE TITLE
Organize the view and edit panes for a POI and a Route

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/Site#1602] opened 2021-09-11 04:50 UTC
## What I expect to happen
That the link I upload to a route, will be used

## What really happened
The link is to the OSM relation

## What I did that caused the issue - step by step
* Opened this route: https://israelhiking.osm.org.il/poi/OSM/relation_8456491?language=he
* Clicked the pencil, updated the description and the site describing the route: https://tourgolan.org.il/listing/south_golan_promenade/
* Clicked the V and waited till IHM shows the new description
* Clicked the link at the bottom of the route pane and was puzzled as it went to OSM

## My environment
Win10+Chrome

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/49042192/132936619-e011f20e-745b-4214-976f-82db8bc0d52a.png)

**Comment by HarelM** [comment] 2021-09-11 04:54
This is by design. The title turned into a link and will point to the link you just added....

**Comment by Tsurha** [comment] 2021-09-11 04:57
But it points to OSM instead to where it shoud https://tourgolan.org.il/listing/south_golan_promenade/

![image](https://user-images.githubusercontent.com/49042192/132936774-35d42ba4-6563-41a6-b621-6b8a0a427835.png)

**Comment by HarelM** [comment] 2021-09-11 05:07
I guess I was not clear...
There's always a link to the relevant OSM entity at the bottom. This is given.
When you add a link to a site and you save you cause the title of the POI to look like a website link (note the blue color and underline in your screenshot above). Clicking the title will go to the address you added, the OSM link will stay the same in any case...

**Comment by Tsurha** [comment] 2021-09-11 05:14
Oh ok. 
Indeed its not a bug. To me its an unexpected design. We can discuss it as an improvement request: 
I do not think the regular user should go to OSM as part of the regular usage. Most of them would like to stay in IHM.  Its too much information. Like sending a user to the underlying Oracle DB so he can examine his information system...

**Comment by Tsurha** [comment] 2021-09-11 05:18
Note that here its to the information site. So we have an inconsistent behavior 

![image](https://user-images.githubusercontent.com/49042192/132937172-69ba7c7e-4f1f-441c-8090-54ced2907488.png)

**Comment by zstadler** [comment] 2021-09-11 06:05
![image](https://user-images.githubusercontent.com/1304610/132938159-fce38ea5-0843-44d2-8c24-70087e0421fa.png)

**Comment by Tsurha** [comment] 2021-09-11 06:23
Thank you Zeev for the technical explanation of how it currently behaves.  

Please consider the following points from a user's point of view:
* A heading as a link is not a common convention. Its underline is likely interpreted as just an underlined header, not as a link. 
* Its only after reading the brief information in the POI or route pane, that the user may want further reading. That's when he is a the bottom of the pane.
* Icons are more encouraging to click, than a link.  
* OSM is irrelevant.  Its not a place to read information about the route or POI. Its a DB and only an advanced user's link.

**Comment by zstadler** [comment] 2021-09-11 06:28
@Tsurha,
If you have a concrete design suggestion, please upload it for discussion.

**Comment by HarelM** [comment] 2021-09-11 06:44
It's probably worth mentioning that these links and icons are rarely rarely clicked...

**Comment by Tsurha** [comment] 2021-09-11 06:50
Design suggestion with little programming effort:

Delete the link from the header. There can be several links so anyway one header is not enough. It's also not a normal internet convention
Add all the user uploaded links to the bottom as icons. There may be several.
The icon GIF should stay as is for your current information sources
The icon GIF for user uploaded links should be an IHM icon
Keep the OSM icon link there. Once a readable information site is added as well, the user can see which one makes better sense to him.

**Comment by zstadler** [comment] 2021-09-11 07:04
- Having an IHM icon for non-IHM sites is misleading. For example, the link to https://tourgolan.org.il/listing/south_golan_promenade/ in שביל דרום הגולן will have an IHM icon.
- Multiple user-provided URLs are not currently supported.
  - Having identical icons for different user-provided URLs would increase the confusion you experienced.
- I don't see the added value for removing the link from the header.

**Comment by Tsurha** [comment] 2021-09-11 07:33
@zstadler - I agree with your points and therefor suggests to:

* Use an internet icon for user provided URLs
* While implementing, see how difficult it is to support presenting multiple user-provided URLs or not, as they are supported in IHM editing. 
* I do not care about the header link. It could be to the first user provided URL or not at all. Whatever. 
* Delete the number coordinates. To me its a long gone UI that was needed before we used digital maps and pins. 
* Keep the height only for POIs.  A route has many heights. 
* Add a sup header above the icons with :מידע נוסף Additional Info:

## Suggested design:
![image](https://user-images.githubusercontent.com/49042192/132939957-32fc2fe4-d640-47cf-aafe-bb4fe4452a47.png)

## IHM Editing supports multiple user URLs: 
![image](https://user-images.githubusercontent.com/49042192/132940249-4db8b287-b4bd-4b95-8d3f-be4afadf8a6d.png)

**Comment by Tsurha** [comment] 2021-09-11 14:23
With such OSM stipulation needing a prefix or a suffix, it seems like IHM editing pane should support just one URL. With intention of it being for the main information site. Multiple should be left for OSM editors where prefix/suffix can be added appropriately.

**Comment by HarelM** [comment] 2021-09-11 14:27
Is this discussion going somewhere? Can I close this issue?

**Comment by Tsurha** [comment] 2021-09-11 15:15
@HarelM 
There are a number of suggestions here for implementation please, if possible.  After considering the discussion, we are left with:
* Change IHM POI and Route editing pane to support just one URL. 
* In presenting a POI and Route, add an internet icon at the bottom (see above example) for that user provided URLs
* Keep the icons for the current information sources
* Add a sub header above the icons with :מידע נוסף Additional Info:
* Keep the header link. 
* Delete the number coordinates. 
* Delete the height just from a route. (Keep the height for POIs)

**Comment by zstadler** [comment] 2021-09-11 15:16
My take on this discussion is that @Tsurha proposed adding an "Internet" icon for the `website` tag next to the OSM icon and adding a "מידע נוסף"/"Additional information" title for the icons:
![image](https://user-images.githubusercontent.com/1304610/132952615-5435352b-f3c7-4136-8163-903359749ebc.png)

**Comment by Tsurha** [comment] 2021-09-11 16:46
In addition
* Keep the distance in routes.  Just move it to where the height is now.  So we have a consistent place for a POI's height and Route's distance.

![image](https://user-images.githubusercontent.com/49042192/132955087-1e1d0011-a83a-4d03-af6f-7e18b6bc7afb.png)

**Comment by HarelM** [comment] 2021-09-18 19:54
Sorry, the only thing I can take from the above requirements is the subheader of "additional info".
I do not agree with the rest of the requirements.
I don't see a reason to move the length, it's important and should be kept where it is, underline for links is the most common way (and the default is you don't use any styling) to present a link. 
I don't see any value in restricting a POI for just one website, this is hardly used if at all to spam OSM with links and starting to restrict it to wiki link and another link is too much work for something that currently is easy to use without complications I.e. It simply works no matter which link you put.
POI coordinates is still a valuable information which I don't see a reason to remove at the moment, it is one of the last things in the screen due to its low importance, maybe in the future it will be removed.

**Comment by HarelM** [comment] 2021-10-03 08:52
Phone conversation summary with @Tsurha:
An icon for the website should be added to the bottom of the POI. In case we'll see that we have a lot of points with a few links to different websites will see how to solve this. I don't think this is the case right now, we can verify this with overpass turbo if needed.
Point location and height is not relevant for routes and areas, and I tend to agree this is not so useful information in general.
I will remove this from the public POI pane. For users who would like to see the coordinates: there's the not so obvious way of converting the public POI to private POI and clicking on the show coordinated button.

**Closed** 2021-10-06 21:47 UTC
Labels: enhancement, Low
