### ISSUE TITLE
linked POI won't open in app

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1283] opened 2020-08-02 10:21 UTC
## What I expect to happen
When opening a linked POI in the app I expect to see the POI details window.

## What really happened
The location centers around the POI but the details window won't open and an error message appears (see image)

## What I did that caused the issue - step by step
Searched for a POI in the app (עין מרג').
Pressed the "share" button on the top of the POI window.
Used Whatsapp to share the link with my self.
Closed the app
Opened the link from whatsapp
Observed behavior

## My environment
* Android
* IHM app version 9.3.106

## Things I think the developers should know, images, links etc.
![image](https://user-images.githubusercontent.com/689201/89120917-d3c70180-d4c2-11ea-88c4-6afa14e97b4d.png)
Route share, and opening sent GPXes works fine for me.

https://israelhiking.osm.org.il/poi/OSM/node_7633054995?language=he

**Comment by HarelM** [comment] 2020-08-02 13:43
Thanks for the input!
I'll be closing this in favor of #1276 since the issue is still open and it is under development.

**Closed by HarelM** 2020-08-02 13:43 UTC

**Comment by zstadler** [comment] 2020-08-03 09:36
> 
> 
> Thanks for the input!
> I'll be closing this in favor of #1276 since the issue is still open and it is under development.

Perhaps the word "[iOS]" should be removed from the title of #1276 as it is expected to address this Android flow too.

**Comment by HarelM** [comment] 2020-08-03 09:44
The feature already exists in android, it is a new feature only in iOS but may affect existing features as do most added features...
I don't see a good reason to remove this prefix, but I'm not sure why it matters here...
