### ISSUE TITLE
Recorded track intermittently visible

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#880] opened 2018-12-10 11:54 UTC
## What I expect to happen
The recorded track should be continuously visible

## What really happened
While recording it only show up when you resize or rotate the map

## What I did that caused the issue - step by step
Planned a route and closed the edit mode (not sure if neccessary)
Pressed the locate button
Pressed the record button
Started moving

## My environment
* Operating System and version: Android 8.00 on SM-G930F
* App beta version 8.068

## Thing I think the developers should know, images, links etc.

**Comment by HarelM** [comment] 2018-12-10 11:56
Duplicate of #876

**Closed by HarelM** 2018-12-10 11:56 UTC
Labels: App, Beta, Critical, bug
