### ISSUE TITLE
Route following mode

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/Site#1134] opened 2020-01-22 17:47 UTC
## Feature
This is a place-holder for discussion.

In a nutshell, it is about the value and the UX for the ability to use the app to follow a planned route.

Some features that could be valuable in this mode:

- Cross-Track alarm: when the GPS position has diverged from the planned route more than a given value.
- Route-based Statistics: remaining distance to target, estimated time to target, etc.
- Re-route based on GPS position.
- Provide directions

**Comment by HarelM** [comment] 2020-01-22 19:08
Duplicate of #929, please decide which one to close. I'm OK with both...

**Closed** 2020-01-30 07:37 UTC
Labels: duplicate
