### ISSUE TITLE
Bad record

### ISSUE THREAD

**Issue by onzd** [IsraelHikingMap/Site#815] opened 2018-09-15 15:30 UTC
## Bug/Feature
I record trail and got a stright line insted of a trail
https://israelhiking.osm.org.il/share/n2YyAMCJEm
## My environment
* Operating System and version:
* Web Browser and version:

**Comment by HarelM** [comment] 2018-09-15 18:16
Thanks for reporting this issue~
It seems that there's a single point in the recording that is misplaced (which causes the straight lines):
```
<trkpt lat="32.8235587" lon="35.2667087">
   <ele>559.92571805736486</ele>
   <time>2018-09-15T08:49:43Z</time>
</trkpt>
```
Can you elaborate on how you used the app? Do you remember when it was in the background and when in the foreground? Do you remember anything strange in the GPS behavior?
Since the time of this recording does not match the time of the previous and next point it seems like a glitch in the code that saves the GPS location and not with the GPS itself, but I can't image what went wrong there...

**Comment by zstadler** [comment] 2018-09-15 19:39
May or may not be related...

I had similar "jumps" and suspected it was caused by the device switching from GPS-based location to network-based location. I changed the Location Services settings from "High Accuracy" to "Device Only" and the problem did not repeat itself (yet).

**Comment by onzd** [comment] 2018-09-16 07:10
The app wad working in the background from 9am saturday. At the begginning
there was no celular signal but after 15 minutes there was a signal. I
worked with the Locus app together with the app but with no recording.1

בתאריך 15 בספט׳ 2018 21:16,‏ "Harel M" <notifications@github.com> כתב:

**Comment by valleyofdawn** [comment] 2018-09-18 15:55
I got an identical error. While working in the background the app recorded a few extra points in a point I had visited earlier. It's as if the timestamps of these points were shifted 15 minutes later.
No GPX to examine unfortunately.

**Comment by HarelM** [comment] 2018-09-18 16:47
Besides keeping the last location and ignore stuff that are not within a reasonable distance or time, I'm not entirely sure what to do here...
Any thoughts are welcome.

**Comment by valleyofdawn** [comment] 2018-09-18 20:53
What is wrong about the outlier point in the above file is not it's position of timestamp which are correct, but its position in the file, which is on line 16181 instead of line 15455, where it belongs. I have no idea how this could have happened.

**Comment by HarelM** [comment] 2018-09-19 21:00
Might be similar or somewhat close to the following issue:
https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/477

The fact that the recording time and location are not in the right place indicates the geolocation service sent an event no at the right time, I have no idea why, but this is the only thing I can think of that might cause this.

I'll add some validation, and see if it helps...

**Comment by HarelM** [comment] 2019-01-06 18:11
@zstadler seemed to have seen this behavior again.
Reopening.
Again. Any thought of a simple check that can spot these flyers are welcome.
All I have in mind is to check if the time of the recording is similar to the current time of the phone (assuming there's no problem with unsychronized clocks between the GPS and phone...)
@zstadler can you please attach/share the bad recording?

**Comment by HarelM** [comment] 2019-03-15 20:30
No new report was made in this issue. Closing for now. Will be open in case new evidence are presented.

**Comment by valleyofdawn** [comment] 2019-05-02 20:40
Sadly, a fresh instance.
https://israelhiking.osm.org.il/share/ZkBadfQxK7

**Comment by valleyofdawn** [comment] 2019-05-03 08:06
Reproducible on my phone.
It happens when you leave the app or hide the screen (short press on the home button).
The app keeps tracking on the background, but **as you return to it**, it briefly shows the position based on cellular reception (indicated by a large blue circle), and creates a distant off-route reading or two.
I don't know if it's just my phone (Xiaomi) or all android machines, please try to reproduce it too.

I made sure the app is not energy-optimized and the phone is not saving battery.
Oruxmaps, in identical scenarios, did not produce these erroneous readings.

**Comment by valleyofdawn** [comment] 2019-05-04 18:53
Made further checks.
It is definitely caused by google assisted location, turning off this service corrects the problem. Once you reactivate the IHM app the assisted location kicks in for a second and produces a first bad reading with no elevation before zeroing in on the GPS read. This is hardly noticeable in the city, where the service is good, but can produce horrible traces outside the city where it is not.
I reproduced this on two different android phones from two makes.
It's an issue we can live with by telling people to switch off assisted location, but on the longer run it could be dealt with by removing reads without elevation from recordings (I hope this is a good criteria for phones that have a barometer as well).

**Comment by HarelM** [comment] 2019-05-05 08:05
I'll invest time in finding a better algorithm for outlier detection, but I don't want to over complicate it...
Removing reads without elevation will probably work for this case, but it's too naive.
I think a proper algorithm will be to check the accuracy of the measurement and check the momentary speed it creates with the previous point to see that we didn't move too far from where we were.
I'll think about how to better solve this and let you know what I come up with.

**Comment by HarelM** [comment] 2019-05-05 08:33
In case this interest you current implementation can be found here - this is the class that emits the position, it is used everywhere in the app, not just for recording.
https://github.com/IsraelHikingMap/Site/blob/87e457ea32c72ac0d8783a371328efa458d5b949/IsraelHiking.Web/sources/application/services/geo-location.service.ts#L190

**Comment by HarelM** [comment] 2019-05-05 20:03
@valleyofdawn thanks for the share.
I have added some verification based on it to the code:
1. GPS point is valid for recording if its accuracy circle is less than 50 meters.
2. GPS point is valid if the speed (between it and the last point) is less than 200 Km/hr
3. The time difference between it and the last point is less than 60 seconds.

@valleyofdawn, @zstadler I have made a commit with this fix, please take the time to install the app and test this.
In case of a bad recording a share of this recording is currently enough for me to be able to add validation rules to the location provider. More interesting cases where we'll need a debug version can be studied in the future.
If this solves the current issue with the google location I think this issue can be closed, and maybe reopened in the future if we encounter an incorrect recording.

**Comment by HarelM** [comment] 2019-05-07 15:54
Closing this issue as I have made a fix to this specific scenario where invalid points are added to the recorded line.
I know there are other issues related to recording being stopped but we'll open a separate issue after with discuss the problem internally.

**Closed by HarelM** 2019-05-07 15:54 UTC
Labels: High, bug
