### ISSUE TITLE
Use old bike map for thumbnails and OSM editting

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Site#1181] opened 2020-03-16 10:29 UTC
## Feature
When sharing a route from the vector bike map, or editing OSM from the bike map, the raster hiking map is used.
The raster bike map is more appropriate.

**Comment by HarelM** [comment] 2020-03-16 10:37
We should define which raster layers are used, where they are stored and when they are updated first.
This is just a side effect of the latest change...

**Comment by HarelM** [comment] 2020-03-18 19:18
This is actually a duplicate of #1131 ...
Please raise this valid concern there.

**Closed by HarelM** 2020-03-18 19:18 UTC
